/**
 * Content model of the 13-section region template, shared by the city pages
 * (/messdienstanbieter/<slug>) and the Germany page (/messdienstanbieter).
 *
 * Designed against all 23 designs (22 cities + Germany): it holds every text
 * that differs between them, written out in full. What is identical in every
 * design (nav, KPI numbers, timeline, billing card figures, phone and
 * portfolio data, trio demo texts, references, partner logos) stays in the
 * components. City modules are generated by `scripts/extract-city.ts`.
 */
import type { ImageAsset } from "$lib/components/Basic/Image/types";
import type { LogoKey } from "$lib/landing/data/logos";
import type { CitySlug } from "$lib/landing/pages/messdienstanbieter-city/cities";
import type { FaqItem } from "$lib/landing/sections/Faq.svelte";

export type SectionHead = { eyebrow: string; title: string; text: string };
export type CardHead = { title: string; text: string };

export interface RegionContent {
	/** Unset on the Germany page. */
	slug?: CitySlug;
	/** "Berlin", "Deutschland" */
	name: string;
	/** Required and unique per page (title 30–60, description 120–160 chars). */
	seo: { title: string; description: string; ogTitle: string };
	/** 2–4 nearby cities, rendered only when live. Empty on the Germany page. */
	links: { nearby: CitySlug[] };
	/** Banner above the nav: "Ab 1.1.2027 … Wir prüfen Ihren Berliner Bestand." */
	bannerText: string;

	hero: {
		/** "Messdienst für Hausverwaltungen in Berlin" */
		tag: string;
		/** The page's H1. */
		title: string;
		lede: string;
		checks: [string, string, string];
		photo: ImageAsset;
		photoAlt: string;
		/** "24 WE" in the hero card stack. */
		units: number;
	};

	/** The example property, reused by the hero, AllInOne, map, billing, duo and trio visuals. */
	example: {
		/** "Kastanienallee 12" */
		address: string;
		/** "Prenzlauer Berg · Altbau" */
		area: string;
		/** Units counted in the AllInOne cards and the trio's tenant flow. */
		units: number;
		/** Second property of the portfolio browser: "Boxhagener Str. 31". */
		secondAddress: string;
		/** Mounting appointment in the AllInOne cards: "Di, 14.10." and "8–10 Uhr". */
		appointment: { day: string; time: string };
		/** Tenant avatars in the "Mieterkommunikation" card. */
		avatars: [string, string, string];
		/** Tenant avatar in the trio's uVI flow. */
		tenant: string;
	};

	logoStrip: { text: string; logos: LogoKey[] };
	noWait: SectionHead & { notes: [string, string, string] };
	/** Card paragraphs of Installation, Mieterkommunikation, Ablesung & uVI, Abrechnung. */
	allInOne: SectionHead & { cards: [string, string, string, string] };
	map: RegionMap;
	/** The dark "Auf Knopfdruck" section (its eyebrow is the same everywhere). */
	billing: { title: string; text: string; checks: [string, string, string] };
	/** "Service aus Berlin" + the labels under the three KPIs. */
	service: SectionHead & { kpis: [string, string, string] };
	duo: { uvi: CardHead; portfolio: CardHead };
	/** Paragraphs under the three trio demos. */
	trio: [string, string, string];
	/** Background of the references card; the quotes are the same everywhere. */
	referencesPhoto: ImageAsset;
	faq: FaqItem[];
	final: { title: string; sub: string };
}

export type MapShape =
	| { kind: "path"; d: string }
	| { kind: "dot"; cx: number; cy: number; r: number };

export type MapLabel = {
	x: number;
	y: number;
	lines: string[];
	/** `dy` of the 2nd+ line, px. */
	lineHeight?: number;
	/** The design's `.sm` labels, hidden below 560 px. */
	small?: boolean;
	/** Per-label font size, px (otherwise the map's). */
	fontSize?: number;
};

export type MapDistrict = {
	/** Key of the district; defaults to `name`. Needed where a city dot and a state share a name. */
	id?: string;
	/** Shown in the info panel and used as the accessible name. */
	name: string;
	/** Germany page: city dots link to the city pages. */
	href?: string;
	shape: MapShape;
	/** Small shapes (the city-states on the Germany map) have none. */
	label?: MapLabel;
	/** "Typischer Bestand" */
	stock: string;
	hint: string;
};

export interface RegionMap {
	/** "In ganz Berlin" */
	eyebrow: string;
	title: string;
	sub: string;
	/** "Karte der Berliner Bezirke" */
	ariaLabel: string;
	viewBox: string;
	/** Non-interactive city outline, drawn under the districts. */
	outline?: string;
	/** Info panel key: "Bezirk", "Stadtbezirk", "Bundesland" … */
	areaLabel: string;
	districts: MapDistrict[];
	/** `id` (or name) of the district selected on load. */
	defaultDistrict: string;
	/** The pulsing example property; none on the Germany map. */
	marker?: { x: number; y: number };
	/** "Beispielobjekt Kastanienallee 12" */
	legend: string;
	style?: {
		strokeWidth?: number;
		labelSize?: number;
		/**
		 * The Berlin and München designs predate the map frame of the later
		 * designs (44 px under the map for the legend, height capped at 600 px):
		 * "none" reserves no legend space, "narrow" 46 px below 560 px only.
		 */
		legacyFrame?: "none" | "narrow";
	};
}

export const districtId = (d: MapDistrict) => d.id ?? d.name;

/** What a city's `<slug>-map.ts` holds; the map's copy lives in the content module. */
export type MapGeometry = Omit<
	RegionMap,
	"eyebrow" | "title" | "sub" | "legend"
>;
