// Generated by scripts/extract-city.ts from the "Heidi Augsburg" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/augsburg/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/augsburg/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./augsburg-map";

const content: RegionContent = {
	slug: "augsburg",
	seo: {
		title: "Messdienstanbieter in Augsburg wechseln | Heidi Systems",
		description:
			"Messdienst in Augsburg vom Bismarckviertel bis Haunstetten: Heidi übernimmt Ihre vorhandenen Zähler sofort und organisiert Montage, Mieterinfo und Abrechnung.",
		ogTitle: "Messdienst wechseln in Augsburg. Ohne Umstellungsstress.",
	},
	links: { nearby: ["muenchen", "stuttgart"] },
	name: "Augsburg",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Augsburger Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Augsburg",
		title: "Messdienst wechseln in Augsburg. Ohne Umstellungsstress.",
		lede: "Ob Altbau im Bismarckviertel oder Wohnanlage in Haunstetten: Heidi übernimmt Ihre vorhandenen Zähler sofort und organisiert Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bestandszähler sofort nutzbar",
			"Ein Partner für den ganzen Ablauf",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Augsburg",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Bismarckstraße 12",
		area: "Bismarckviertel · Altbau",
		units: 20,
		secondAddress: "Neuburger Straße 31",
		appointment: {
			day: "Do, 29.10.",
			time: "8–10 Uhr",
		},
		avatars: ["EK", "HV", "LW"],
		tenant: "EK",
	},
	logoStrip: {
		text: "Bundesweit rechnen Hausverwaltungen schon mit Heidi ab.",
		logos: [
			"progera",
			"wagner",
			"neckar",
			"werne",
			"dumax",
			"hsp",
			"berlin",
			"vitec",
			"harte",
			"schleicher",
			"niesen",
			"raumgold",
		],
	},
	noWait: {
		eyebrow: "Wechsel ohne Wartezeit",
		title: "Restlaufzeit beim alten Messdienst? Egal.",
		text: "Wechseln Sie jetzt: Heidi liest die verbauten Zähler aus und rechnet ab. Heidi-Funkzähler werden erst montiert, wenn der alte Vertrag ausgelaufen ist.",
		notes: [
			"Ohne Parallelbetrieb, ohne Datenverlust",
			"Kündigung übernimmt Heidi per Vollmacht",
			"Eine Ansprechperson für alles",
		],
	},
	allInOne: {
		eyebrow: "Rundum-Service",
		title: "Alles organisiert. Von der ersten Montage an.",
		text: "Von der ersten Montage bis zur fertigen Abrechnung organisiert Heidi alles. Ihr Team spart sich Terminabsprachen, Aushänge und das Einsammeln von Ablesewerten.",
		cards: [
			"92 % Erfolg beim ersten Termin, 1–2 h Zeitfenster für Ihre Mieter, ausgeführt von zertifizierten Heidi-Monteuren.",
			"Heidi informiert Ihre Mieter per Aushang und Ankündigung und beantwortet ihre Fragen direkt.",
			"Per Funk abgelesen, ohne Termin in der Wohnung. Dazu jeden Monat die uVI nach HKVO, vollautomatisch.",
			"Rechtssicher abgerechnet auf Knopfdruck und direkt an Ihr ERP- oder CRM-System übergeben.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Augsburg",
		title: "Von Oberhausen bis Haunstetten. In der ganzen Stadt.",
		sub: "Fahren Sie über einen Stadtteil und sehen Sie, wie Heidi typische Augsburger Bestände übernimmt.",
		legend: "Beispielobjekt Bismarckstraße 12",
	},
	billing: {
		title: "Ein Klick. Alle Abrechnungen fertig.",
		text: "Verbräuche per Funk, Kostenarten zugeordnet, Verteilerschlüssel hinterlegt. Sie klicken, Heidi rechnet jede Einheit ab.",
		checks: [
			"Nach Heizkostenverordnung",
			"Plausibilitätscheck pro Einheit",
			"Direkt in Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Augsburg",
		title: "Ein fester Ansprechpartner für Ihren Augsburger Bestand.",
		text: "Ob Innenstadt, Pfersee oder Lechhausen: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"der Montagen klappen beim ersten Termin",
			"Tage Vorlauf, bevor montiert wird",
			"Zeitfenster für Mieter bei der Montage",
		],
	},
	duo: {
		uvi: {
			title: "Verbrauchsinformation für Mieter. Monat für Monat automatisch.",
			text: "Ihre Mieter sehen monatlich ihren Verbrauch nach HKVO, mit Vergleich zum Vorjahresmonat. Ihr Team muss dafür nichts tun.",
		},
		portfolio: {
			title: "Liegenschaften verwalten. Alles an einem Ort.",
			text: "Eine Plattform für den ganzen Bestand: Montagen, Ablesungen und Abrechnungen jeder Liegenschaft, mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Ein Klick genügt: Aus den Funkwerten wird die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Heidi kümmert sich um Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung. Ihr Team hat damit nichts zu tun.",
		"Jede Mietpartei hat einen persönlichen Zugang und sieht dort monatlich ihre Verbrauchsinformation, wie es die HKVO vorgibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Übernimmt Heidi unsere vorhandenen Zähler?",
			answer:
				"Sie bleiben. Heidi liest sie aus, wertet die Verbräuche aus und erstellt die Abrechnung. Getauscht wird erst, wenn Ihr Vertrag mit dem bisherigen Messdienst endet.",
		},
		{
			question: "Was ist mit der Restlaufzeit unseres Vertrags?",
			answer:
				"Ja. Sie wechseln sofort, unabhängig von der Restlaufzeit. Die Kündigung übernehmen wir per Vollmacht.",
		},
		{
			question: "Wie werden unsere Mieter eingebunden?",
			answer:
				"Das machen wir. 14 Tage vor der Montage geht die Ankündigung raus, mit Zeitfenster von 1–2 Stunden. Rückfragen beantwortet Heidi selbst.",
		},
		{
			question: "Wie aufwendig ist die Heizkostenabrechnung?",
			answer:
				"Auf Knopfdruck: Die Verbräuche sind per Funk erfasst, Heidi erstellt die Abrechnung, Sie prüfen das Ergebnis und geben es frei.",
		},
		{
			question: "Welche Kosten entstehen mit Heidi?",
			answer:
				'Abgerechnet wird pro tatsächlich installiertem Zähler, dazu eine Abrechnungspauschale. Ihr konkretes <a href="/preise">Angebot</a> für den Augsburger Bestand bekommen Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Augsburg. Heute.",
		sub: "Unterschreiben, zurücklehnen. Heidi erledigt den Rest.",
	},
};

export default content;
