// Generated by scripts/extract-city.ts from the "Heidi Berlin" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/berlin/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/berlin/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./berlin-map";

const content: RegionContent = {
	slug: "berlin",
	seo: {
		title: "Messdienstanbieter Berlin ohne Wartezeit | Heidi Systems",
		description:
			"Messdienst für Hausverwaltungen in Berlin: Heidi übernimmt Ihre Zähler sofort und erledigt Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Berlin. Ohne Wartezeit.",
	},
	links: { nearby: ["leipzig", "dresden", "hannover"] },
	name: "Berlin",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Berliner Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Berlin",
		title: "Messdienst wechseln in Berlin. Ohne Wartezeit.",
		lede: "Heidi übernimmt Ihre bestehenden Zähler sofort und kümmert sich um alles: Installation, Mieterkommunikation, Ablesung und die Heizkostenabrechnung auf Knopfdruck.",
		checks: [
			"Bestehende Zähler sofort nutzen",
			"Alles aus einer Hand",
			"Abrechnung auf Knopfdruck",
		],
		photoAlt: "Berliner Altbau-Mehrfamilienhaus",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Kastanienallee 12",
		area: "Prenzlauer Berg · Altbau",
		units: 24,
		secondAddress: "Boxhagener Str. 31",
		appointment: {
			day: "Di, 14.10.",
			time: "8–10 Uhr",
		},
		avatars: ["AK", "MS", "JB"],
		tenant: "AK",
	},
	logoStrip: {
		text: "Hausverwaltungen in Berlin und ganz Deutschland rechnen bereits mit Heidi ab.",
		logos: [
			"berlin",
			"dumax",
			"harte",
			"hsp",
			"raumgold",
			"schleicher",
			"vitec",
			"wagner",
			"werne",
			"neckar",
			"niesen",
			"progera",
		],
	},
	noWait: {
		eyebrow: "Kein Warten aufs Vertragsende",
		title: "Ihr Vertrag läuft noch? Wechseln Sie trotzdem heute.",
		text: "Heidi liest Ihre vorhandenen Zähler aus und rechnet ab, egal wie lange der Vertrag mit dem bisherigen Messdienst noch läuft. Getauscht wird erst, wenn er endet.",
		notes: [
			"Kein Parallelbetrieb, kein Datenverlust",
			"Kündigung übernehmen wir per Vollmacht",
			"Ein Ansprechpartner ab dem ersten Tag",
		],
	},
	allInOne: {
		eyebrow: "Alles aus einer Hand",
		title: "Von der Montage bis zur Abrechnung. Wir kümmern uns.",
		text: "Sie unterschreiben einmal. Heidi organisiert den Rest, ohne dass Ihr Team Termine, Aushänge oder Ablesewerte hinterherlaufen muss.",
		cards: [
			"Zertifizierte Heidi-Monteure, 92 % Erfolg beim ersten Termin und 1–2 h Zeitfenster für Ihre Mieter.",
			"Aushänge, Terminankündigungen und Rückfragen der Mieter laufen über Heidi, nicht über Ihr Postfach.",
			"Funkablesung ohne Termin vor Ort und die monatliche Verbrauchsinformation nach HKVO, automatisch.",
			"Rechtssichere Heizkostenabrechnung auf Knopfdruck, direkt übergeben an Ihr ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Berlin",
		title: "Von Spandau bis Köpenick. Wir sind vor Ort.",
		sub: "Fahren Sie über einen Bezirk und sehen Sie, wie Heidi typische Berliner Bestände übernimmt.",
		legend: "Beispielobjekt Kastanienallee 12",
	},
	billing: {
		title: "Die Heizkostenabrechnung. Auf Knopfdruck.",
		text: "Alle Verbräuche liegen per Funk vor, Kostenarten sind zugeordnet. Sie klicken einmal, Heidi erstellt die Abrechnungen für jede Einheit.",
		checks: [
			"Rechtssicher nach Heizkostenverordnung",
			"Plausibilitätsprüfung für jede Einheit",
			"Übergabe an Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service aus Berlin",
		title: "Ein Team in Berlin. Ein Ansprechpartner für Sie.",
		text: "Heidi sitzt in Berlin. Ihre Verwaltung bekommt eine feste Ansprechperson, die Ihren Bestand kennt.",
		kpis: [
			"Montagen beim ersten Termin erfolgreich",
			"Tage Vorankündigung an Mieter",
			"Zeitfenster für Mieter am Montagetag",
		],
	},
	duo: {
		uvi: {
			title: "Verbrauchsinformation für Ihre Mieter. Jeden Monat automatisch.",
			text: "Jede Mietpartei sieht ihren Verbrauch monatlich nach Heizkostenverordnung, mit Vergleich zum Vorjahr. Ohne Aufwand für Ihr Team.",
		},
		portfolio: {
			title: "Ihr Portfolio im Blick. Alle Liegenschaften auf einer Plattform.",
			text: "Montagen, Ablesungen und Abrechnungen für jede Liegenschaft an einem Ort, egal ob Heidi-Funkzähler oder übernommene Bestandszähler.",
		},
	},
	trio: [
		"Alle Verbräuche liegen per Funk vor. Ein Klick, und Heidi erstellt die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Kündigung per Vollmacht, Montage, Mieterkommunikation und Abrechnung. Ihr Team muss nichts koordinieren.",
		"Jede Mietpartei bekommt einen eigenen Zugang und sieht ihre Verbrauchsinformation jeden Monat, wie es die HKVO verlangt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Können Sie unsere bestehenden Zähler übernehmen?",
			answer:
				"Ja. Heidi liest Ihre vorhandenen Zähler aus, wertet die Verbräuche aus und erstellt die Abrechnung. Ausgetauscht wird erst, wenn der Vertrag mit Ihrem bisherigen Messdienst endet.",
		},
		{
			question: "Müssen wir warten, bis unser Vertrag ausläuft?",
			answer:
				"Nein. Sie können sofort zu Heidi wechseln, egal wie lange der Vertrag noch läuft. Die Kündigung übernehmen wir mit Ihrer Vollmacht.",
		},
		{
			question: "Wer informiert die Mieter?",
			answer:
				"Wir. Heidi kündigt Montagetermine 14 Tage vorher an, gibt den Mietern ein Zeitfenster von 1–2 Stunden und beantwortet Rückfragen direkt.",
		},
		{
			question: "Wie schnell ist die Heizkostenabrechnung fertig?",
			answer:
				"Da alle Verbräuche per Funk vorliegen, erstellt Heidi die Abrechnung auf Knopfdruck. Sie prüfen das Ergebnis und geben es frei.",
		},
		{
			question: "Was kostet Heidi?",
			answer:
				'Abgerechnet wird nach der Anzahl der tatsächlich installierten Zähler, dazu kommt eine Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Berliner Bestand erhalten Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Berlin. Heute.",
		sub: "Eine Unterschrift. Um den Rest kümmern wir uns.",
	},
};

export default content;
