// Generated by scripts/extract-city.ts from the "Heidi Bielefeld" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/bielefeld/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/bielefeld/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./bielefeld-map";

const content: RegionContent = {
	slug: "bielefeld",
	seo: {
		title: "Messdienstanbieter Bielefeld ohne Mehrarbeit | Heidi Systems",
		description:
			"Messdienst für Bielefelder Hausverwaltungen: vom Bielefelder Westen bis Sennestadt übernimmt Heidi Ihre bestehenden Zähler und die Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Bielefeld. Ohne Mehrarbeit.",
	},
	links: { nearby: ["hannover", "dortmund"] },
	name: "Bielefeld",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Bielefelder Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Bielefeld",
		title: "Messdienst wechseln in Bielefeld. Ohne Mehrarbeit.",
		lede: "Ob Altbau im Bielefelder Westen oder Wohnanlage in Sennestadt: Heidi übernimmt Ihre bestehenden Zähler sofort und organisiert Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bestandszähler sofort nutzbar",
			"Ein Partner für den ganzen Ablauf",
			"Heizkostenabrechnung auf Knopfdruck",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Bielefeld",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Arndtstraße 12",
		area: "Bielefelder Westen · Altbau",
		units: 20,
		secondAddress: "Jöllenbecker Straße 31",
		appointment: {
			day: "Mo, 19.10.",
			time: "7–9 Uhr",
		},
		avatars: ["DM", "LW", "RS"],
		tenant: "DM",
	},
	logoStrip: {
		text: "Verwaltungen aus ganz Deutschland vertrauen bei der Abrechnung auf Heidi.",
		logos: [
			"neckar",
			"schleicher",
			"niesen",
			"raumgold",
			"progera",
			"dumax",
			"harte",
			"vitec",
			"hsp",
			"berlin",
			"werne",
			"wagner",
		],
	},
	noWait: {
		eyebrow: "Sofortiger Wechsel",
		title: "Ihr alter Vertrag läuft noch Jahre? Starten Sie jetzt.",
		text: "Ihr bisheriger Messdienstvertrag läuft weiter, Heidi übernimmt trotzdem schon jetzt Auslesung und Abrechnung mit den vorhandenen Zählern. Der Gerätetausch folgt zum Vertragsende.",
		notes: [
			"Nahtloser Übergang ohne Datenverlust",
			"Kündigung per Vollmacht übernommen",
			"Ein Ansprechpartner ab Start",
		],
	},
	allInOne: {
		eyebrow: "Komplettservice",
		title: "Ein Partner für den ganzen Ablauf.",
		text: "Einmal unterschrieben, organisiert Heidi Montage, Mieterinfo, Ablesung und Abrechnung. Ihr Team muss keinen Terminen, Aushängen oder Ablesewerten mehr hinterherlaufen.",
		cards: [
			"Zertifizierte Heidi-Monteure: 92 % der Montagen klappen beim ersten Termin, Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Terminankündigungen, Aushänge und Fragen der Mieter laufen komplett über Heidi.",
			"Per Funk abgelesen, ohne Termin in der Wohnung. Dazu jeden Monat die uVI nach HKVO, vollautomatisch.",
			"Die rechtssichere Heizkostenabrechnung entsteht per Klick und landet direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Bielefeld",
		title: "Von Jöllenbeck bis Sennestadt. In allen zehn Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Bielefelder Bestände übernimmt.",
		legend: "Beispielobjekt Arndtstraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung in Sekunden.",
		text: "Alles ist vorbereitet: Funkwerte erfasst, Kostenarten zugeordnet. Sie klicken, Heidi erstellt die Abrechnungen.",
		checks: [
			"Rechtssicher gemäß HKVO",
			"Automatische Plausibilitätsprüfung",
			"Export in Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Bielefeld",
		title: "Ihre Bielefelder Objekte. Eine feste Ansprechperson.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Westen, Brackwede oder Heepen. Montage, Ablesung und Abrechnung folgen in Bielefeld demselben bewährten Ablauf.",
		kpis: [
			"beim ersten Termin montiert",
			"Tage Vorankündigung für Ihre Mieter",
			"Zeitfenster für jede Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Verbrauchsinformation für Mieter. Monat für Monat automatisch.",
			text: "Monat für Monat sieht jede Mietpartei ihren Verbrauch nach HKVO, mit Vorjahresvergleich. Ihr Team hat keine Arbeit damit.",
		},
		portfolio: {
			title: "Ihr gesamter Bestand. Auf einer Plattform.",
			text: "Eine Plattform für den ganzen Bestand: Montagen, Ablesungen und Abrechnungen jeder Liegenschaft, mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Die Verbrauchswerte liegen per Funk bereit. Ein Klick, und die Abrechnung für jede Einheit steht, rechtssicher nach HKVO.",
		"Heidi kündigt per Vollmacht, montiert, informiert Ihre Mieter und rechnet ab. Sie müssen nichts koordinieren.",
		"Jede Mietpartei hat einen persönlichen Zugang und sieht dort monatlich ihre Verbrauchsinformation, wie es die HKVO vorgibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Können vorhandene Zähler bleiben?",
			answer:
				"Ja, Heidi arbeitet mit den Zählern, die bereits verbaut sind: auslesen, auswerten, abrechnen. Der Austausch folgt erst zum Vertragsende beim bisherigen Anbieter.",
		},
		{
			question: "Wann können wir frühestens wechseln?",
			answer:
				"Ja, sofort und unabhängig von der Restlaufzeit. Mit Ihrer Vollmacht kündigen wir beim bisherigen Messdienst.",
		},
		{
			question: "Wie läuft die Kommunikation mit den Mietern?",
			answer:
				"Heidi. Wir kündigen jede Montage 14 Tage vorher an, geben ein Zeitfenster von 1–2 Stunden vor und beantworten die Fragen der Mieter.",
		},
		{
			question: "Wie aufwendig ist die Heizkostenabrechnung?",
			answer:
				"Sehr schnell. Weil die Verbräuche per Funk vorliegen, erzeugt Heidi die Abrechnung mit einem Klick. Danach prüfen Sie und geben frei.",
		},
		{
			question: "Wie rechnet Heidi ab?",
			answer:
				'Sie zahlen nur für tatsächlich installierte Zähler plus eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein <a href="/preise">Angebot</a> für Ihren Bielefelder Bestand.',
		},
	],
	final: {
		title: "Jetzt in Bielefeld den Messdienst wechseln.",
		sub: "Sie unterschreiben, Heidi übernimmt.",
	},
};

export default content;
