// Generated by scripts/extract-city.ts from the "Heidi Bochum" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/bochum/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/bochum/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./bochum-map";

const content: RegionContent = {
	slug: "bochum",
	seo: {
		title: "Messdienstanbieter Bochum ohne Hin und Her | Heidi Systems",
		description:
			"Messdienst in Bochum für Altbau in Ehrenfeld und Zechensiedlungen in Wattenscheid: Heidi übernimmt Ihre Zähler sofort, inklusive Montage und Abrechnung.",
		ogTitle: "Messdienst wechseln in Bochum. Ohne Hin und Her.",
	},
	links: { nearby: ["essen", "dortmund", "wuppertal"] },
	name: "Bochum",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Bochumer Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Bochum",
		title: "Messdienst wechseln in Bochum. Ohne Hin und Her.",
		lede: "Ob Altbau im Ehrenfeld oder Zechensiedlung in Wattenscheid: Heidi übernimmt Ihre vorhandenen Zähler sofort und kümmert sich um Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bestandszähler sofort nutzbar",
			"Alles bei einem Partner",
			"Abrechnung in Sekunden",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Bochum",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Königsallee 12",
		area: "Ehrenfeld · Altbau",
		units: 36,
		secondAddress: "Hattinger Straße 31",
		appointment: {
			day: "Mo, 12.10.",
			time: "7–9 Uhr",
		},
		avatars: ["NB", "SY", "CL"],
		tenant: "NB",
	},
	logoStrip: {
		text: "Hausverwaltungen von Nord bis Süd setzen auf Heidi.",
		logos: [
			"hsp",
			"raumgold",
			"werne",
			"harte",
			"progera",
			"vitec",
			"niesen",
			"neckar",
			"wagner",
			"dumax",
			"berlin",
			"schleicher",
		],
	},
	noWait: {
		eyebrow: "Wechsel jederzeit",
		title: "Langer Restvertrag? Kein Grund zu warten.",
		text: "Heidi startet mit Ihren vorhandenen Zählern: Auslesen und Abrechnen läuft ab sofort über uns, auch wenn der Vertrag mit dem bisherigen Messdienst noch Jahre gilt. Die Geräte tauschen wir erst zum Vertragsende.",
		notes: [
			"Übergang ohne Datenverlust",
			"Kündigung per Vollmacht inklusive",
			"Feste Ansprechperson ab dem Start",
		],
	},
	allInOne: {
		eyebrow: "Komplettservice",
		title: "Ein Partner für den ganzen Ablauf.",
		text: "Nach einer Unterschrift organisiert Heidi den gesamten Ablauf. Termine, Aushänge und Ablesewerte muss Ihr Team nicht mehr nachhalten.",
		cards: [
			"Montage durch zertifizierte Heidi-Monteure: 92 % Erfolg beim ersten Termin, 1–2 h Zeitfenster für die Mieter.",
			"Ankündigungen, Aushänge und Mieterfragen übernimmt Heidi. Ihr Postfach bleibt frei.",
			"Ablesung per Funk, ohne dass jemand in die Wohnung muss. Die monatliche uVI nach HKVO kommt automatisch.",
			"Heizkostenabrechnung per Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Bochum",
		title: "Von Wattenscheid bis Langendreer. In allen sechs Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Bochumer Bestände übernimmt.",
		legend: "Beispielobjekt Königsallee 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Per Klick fertig.",
		text: "Weil Verbräuche per Funk vorliegen und Kostenarten zugeordnet sind, reicht ein Klick für die Abrechnung jeder Einheit.",
		checks: [
			"Nach Heizkostenverordnung",
			"Plausibilitätsprüfung pro Einheit",
			"Direkt in Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Bochum",
		title: "Bochumer Bestand, persönlich betreut.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Ehrenfeld, Wattenscheid oder Langendreer. Montage, Ablesung und Abrechnung folgen in Bochum demselben bewährten Ablauf.",
		kpis: [
			"Erfolgsquote beim ersten Montagetermin",
			"Tage Vorlauf für Ihre Mieter",
			"Zeitfenster für Ihre Mieter",
		],
	},
	duo: {
		uvi: {
			title: "Monatliche Verbrauchsinfo für Ihre Mieter. Vollautomatisch.",
			text: "Heidi stellt jeder Mietpartei monatlich ihren Verbrauch bereit, nach HKVO und mit Vorjahresvergleich. Ihr Team ist nicht beteiligt.",
		},
		portfolio: {
			title: "Ihr gesamter Bestand. Auf einer Plattform.",
			text: "Pro Liegenschaft sehen Sie Montagen, Ablesungen und Abrechnungen an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Die Funkwerte sind schon da. Mit einem Klick erstellt Heidi die Abrechnung jeder Einheit, rechtssicher nach HKVO.",
		"Von der Kündigung per Vollmacht bis zur fertigen Abrechnung organisiert Heidi alles, auch Montage und Mieterinfo.",
		"Jede Mietpartei erhält einen persönlichen Zugang und sieht ihre monatliche Verbrauchsinformation, so wie es die HKVO vorschreibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Können unsere bisherigen Zähler weiter genutzt werden?",
			answer:
				"Ja, Heidi arbeitet mit den Zählern, die bereits verbaut sind: auslesen, auswerten, abrechnen. Der Austausch folgt erst zum Vertragsende beim bisherigen Anbieter.",
		},
		{
			question: "Wann können wir frühestens wechseln?",
			answer:
				"Nein. Heidi startet direkt, die Restlaufzeit spielt keine Rolle. Gekündigt wird per Vollmacht durch uns.",
		},
		{
			question: "Wie werden unsere Mieter eingebunden?",
			answer:
				"Über Heidi. Wir kündigen Montagen 14 Tage im Voraus an, nennen ein Zeitfenster von 1–2 Stunden und kümmern uns um Rückfragen.",
		},
		{
			question: "Wie viel Arbeit macht die Heizkostenabrechnung?",
			answer:
				"Sobald Sie klicken: Die Verbräuche liegen per Funk vor, Heidi erstellt die Abrechnung, Sie prüfen und geben frei.",
		},
		{
			question: "Wie rechnet Heidi ab?",
			answer:
				'Grundlage sind die installierten Zähler und eine Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Bochumer Bestand gibt es nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Ihr Messdienst in Bochum. Ab heute mit Heidi.",
		sub: "Unterschreiben, zurücklehnen. Heidi erledigt den Rest.",
	},
};

export default content;
