// Generated by scripts/extract-city.ts from the "Heidi Bonn" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/bonn/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/bonn/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./bonn-map";

const content: RegionContent = {
	slug: "bonn",
	seo: {
		title: "Messdienstanbieter in Bonn wechseln | Heidi Systems",
		description:
			"Messdienst in Bonn von der Südstadt bis zum Hardtberg: Heidi übernimmt Ihre vorhandenen Zähler sofort und kümmert sich um Montage, Mieterinfo und Abrechnung.",
		ogTitle: "Messdienst wechseln in Bonn. Ohne Reibungsverluste.",
	},
	links: { nearby: ["koeln", "duesseldorf"] },
	name: "Bonn",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Bonner Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Bonn",
		title: "Messdienst wechseln in Bonn. Ohne Reibungsverluste.",
		lede: "Ob Gründerzeit in der Südstadt oder Wohnanlage am Hardtberg: Heidi übernimmt Ihre vorhandenen Zähler sofort und kümmert sich um Montage, Mieterinfo, Ablesung und Abrechnung.",
		checks: [
			"Vorhandene Zähler weiter nutzen",
			"Alles bei einem Partner",
			"Abrechnung ohne Wartezeit",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Bonn",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Poppelsdorfer Allee 12",
		area: "Südstadt · Altbau",
		units: 26,
		secondAddress: "Königswinterer Straße 31",
		appointment: {
			day: "Mo, 09.11.",
			time: "10–12 Uhr",
		},
		avatars: ["DM", "CL", "HV"],
		tenant: "DM",
	},
	logoStrip: {
		text: "Bundesweit rechnen Hausverwaltungen schon mit Heidi ab.",
		logos: [
			"harte",
			"wagner",
			"niesen",
			"vitec",
			"raumgold",
			"berlin",
			"progera",
			"werne",
			"neckar",
			"dumax",
			"schleicher",
			"hsp",
		],
	},
	noWait: {
		eyebrow: "Heute wechseln",
		title: "Noch an den alten Messdienst gebunden? Wechseln Sie trotzdem.",
		text: "Heidi rechnet ab sofort mit Ihren vorhandenen Zählern ab, egal wie lange der alte Vertrag noch gilt. Erst zum Vertragsende tauschen wir auf Heidi-Funkzähler.",
		notes: [
			"Ohne Parallelbetrieb, ohne Datenverlust",
			"Kündigung per Vollmacht durch Heidi",
			"Fester Ansprechpartner ab Tag eins",
		],
	},
	allInOne: {
		eyebrow: "Alles erledigt",
		title: "Montage, Mieterinfo, Abrechnung. Ein Ansprechpartner.",
		text: "Nach Ihrer Unterschrift übernimmt Heidi die Organisation. Ihr Team muss weder Termine abstimmen noch Aushänge verteilen oder Ablesewerte einsammeln.",
		cards: [
			"Zertifizierte Heidi-Monteure: 92 % der Montagen klappen beim ersten Termin, Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Heidi kündigt Termine an, hängt aus und beantwortet die Fragen der Mieter. Ihr Postfach bleibt ruhig.",
			"Ablesung per Funk, ohne dass jemand in die Wohnung muss. Die monatliche uVI nach HKVO kommt automatisch.",
			"Die Heizkostenabrechnung entsteht mit einem Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Bonn",
		title: "Von der Südstadt bis nach Beuel. In allen vier Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Bonner Bestände übernimmt.",
		legend: "Beispielobjekt Poppelsdorfer Allee 12",
	},
	billing: {
		title: "Ein Klick. Und die Abrechnung steht.",
		text: "Alle Verbrauchswerte kommen per Funk, die Kostenarten sind bereits zugeordnet. Mit einem Klick erstellt Heidi die Abrechnung für jede Einheit.",
		checks: [
			"Nach Heizkostenverordnung",
			"Plausibilitätsprüfung pro Einheit",
			"Direkt in Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Bonn",
		title: "Bonner Bestand, persönlich betreut.",
		text: "Ob Südstadt, Beuel oder Bad Godesberg: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"Erfolgsquote im ersten Anlauf",
			"Tage vorher angekündigt",
			"Zeitfenster für jede Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Monatliche Verbrauchsinfo. Automatisch für jede Mietpartei.",
			text: "Ihre Mieter sehen jeden Monat, was sie verbraucht haben, nach HKVO und im Vergleich zum Vorjahr. Für Ihr Team entsteht keine Arbeit.",
		},
		portfolio: {
			title: "Alle Objekte im Blick. Auf einer Plattform.",
			text: "Sie sehen Montagen, Ablesungen und Abrechnungen pro Liegenschaft an einem Ort, für Heidi-Funkzähler genauso wie für übernommene Bestandszähler.",
		},
	},
	trio: [
		"Die Funkwerte sind schon da. Mit einem Klick erstellt Heidi die Abrechnung jeder Einheit, rechtssicher nach HKVO.",
		"Von der Kündigung per Vollmacht bis zur fertigen Abrechnung organisiert Heidi alles, auch Montage und Mieterinfo.",
		"Jede Mietpartei hat einen persönlichen Zugang und sieht dort monatlich ihre Verbrauchsinformation, wie es die HKVO vorgibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Übernimmt Heidi unsere vorhandenen Zähler?",
			answer:
				"Ja. Ihre vorhandenen Zähler werden von Heidi ausgelesen und ausgewertet, die Abrechnung kommt von uns. Neue Geräte gibt es erst nach Ablauf Ihres alten Messdienstvertrags.",
		},
		{
			question: "Wann können wir frühestens wechseln?",
			answer:
				"Ja. Sie wechseln sofort, unabhängig von der Restlaufzeit. Die Kündigung übernehmen wir per Vollmacht.",
		},
		{
			question: "Wer kündigt die Montage bei den Mietern an?",
			answer:
				"Heidi informiert sie 14 Tage vor der Montage, nennt ein Zeitfenster von 1–2 Stunden und ist für Rückfragen direkt erreichbar.",
		},
		{
			question: "Wie entsteht die Heizkostenabrechnung?",
			answer:
				"Einen Klick: Die Verbräuche liegen per Funk vor, Heidi erstellt die Abrechnung. Sie prüfen sie und geben sie frei.",
		},
		{
			question: "Wie ist der Preis aufgebaut?",
			answer:
				'Grundlage sind die installierten Zähler und eine Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Bonner Bestand gibt es nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Ihr Messdienst in Bonn. Ab heute mit Heidi.",
		sub: "Unterschreiben, zurücklehnen. Heidi erledigt den Rest.",
	},
};

export default content;
