// Generated by scripts/extract-city.ts from the "Heidi Bremen" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/bremen/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/bremen/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./bremen-map";

const content: RegionContent = {
	slug: "bremen",
	seo: {
		title: "Messdienstanbieter Bremen: unkompliziert | Heidi Systems",
		description:
			"Messdienst in Bremen, vom Altbremer Haus im Viertel bis zur Wohnanlage in Osterholz: Heidi übernimmt Ihre vorhandenen Zähler und die Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Bremen. Ganz unkompliziert.",
	},
	links: { nearby: ["hannover", "bielefeld"] },
	name: "Bremen",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Bremer Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Bremen",
		title: "Messdienst wechseln in Bremen. Ganz unkompliziert.",
		lede: "Ob Altbremer Haus im Viertel oder Wohnanlage in Osterholz: Heidi übernimmt Ihre vorhandenen Zähler sofort und kümmert sich um Montage, Mieterinfo, Ablesung und Abrechnung.",
		checks: [
			"Bestandszähler ab Tag eins",
			"Rundum-Service",
			"Abrechnung in Sekunden",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Bremen",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Humboldtstraße 12",
		area: "Ostertor · Altbau",
		units: 14,
		secondAddress: "Waller Heerstraße 31",
		appointment: {
			day: "Mo, 12.10.",
			time: "13–15 Uhr",
		},
		avatars: ["JB", "MS", "DM"],
		tenant: "JB",
	},
	logoStrip: {
		text: "Hausverwaltungen in ganz Deutschland rechnen bereits mit Heidi ab.",
		logos: [
			"harte",
			"raumgold",
			"vitec",
			"neckar",
			"wagner",
			"berlin",
			"progera",
			"hsp",
			"schleicher",
			"dumax",
			"werne",
			"niesen",
		],
	},
	noWait: {
		eyebrow: "Wechsel jederzeit",
		title: "Nicht aufs Vertragsende warten. Heute wechseln.",
		text: "Wechseln Sie jetzt: Heidi liest die verbauten Zähler aus und rechnet ab. Heidi-Funkzähler werden erst montiert, wenn der alte Vertrag ausgelaufen ist.",
		notes: [
			"Ohne Parallelbetrieb, ohne Datenverlust",
			"Vollmacht genügt für die Kündigung",
			"Feste Ansprechperson von Beginn an",
		],
	},
	allInOne: {
		eyebrow: "Rundum-Service",
		title: "Vier Aufgaben. Ein Ansprechpartner.",
		text: "Einmal unterschrieben, organisiert Heidi Montage, Mieterinfo, Ablesung und Abrechnung. Ihr Team muss keinen Terminen, Aushängen oder Ablesewerten mehr hinterherlaufen.",
		cards: [
			"Zertifizierte Monteure von Heidi schaffen 92 % der Montagen beim ersten Termin. Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Mieterkommunikation läuft über Heidi: Aushänge, Ankündigungen, Rückfragen.",
			"Ablesung per Funk, ohne dass jemand in die Wohnung muss. Die monatliche uVI nach HKVO kommt automatisch.",
			"Heizkostenabrechnung per Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Bremen",
		title: "Von Vegesack bis in die Neustadt. In allen fünf Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Bremer Bestände übernimmt.",
		legend: "Beispielobjekt Humboldtstraße 12",
	},
	billing: {
		title: "Ein Klick. Und die Abrechnung steht.",
		text: "Alle Verbrauchswerte kommen per Funk, die Kostenarten sind bereits zugeordnet. Mit einem Klick erstellt Heidi die Abrechnung für jede Einheit.",
		checks: [
			"Konform mit HKVO",
			"Jede Wohnung auf Plausibilität geprüft",
			"Direkt übergeben an Ihre Software",
		],
	},
	service: {
		eyebrow: "Service für Bremen",
		title: "Ihre Bremer Objekte. Eine feste Ansprechperson.",
		text: "Ob Schwachhausen, Neustadt oder Vegesack: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"der Montagen klappen beim ersten Termin",
			"Tage Ankündigung vor der Montage",
			"Zeitfenster für Mieter bei der Montage",
		],
	},
	duo: {
		uvi: {
			title: "Monat für Monat: die Verbrauchsinfo für Ihre Mieter.",
			text: "Ihre Mieter sehen monatlich ihren Verbrauch nach HKVO, mit Vergleich zum Vorjahresmonat. Ihr Team muss dafür nichts tun.",
		},
		portfolio: {
			title: "Ihr Bestand. Übersichtlich auf einer Plattform.",
			text: "Eine Plattform für den ganzen Bestand: Montagen, Ablesungen und Abrechnungen jeder Liegenschaft, mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Die Funkwerte sind schon da. Mit einem Klick erstellt Heidi die Abrechnung jeder Einheit, rechtssicher nach HKVO.",
		"Heidi kümmert sich um Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung. Ihr Team hat damit nichts zu tun.",
		"Jede Mietpartei bekommt einen eigenen Zugang zur monatlichen Verbrauchsinformation, wie von der HKVO gefordert.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Nutzt Heidi unsere bisherigen Zähler weiter?",
			answer:
				"Ja. Heidi liest die vorhandenen Zähler aus, wertet die Verbräuche aus und rechnet ab. Neue Zähler kommen erst, wenn Ihr alter Messdienstvertrag endet.",
		},
		{
			question: "Geht der Wechsel auch mitten in der Vertragslaufzeit?",
			answer:
				"Nein. Heidi übernimmt ab sofort, egal wie lange der alte Vertrag noch gilt. Um die Kündigung kümmern wir uns per Vollmacht.",
		},
		{
			question: "Wer spricht mit unseren Mietern?",
			answer:
				"Wir übernehmen das: Ankündigung 14 Tage im Voraus, ein Zeitfenster von 1–2 Stunden am Montagetag und direkte Antworten auf Rückfragen.",
		},
		{
			question: "Wie kommen wir zur Heizkostenabrechnung?",
			answer:
				"Sehr schnell. Weil die Verbräuche per Funk vorliegen, erzeugt Heidi die Abrechnung mit einem Klick. Danach prüfen Sie und geben frei.",
		},
		{
			question: "Wie wird Heidi abgerechnet?",
			answer:
				'Sie zahlen nur für tatsächlich installierte Zähler plus eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein <a href="/preise">Angebot</a> für Ihren Bremer Bestand.',
		},
	],
	final: {
		title: "Jetzt in Bremen den Messdienst wechseln.",
		sub: "Einmal unterschreiben, den Rest übernimmt Heidi.",
	},
};

export default content;
