// Generated by scripts/extract-city.ts from the "Heidi Dortmund" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/dortmund/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/dortmund/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./dortmund-map";

const content: RegionContent = {
	slug: "dortmund",
	seo: {
		title: "Messdienstanbieter Dortmund ohne Zeitverlust | Heidi Systems",
		description:
			"Messdienst in Dortmund vom Kreuzviertel bis Eving: Heidi übernimmt Ihre vorhandenen Zähler sofort und erledigt Montage, Mieterinfo, Ablesung und Abrechnung.",
		ogTitle: "Messdienst wechseln in Dortmund. Ohne Zeitverlust.",
	},
	links: { nearby: ["bochum", "essen", "bielefeld"] },
	name: "Dortmund",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Dortmunder Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Dortmund",
		title: "Messdienst wechseln in Dortmund. Ohne Zeitverlust.",
		lede: "Vom Kreuzviertel bis zur Zechensiedlung in Eving: Heidi übernimmt Ihre vorhandenen Zähler sofort und erledigt Montage, Mieterinfo, Ablesung und die Heizkostenabrechnung.",
		checks: [
			"Bestandszähler sofort nutzbar",
			"Rundum-Service",
			"Abrechnung in Sekunden",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Dortmund",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Kreuzstraße 12",
		area: "Kreuzviertel · Altbau",
		units: 12,
		secondAddress: "Münsterstraße 31",
		appointment: {
			day: "Mo, 05.10.",
			time: "10–12 Uhr",
		},
		avatars: ["JB", "RS", "HV"],
		tenant: "JB",
	},
	logoStrip: {
		text: "Hausverwaltungen von Nord bis Süd setzen auf Heidi.",
		logos: [
			"vitec",
			"raumgold",
			"niesen",
			"wagner",
			"dumax",
			"neckar",
			"harte",
			"berlin",
			"hsp",
			"schleicher",
			"werne",
			"progera",
		],
	},
	noWait: {
		eyebrow: "Heute wechseln",
		title: "Nicht aufs Vertragsende warten. Heute wechseln.",
		text: "Wechseln Sie jetzt: Heidi liest die verbauten Zähler aus und rechnet ab. Heidi-Funkzähler werden erst montiert, wenn der alte Vertrag ausgelaufen ist.",
		notes: [
			"Ohne Parallelbetrieb, ohne Datenverlust",
			"Kündigung erledigt Heidi per Vollmacht",
			"Ein Ansprechpartner von Anfang an",
		],
	},
	allInOne: {
		eyebrow: "Komplett betreut",
		title: "Alles organisiert. Von der ersten Montage an.",
		text: "Einmal unterschrieben, organisiert Heidi Montage, Mieterinfo, Ablesung und Abrechnung. Ihr Team muss keinen Terminen, Aushängen oder Ablesewerten mehr hinterherlaufen.",
		cards: [
			"92 % der Montagen gelingen beim ersten Termin. Zertifizierte Monteure, Zeitfenster von 1–2 h für Ihre Mieter.",
			"Heidi kündigt Termine an, hängt aus und beantwortet die Fragen der Mieter. Ihr Postfach bleibt ruhig.",
			"Ablesung per Funk, ohne dass jemand in die Wohnung muss. Die monatliche uVI nach HKVO kommt automatisch.",
			"Rechtssicher abgerechnet auf Knopfdruck und direkt an Ihr ERP- oder CRM-System übergeben.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Dortmund",
		title: "Von Mengede bis Aplerbeck. In allen zwölf Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Dortmunder Bestände übernimmt.",
		legend: "Beispielobjekt Kreuzstraße 12",
	},
	billing: {
		title: "Abrechnen mit einem Klick.",
		text: "Die Verbräuche sind per Funk erfasst, die Kostenarten zugeordnet. Mit einem Klick entstehen die Abrechnungen für alle Einheiten.",
		checks: [
			"Nach HKVO rechtssicher",
			"Jede Einheit auf Plausibilität geprüft",
			"Übergabe an Ihr ERP",
		],
	},
	service: {
		eyebrow: "Service für Dortmund",
		title: "Ein fester Ansprechpartner für Ihren Dortmunder Bestand.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Kreuzviertel, Hörde oder Eving. Montage, Ablesung und Abrechnung folgen in Dortmund demselben bewährten Ablauf.",
		kpis: [
			"Erfolg beim ersten Termin",
			"Tage vorher angekündigt",
			"Zeitfenster für jede Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Verbrauchsinformation für Mieter. Monat für Monat automatisch.",
			text: "Verbrauch nach HKVO, jeden Monat, mit Vergleich zum Vorjahr. So informiert Heidi Ihre Mieter, ohne Aufwand für Ihr Team.",
		},
		portfolio: {
			title: "Ein Portal für alle Liegenschaften.",
			text: "Montagen, Ablesungen und Abrechnungen aller Liegenschaften auf einen Blick, mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Heidi nutzt die per Funk erfassten Werte und erstellt per Klick die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Heidi kümmert sich um Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung. Ihr Team hat damit nichts zu tun.",
		"Monatlich und mit eigenem Zugang: So sieht jede Mietpartei ihre Verbrauchsinformation nach HKVO.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Nutzt Heidi unsere bisherigen Zähler weiter?",
			answer:
				"Ja, Heidi arbeitet mit den Zählern, die bereits verbaut sind: auslesen, auswerten, abrechnen. Der Austausch folgt erst zum Vertragsende beim bisherigen Anbieter.",
		},
		{
			question: "Wann können wir frühestens wechseln?",
			answer:
				"Nein. Der Wechsel ist sofort möglich, auch bei langer Restlaufzeit. Die Kündigung beim bisherigen Messdienst übernehmen wir mit Ihrer Vollmacht.",
		},
		{
			question: "Wer kümmert sich um die Mieterkommunikation?",
			answer:
				"Wir übernehmen das: Ankündigung 14 Tage im Voraus, ein Zeitfenster von 1–2 Stunden am Montagetag und direkte Antworten auf Rückfragen.",
		},
		{
			question: "Wie kommen wir zur Heizkostenabrechnung?",
			answer:
				"Ohne Wartezeit auf Ablesungen. Heidi hat die Funkwerte bereits und erstellt die Abrechnung auf Knopfdruck, Sie geben sie nach Prüfung frei.",
		},
		{
			question: "Was zahlen wir für Heidi?",
			answer:
				'Abgerechnet wird pro tatsächlich installiertem Zähler, dazu eine Abrechnungspauschale. Ihr konkretes <a href="/preise">Angebot</a> für den Dortmunder Bestand bekommen Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Dortmund. Heute.",
		sub: "Sie unterschreiben, Heidi übernimmt.",
	},
};

export default content;
