// Generated by scripts/extract-city.ts from the "Heidi Dresden" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/dresden/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/dresden/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./dresden-map";

const content: RegionContent = {
	slug: "dresden",
	seo: {
		title: "Messdienstanbieter Dresden ohne Verzögerung | Heidi Systems",
		description:
			"Messdienst für Hausverwaltungen in Dresden: ob Gründerzeit in der Neustadt oder Plattenbau in Gorbitz, Heidi übernimmt Ihre Zähler sofort und rechnet ab.",
		ogTitle: "Messdienst wechseln in Dresden. Ohne Verzögerung.",
	},
	links: { nearby: ["leipzig", "berlin"] },
	name: "Dresden",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Dresdner Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Dresden",
		title: "Messdienst wechseln in Dresden. Ohne Verzögerung.",
		lede: "Ob Gründerzeit in der Neustadt oder Plattenbau in Gorbitz: Heidi übernimmt Ihre vorhandenen Zähler sofort und erledigt Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bestandszähler ab Tag eins",
			"Alles bei Heidi",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Dresden",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Alaunstraße 12",
		area: "Äußere Neustadt · Altbau",
		units: 18,
		secondAddress: "Bodenbacher Straße 31",
		appointment: {
			day: "Mi, 11.11.",
			time: "7–9 Uhr",
		},
		avatars: ["OP", "RS", "EK"],
		tenant: "OP",
	},
	logoStrip: {
		text: "Bundesweit rechnen Hausverwaltungen schon mit Heidi ab.",
		logos: [
			"berlin",
			"niesen",
			"dumax",
			"neckar",
			"schleicher",
			"progera",
			"wagner",
			"raumgold",
			"vitec",
			"hsp",
			"harte",
			"werne",
		],
	},
	noWait: {
		eyebrow: "Sofort wechseln",
		title: "Ihr alter Vertrag läuft noch Jahre? Starten Sie jetzt.",
		text: "Heidi rechnet ab sofort mit Ihren vorhandenen Zählern ab, egal wie lange der alte Vertrag noch gilt. Erst zum Vertragsende tauschen wir auf Heidi-Funkzähler.",
		notes: [
			"Ohne Doppelbetrieb, ohne Datenverlust",
			"Kündigung durch Heidi per Vollmacht",
			"Ein Ansprechpartner ab Start",
		],
	},
	allInOne: {
		eyebrow: "Ohne Koordinationsaufwand",
		title: "Alles organisiert. Von der ersten Montage an.",
		text: "Eine Unterschrift reicht. Danach koordiniert Heidi Termine, Aushänge und Ablesewerte, Ihr Team muss nichts nachhalten.",
		cards: [
			"Zertifizierte Heidi-Monteure. 92 % der Montagen gelingen beim ersten Termin, Ihre Mieter haben ein Zeitfenster von 1–2 h.",
			"Heidi übernimmt Aushänge, Terminankündigungen und Rückfragen. Ihr Team wird damit nicht belastet.",
			"Per Funk abgelesen, ohne dass jemand klingeln muss. Die uVI nach HKVO kommt monatlich und automatisch.",
			"Heizkostenabrechnung per Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Dresden",
		title: "Von der Neustadt bis nach Prohlis. In allen zehn Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Dresdner Bestände übernimmt.",
		legend: "Beispielobjekt Alaunstraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung in Sekunden.",
		text: "Alle Verbrauchswerte kommen per Funk, die Kostenarten sind bereits zugeordnet. Mit einem Klick erstellt Heidi die Abrechnung für jede Einheit.",
		checks: [
			"Konform mit HKVO",
			"Automatische Plausibilitätsprüfung",
			"Export in Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Dresden",
		title: "Ein fester Ansprechpartner für Ihren Dresdner Bestand.",
		text: "Ob Neustadt, Striesen oder Löbtau: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"Montagen im ersten Anlauf erledigt",
			"Tage Vorlauf für die Mieterinformation",
			"Zeitfenster für die Mieter",
		],
	},
	duo: {
		uvi: {
			title: "Monatliche Verbrauchsinfo. Automatisch für jede Mietpartei.",
			text: "Heidi stellt jeder Mietpartei monatlich ihren Verbrauch bereit, nach HKVO und mit Vorjahresvergleich. Ihr Team ist nicht beteiligt.",
		},
		portfolio: {
			title: "Jede Liegenschaft im Blick. Auf einer Plattform.",
			text: "Ob Montage, Ablesung oder Abrechnung: Sie sehen jede Liegenschaft an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Per Funk liegen alle Verbräuche vor. Mit einem Klick erstellt Heidi die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Heidi erledigt Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung. Für Ihr Team bleibt nichts zu koordinieren.",
		"Mit einem eigenen Zugang sieht jede Mietpartei jeden Monat ihre Verbrauchsinformation, genau wie es die HKVO verlangt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Können unsere bisherigen Zähler weiter genutzt werden?",
			answer:
				"Ja. Heidi liest die vorhandenen Zähler aus, wertet die Verbräuche aus und erstellt die Abrechnung. Ausgetauscht wird erst, wenn Ihr Vertrag mit dem bisherigen Messdienst ausläuft.",
		},
		{
			question: "Geht der Wechsel auch mitten in der Vertragslaufzeit?",
			answer:
				"Ja, sofort und unabhängig von der Restlaufzeit. Mit Ihrer Vollmacht kündigen wir beim bisherigen Messdienst.",
		},
		{
			question: "Wie läuft die Kommunikation mit den Mietern?",
			answer:
				"Heidi. Wir kündigen die Montage 14 Tage vorher an, nennen den Mietern ein Zeitfenster von 1–2 Stunden und sind ihr Ansprechpartner bei Fragen.",
		},
		{
			question: "Wie schnell rechnet Heidi ab?",
			answer:
				"Auf Knopfdruck: Die Verbräuche sind per Funk erfasst, Heidi erstellt die Abrechnung, Sie prüfen das Ergebnis und geben es frei.",
		},
		{
			question: "Welche Kosten entstehen mit Heidi?",
			answer:
				'Abgerechnet wird pro tatsächlich installiertem Zähler, dazu eine Abrechnungspauschale. Ihr konkretes <a href="/preise">Angebot</a> für den Dresdner Bestand bekommen Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Dresden. Heute.",
		sub: "Unterschrift genügt. Alles Weitere macht Heidi.",
	},
};

export default content;
