// Generated by scripts/extract-city.ts from the "Heidi Düsseldorf" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/duesseldorf/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/duesseldorf/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./duesseldorf-map";

const content: RegionContent = {
	slug: "duesseldorf",
	seo: {
		title: "Messdienstanbieter in Düsseldorf wechseln | Heidi Systems",
		description:
			"Messdienst für Düsseldorfer Hausverwaltungen: Heidi übernimmt Ihre Zähler von Pempelfort bis Garath ohne Stillstand und rechnet Heizkosten auf Knopfdruck ab.",
		ogTitle: "Messdienst wechseln in Düsseldorf. Ohne Stillstand.",
	},
	links: { nearby: ["koeln", "duisburg", "moenchengladbach", "wuppertal"] },
	name: "Düsseldorf",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Düsseldorfer Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Düsseldorf",
		title: "Messdienst wechseln in Düsseldorf. Ohne Stillstand.",
		lede: "Ob Altbau in Pempelfort oder Wohnanlage in Garath: Heidi übernimmt Ihre vorhandenen Zähler sofort und kümmert sich um Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bestehende Zähler bleiben",
			"Ein Partner für den ganzen Ablauf",
			"Ein Klick zur Abrechnung",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Düsseldorf",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Lindemannstraße 12",
		area: "Düsseltal · Altbau",
		units: 36,
		secondAddress: "Lorettostraße 31",
		appointment: {
			day: "Mo, 02.11.",
			time: "9–11 Uhr",
		},
		avatars: ["JB", "AK", "HV"],
		tenant: "JB",
	},
	logoStrip: {
		text: "Hausverwaltungen in ganz Deutschland rechnen bereits mit Heidi ab.",
		logos: [
			"hsp",
			"vitec",
			"harte",
			"schleicher",
			"raumgold",
			"progera",
			"dumax",
			"neckar",
			"berlin",
			"wagner",
			"niesen",
			"werne",
		],
	},
	noWait: {
		eyebrow: "Jetzt umsteigen",
		title: "Messdienstvertrag läuft noch? Wechseln Sie trotzdem jetzt.",
		text: "Sie müssen nicht bis zum Vertragsende warten. Heidi liest Ihre vorhandenen Zähler ab sofort aus und rechnet ab. Die Funkzähler von Heidi kommen erst, wenn der alte Vertrag ausgelaufen ist.",
		notes: [
			"Ohne Parallelbetrieb, ohne Datenverlust",
			"Kündigung per Vollmacht übernommen",
			"Persönlicher Ansprechpartner ab Tag eins",
		],
	},
	allInOne: {
		eyebrow: "Komplettservice",
		title: "Montage, Mieter, Abrechnung. Alles bei Heidi.",
		text: "Eine Unterschrift reicht. Danach koordiniert Heidi Termine, Aushänge und Ablesewerte, Ihr Team muss nichts nachhalten.",
		cards: [
			"Zertifizierte Heidi-Monteure: 92 % der Montagen klappen beim ersten Termin, Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Heidi informiert Ihre Mieter per Aushang und Ankündigung und beantwortet ihre Fragen direkt.",
			"Fernablesung per Funk ohne Wohnungstermin, dazu die monatliche Verbrauchsinformation nach HKVO.",
			"Heizkostenabrechnung mit einem Klick, rechtssicher und automatisch an Ihr ERP- oder CRM-System übergeben.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Düsseldorf",
		title: "Von Kaiserswerth bis Garath. In allen zehn Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Düsseldorfer Bestände übernimmt.",
		legend: "Beispielobjekt Lindemannstraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Mit einem Klick erledigt.",
		text: "Weil Verbräuche per Funk vorliegen und Kostenarten zugeordnet sind, reicht ein Klick für die Abrechnung jeder Einheit.",
		checks: [
			"Konform mit HKVO",
			"Jede Einheit auf Plausibilität geprüft",
			"Direkt übergeben an Ihre Software",
		],
	},
	service: {
		eyebrow: "Service für Düsseldorf",
		title: "Ein fester Ansprechpartner für Ihren Düsseldorfer Bestand.",
		text: "Ob Pempelfort, Bilk oder Benrath: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"Montagen im ersten Anlauf erledigt",
			"Tage Vorlauf, bevor montiert wird",
			"Zeitfenster am Montagetag",
		],
	},
	duo: {
		uvi: {
			title: "Monat für Monat: die Verbrauchsinfo für Ihre Mieter.",
			text: "Monat für Monat sieht jede Mietpartei ihren Verbrauch nach HKVO, mit Vorjahresvergleich. Ihr Team hat keine Arbeit damit.",
		},
		portfolio: {
			title: "Ein Portal für alle Liegenschaften.",
			text: "Pro Liegenschaft sehen Sie Montagen, Ablesungen und Abrechnungen an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Die Funkwerte sind schon da. Mit einem Klick erstellt Heidi die Abrechnung jeder Einheit, rechtssicher nach HKVO.",
		"Heidi kümmert sich um Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung. Ihr Team hat damit nichts zu tun.",
		"Monatlich und mit eigenem Zugang: So sieht jede Mietpartei ihre Verbrauchsinformation nach HKVO.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Müssen wir sofort neue Zähler einbauen?",
			answer:
				"Ja. Die verbauten Zähler bleiben zunächst, Heidi liest sie aus und erstellt daraus die Abrechnung. Erst zum Ende des alten Vertrags tauschen wir.",
		},
		{
			question: "Wann können wir frühestens wechseln?",
			answer:
				"Nein. Heidi startet direkt, die Restlaufzeit spielt keine Rolle. Gekündigt wird per Vollmacht durch uns.",
		},
		{
			question: "Wie läuft die Kommunikation mit den Mietern?",
			answer:
				"Heidi. Wir kündigen jede Montage 14 Tage vorher an, geben ein Zeitfenster von 1–2 Stunden vor und beantworten die Fragen der Mieter.",
		},
		{
			question: "Wann liegt die Heizkostenabrechnung vor?",
			answer:
				"Mit einem Klick. Die Funkwerte sind schon da, Heidi rechnet ab, und Sie geben das geprüfte Ergebnis frei.",
		},
		{
			question: "Wie ist der Preis aufgebaut?",
			answer:
				'Abgerechnet wird pro tatsächlich installiertem Zähler, dazu eine Abrechnungspauschale. Ihr konkretes <a href="/preise">Angebot</a> für den Düsseldorfer Bestand bekommen Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Düsseldorf. Heute.",
		sub: "Unterschreiben, zurücklehnen. Heidi erledigt den Rest.",
	},
};

export default content;
