// Generated by scripts/extract-city.ts from the "Heidi Duisburg" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/duisburg/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/duisburg/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./duisburg-map";

const content: RegionContent = {
	slug: "duisburg",
	seo: {
		title: "Messdienstanbieter Duisburg: sofort starten | Heidi Systems",
		description:
			"Messdienst für Duisburger Hausverwaltungen: vom Dellviertel bis Walsum übernimmt Heidi Ihre bestehenden Zähler sofort und erstellt die Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Duisburg. Einfach und sofort.",
	},
	links: { nearby: ["essen", "duesseldorf", "moenchengladbach"] },
	name: "Duisburg",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Duisburger Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Duisburg",
		title: "Messdienst wechseln in Duisburg. Einfach und sofort.",
		lede: "Vom Dellviertel bis zur Zechensiedlung in Walsum: Heidi übernimmt Ihre bestehenden Zähler sofort und erledigt Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bestandszähler ab Tag eins",
			"Ein Ansprechpartner für alles",
			"Heizkostenabrechnung per Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Duisburg",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Düsseldorfer Straße 12",
		area: "Dellviertel · Altbau",
		units: 12,
		secondAddress: "Weseler Straße 31",
		appointment: {
			day: "Mo, 09.11.",
			time: "7–9 Uhr",
		},
		avatars: ["EK", "JB", "NB"],
		tenant: "EK",
	},
	logoStrip: {
		text: "Verwaltungen aus ganz Deutschland vertrauen bei der Abrechnung auf Heidi.",
		logos: [
			"werne",
			"progera",
			"schleicher",
			"hsp",
			"harte",
			"wagner",
			"dumax",
			"vitec",
			"niesen",
			"berlin",
			"raumgold",
			"neckar",
		],
	},
	noWait: {
		eyebrow: "Jetzt umsteigen",
		title: "Altvertrag noch nicht abgelaufen? Kein Problem.",
		text: "Auch während der Restlaufzeit liest Heidi Ihre vorhandenen Zähler aus und erstellt die Abrechnung. Erst wenn der alte Vertrag ausläuft, tauschen wir auf Heidi-Funkzähler.",
		notes: [
			"Ohne Doppelbetrieb, ohne Datenverlust",
			"Kündigung per Vollmacht inklusive",
			"Von Anfang an ein fester Kontakt",
		],
	},
	allInOne: {
		eyebrow: "Rundum-Service",
		title: "Sie unterschreiben. Heidi macht den Rest.",
		text: "Eine Unterschrift reicht. Danach koordiniert Heidi Termine, Aushänge und Ablesewerte, Ihr Team muss nichts nachhalten.",
		cards: [
			"Zertifizierte Heidi-Monteure. 92 % der Montagen gelingen beim ersten Termin, Ihre Mieter haben ein Zeitfenster von 1–2 h.",
			"Heidi informiert Ihre Mieter per Aushang und Ankündigung und beantwortet ihre Fragen direkt.",
			"Kein Ablesetermin in der Wohnung: Heidi liest per Funk ab und verschickt monatlich die uVI nach HKVO.",
			"Die Heizkostenabrechnung entsteht mit einem Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Duisburg",
		title: "Von Walsum bis in den Süden. In allen sieben Bezirken.",
		sub: "Fahren Sie über einen Bezirk und sehen Sie, wie Heidi typische Duisburger Bestände übernimmt.",
		legend: "Beispielobjekt Düsseldorfer Straße 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Mit einem Klick erledigt.",
		text: "Funkwerte da, Kostenarten zugeordnet: Ein Klick, und Heidi erstellt jede Einzelabrechnung.",
		checks: [
			"Konform mit HKVO",
			"Plausibilitätscheck pro Einheit",
			"Anbindung an Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Duisburg",
		title: "Ein fester Ansprechpartner für Ihren Duisburger Bestand.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Neudorf, Hamborn oder Rheinhausen. Montage, Ablesung und Abrechnung folgen in Duisburg demselben bewährten Ablauf.",
		kpis: [
			"beim ersten Termin montiert",
			"Tage Vorankündigung für Ihre Mieter",
			"Zeitfenster pro Wohnung am Montagetag",
		],
	},
	duo: {
		uvi: {
			title: "Jeden Monat die Verbrauchsinformation. Ohne Aufwand.",
			text: "Monat für Monat sieht jede Mietpartei ihren Verbrauch nach HKVO, mit Vorjahresvergleich. Ihr Team hat keine Arbeit damit.",
		},
		portfolio: {
			title: "Ihr gesamter Bestand. Auf einer Plattform.",
			text: "Montagen, Ablesungen, Abrechnungen. Für jede Liegenschaft auf einer Plattform, egal ob Heidi-Funkzähler oder übernommene Bestandszähler.",
		},
	},
	trio: [
		"Die Funkwerte sind schon da. Mit einem Klick erstellt Heidi die Abrechnung jeder Einheit, rechtssicher nach HKVO.",
		"Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung übernimmt Heidi. Ihr Team muss nichts abstimmen.",
		"Jede Mietpartei erhält einen persönlichen Zugang und sieht ihre monatliche Verbrauchsinformation, so wie es die HKVO vorschreibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Übernehmen Sie unsere bisherigen Zähler?",
			answer:
				"Ja. Heidi liest die vorhandenen Zähler aus, wertet die Verbräuche aus und rechnet ab. Neue Zähler kommen erst, wenn Ihr alter Messdienstvertrag endet.",
		},
		{
			question: "Wann können wir frühestens wechseln?",
			answer:
				"Nein. Der Wechsel ist sofort möglich, auch bei langer Restlaufzeit. Die Kündigung beim bisherigen Messdienst übernehmen wir mit Ihrer Vollmacht.",
		},
		{
			question: "Wie werden unsere Mieter eingebunden?",
			answer:
				"Heidi. Wir kündigen die Montage 14 Tage vorher an, nennen den Mietern ein Zeitfenster von 1–2 Stunden und sind ihr Ansprechpartner bei Fragen.",
		},
		{
			question: "Wie lange dauert die Heizkostenabrechnung?",
			answer:
				"Mit einem Klick. Die Funkwerte sind schon da, Heidi rechnet ab, und Sie geben das geprüfte Ergebnis frei.",
		},
		{
			question: "Welche Kosten entstehen mit Heidi?",
			answer:
				'Abgerechnet wird pro tatsächlich installiertem Zähler, dazu eine Abrechnungspauschale. Ihr konkretes <a href="/preise">Angebot</a> für den Duisburger Bestand bekommen Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Duisburg. Heute.",
		sub: "Sie unterschreiben einmal. Heidi kümmert sich um alles Weitere.",
	},
};

export default content;
