// Generated by scripts/extract-city.ts from the "Heidi Essen" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/essen/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/essen/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./essen-map";

const content: RegionContent = {
	slug: "essen",
	seo: {
		title: "Messdienstanbieter Essen ohne Stress | Heidi Systems",
		description:
			"Messdienst in Essen von Rüttenscheid bis Katernberg: Heidi nutzt Ihre bestehenden Zähler sofort weiter und übernimmt Montage, Ablesung, uVI und Abrechnung.",
		ogTitle: "Messdienst wechseln in Essen. Ohne Stress.",
	},
	links: { nearby: ["bochum", "duisburg", "dortmund"] },
	name: "Essen",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Essener Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Essen",
		title: "Messdienst wechseln in Essen. Ohne Stress.",
		lede: "Von Rüttenscheid bis zur Zechensiedlung in Katernberg: Heidi nutzt Ihre bestehenden Zähler sofort weiter und übernimmt Montage, Mieterkommunikation, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Vorhandene Zähler weiter nutzen",
			"Alles bei Heidi",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Essen",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Isenbergstraße 12",
		area: "Rüttenscheid · Altbau",
		units: 36,
		secondAddress: "Altenessener Straße 31",
		appointment: {
			day: "Mo, 30.11.",
			time: "8–10 Uhr",
		},
		avatars: ["NB", "HV", "DM"],
		tenant: "NB",
	},
	logoStrip: {
		text: "Verwaltungen aus ganz Deutschland vertrauen bei der Abrechnung auf Heidi.",
		logos: [
			"schleicher",
			"progera",
			"hsp",
			"werne",
			"vitec",
			"wagner",
			"dumax",
			"berlin",
			"harte",
			"raumgold",
			"niesen",
			"neckar",
		],
	},
	noWait: {
		eyebrow: "Sofort wechseln",
		title: "Altvertrag noch nicht abgelaufen? Kein Problem.",
		text: "Heidi rechnet ab sofort mit Ihren vorhandenen Zählern ab, egal wie lange der alte Vertrag noch gilt. Erst zum Vertragsende tauschen wir auf Heidi-Funkzähler.",
		notes: [
			"Kein Parallelbetrieb nötig",
			"Heidi kündigt per Vollmacht",
			"Von Anfang an ein fester Kontakt",
		],
	},
	allInOne: {
		eyebrow: "Ohne Koordinationsaufwand",
		title: "Alles organisiert. Von der ersten Montage an.",
		text: "Von der ersten Montage bis zur fertigen Abrechnung organisiert Heidi alles. Ihr Team spart sich Terminabsprachen, Aushänge und das Einsammeln von Ablesewerten.",
		cards: [
			"Zertifizierte Heidi-Monteure: 92 % der Montagen klappen beim ersten Termin, Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Ankündigungen, Aushänge und Mieterfragen übernimmt Heidi. Ihr Postfach bleibt frei.",
			"Fernablesung per Funk ohne Wohnungstermin, dazu die monatliche Verbrauchsinformation nach HKVO.",
			"Die rechtssichere Heizkostenabrechnung entsteht per Klick und landet direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Essen",
		title: "Vom Essener Norden bis an die Ruhr. In allen neun Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Essener Bestände übernimmt.",
		legend: "Beispielobjekt Isenbergstraße 12",
	},
	billing: {
		title: "Ein Klick. Alle Abrechnungen fertig.",
		text: "Alles ist vorbereitet: Funkwerte erfasst, Kostenarten zugeordnet. Sie klicken, Heidi erstellt die Abrechnungen.",
		checks: [
			"Heizkostenverordnung eingehalten",
			"Automatische Plausibilitätsprüfung",
			"Schnittstelle zu Ihrer Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Essen",
		title: "Essener Bestand, persönlich betreut.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Rüttenscheid, Steele oder Borbeck. Montage, Ablesung und Abrechnung folgen in Essen demselben bewährten Ablauf.",
		kpis: [
			"der Montagen gelingen im ersten Termin",
			"Tage vorher angekündigt",
			"Zeitfenster für jede Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "uVI für Ihre Mieter. Monatlich und automatisch.",
			text: "Monat für Monat sieht jede Mietpartei ihren Verbrauch nach HKVO, mit Vorjahresvergleich. Ihr Team hat keine Arbeit damit.",
		},
		portfolio: {
			title: "Alle Liegenschaften. Eine Plattform.",
			text: "Pro Liegenschaft sehen Sie Montagen, Ablesungen und Abrechnungen an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Alle Verbrauchswerte sind per Funk erfasst. Mit einem Klick entsteht die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Heidi erledigt Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung. Für Ihr Team bleibt nichts zu koordinieren.",
		"Jede Mietpartei hat ihren eigenen Zugang und findet dort jeden Monat ihre Verbrauchsinformation, wie es die HKVO verlangt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Können vorhandene Zähler bleiben?",
			answer:
				"Sie bleiben. Heidi liest sie aus, wertet die Verbräuche aus und erstellt die Abrechnung. Getauscht wird erst, wenn Ihr Vertrag mit dem bisherigen Messdienst endet.",
		},
		{
			question: "Wechsel trotz laufendem Vertrag möglich?",
			answer:
				"Ja. Sie wechseln sofort, unabhängig von der Restlaufzeit. Die Kündigung übernehmen wir per Vollmacht.",
		},
		{
			question: "Wer spricht mit unseren Mietern?",
			answer:
				"Das machen wir. 14 Tage vor der Montage geht die Ankündigung raus, mit Zeitfenster von 1–2 Stunden. Rückfragen beantwortet Heidi selbst.",
		},
		{
			question: "Wie entsteht die Heizkostenabrechnung?",
			answer:
				"Einen Klick: Die Verbräuche liegen per Funk vor, Heidi erstellt die Abrechnung. Sie prüfen sie und geben sie frei.",
		},
		{
			question: "Was zahlen wir für Heidi?",
			answer:
				'Grundlage sind die installierten Zähler und eine Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Essener Bestand gibt es nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Ihr Messdienst in Essen. Ab heute mit Heidi.",
		sub: "Sie unterschreiben, Heidi übernimmt.",
	},
};

export default content;
