// Generated by scripts/extract-city.ts from the "Heidi Frankfurt" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/frankfurt/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/frankfurt/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./frankfurt-map";

const content: RegionContent = {
	slug: "frankfurt",
	seo: {
		title: "Messdienstanbieter Frankfurt: ganz einfach | Heidi Systems",
		description:
			"Messdienst in Frankfurt vom Nordend bis zur Nordweststadt: Heidi übernimmt Ihre vorhandenen Zähler sofort und organisiert Montage, Ablesung und Abrechnung.",
		ogTitle: "Messdienst wechseln in Frankfurt. Ganz einfach.",
	},
	links: { nearby: ["wiesbaden", "mannheim"] },
	name: "Frankfurt",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Frankfurter Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Frankfurt",
		title: "Messdienst wechseln in Frankfurt. Ganz einfach.",
		lede: "Vom Altbau im Nordend bis zur Wohnanlage in der Nordweststadt: Heidi übernimmt Ihre vorhandenen Zähler sofort und organisiert Montage, Mieterinfo, Ablesung und Heizkostenabrechnung für Sie.",
		checks: [
			"Vorhandene Zähler bleiben",
			"Ein Partner, alle Aufgaben",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Frankfurter Altbau-Mehrfamilienhaus",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Oeder Weg 12",
		area: "Nordend · Altbau",
		units: 24,
		secondAddress: "Berger Str. 31",
		appointment: {
			day: "Di, 14.10.",
			time: "8–10 Uhr",
		},
		avatars: ["AK", "MS", "JB"],
		tenant: "AK",
	},
	logoStrip: {
		text: "Verwaltungen in ganz Deutschland setzen bei der Abrechnung auf Heidi.",
		logos: [
			"werne",
			"hsp",
			"schleicher",
			"progera",
			"vitec",
			"neckar",
			"dumax",
			"raumgold",
			"berlin",
			"harte",
			"niesen",
			"wagner",
		],
	},
	noWait: {
		eyebrow: "Wechsel jederzeit",
		title: "Langer Restvertrag? Kein Grund zu warten.",
		text: "Heidi startet mit Ihren vorhandenen Zählern: Auslesen und Abrechnen läuft ab sofort über uns, auch wenn der Vertrag mit dem bisherigen Messdienst noch Jahre gilt. Die Geräte tauschen wir erst zum Vertragsende.",
		notes: [
			"Ohne Parallelbetrieb, ohne Datenverlust",
			"Kündigung per Vollmacht inklusive",
			"Eine Ansprechperson für alles",
		],
	},
	allInOne: {
		eyebrow: "Voller Service",
		title: "Vier Aufgaben. Ein Ansprechpartner.",
		text: "Einmal unterschrieben, organisiert Heidi Montage, Mieterinfo, Ablesung und Abrechnung. Ihr Team muss keinen Terminen, Aushängen oder Ablesewerten mehr hinterherlaufen.",
		cards: [
			"92 % der Montagen gelingen beim ersten Termin. Zertifizierte Monteure, Zeitfenster von 1–2 h für Ihre Mieter.",
			"Heidi informiert Ihre Mieter per Aushang und Ankündigung und beantwortet ihre Fragen direkt.",
			"Ablesung per Funk, ohne dass jemand in die Wohnung muss. Die monatliche uVI nach HKVO kommt automatisch.",
			"Die Heizkostenabrechnung entsteht mit einem Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Frankfurt",
		title: "Von Höchst bis Bergen-Enkheim. In allen 16 Ortsbezirken.",
		sub: "Fahren Sie über einen Ortsbezirk und sehen Sie, wie Heidi typische Frankfurter Bestände übernimmt.",
		legend: "Beispielobjekt Oeder Weg 12",
	},
	billing: {
		title: "Heizkostenabrechnung in Sekunden.",
		text: "Verbräuche per Funk, Kostenarten zugeordnet, Verteilerschlüssel hinterlegt. Sie klicken, Heidi rechnet jede Einheit ab.",
		checks: [
			"Nach Heizkostenverordnung",
			"Automatische Plausibilitätsprüfung",
			"Export in Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Frankfurt",
		title: "Ihr Frankfurter Bestand. Eine feste Ansprechperson.",
		text: "Ob Nordend, Sachsenhausen oder Höchst: Ihre Verwaltung hat eine feste Ansprechperson, die Ihre Objekte kennt. Montage, Ablesung und Abrechnung folgen einem klaren Ablauf.",
		kpis: [
			"Montagen im ersten Anlauf erledigt",
			"Tage Vorlauf, bevor montiert wird",
			"Zeitfenster für Ihre Mieter",
		],
	},
	duo: {
		uvi: {
			title: "Monat für Monat: die Verbrauchsinfo für Ihre Mieter.",
			text: "Heidi stellt jeder Mietpartei monatlich ihren Verbrauch bereit, nach HKVO und mit Vorjahresvergleich. Ihr Team ist nicht beteiligt.",
		},
		portfolio: {
			title: "Ihr Portfolio. Übersichtlich an einem Ort.",
			text: "Jede Liegenschaft mit Montagen, Ablesungen und Abrechnungen auf einer Plattform, ob mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Da alle Werte per Funk vorliegen, reicht ein Klick: Heidi erstellt die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Vom Kündigen per Vollmacht über die Montage bis zur Abrechnung kümmert sich Heidi. Ihr Team koordiniert nichts.",
		"Mit einem eigenen Zugang sieht jede Mietpartei jeden Monat ihre Verbrauchsinformation, genau wie es die HKVO verlangt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Was passiert mit unseren vorhandenen Zählern?",
			answer:
				"Sie bleiben. Heidi liest sie aus, wertet die Verbräuche aus und erstellt die Abrechnung. Getauscht wird erst, wenn Ihr Vertrag mit dem bisherigen Messdienst endet.",
		},
		{
			question: "Geht der Wechsel auch mitten in der Vertragslaufzeit?",
			answer:
				"Ja. Sie wechseln sofort, ganz gleich, wie lange der Vertrag noch läuft. Mit Ihrer Vollmacht kündigen wir für Sie.",
		},
		{
			question: "Wie werden unsere Mieter eingebunden?",
			answer:
				"Heidi informiert sie 14 Tage vor der Montage, nennt ein Zeitfenster von 1–2 Stunden und ist für Rückfragen direkt erreichbar.",
		},
		{
			question: "Wie entsteht die Heizkostenabrechnung?",
			answer:
				"Auf Knopfdruck: Die Verbräuche sind per Funk erfasst, Heidi erstellt die Abrechnung, Sie prüfen das Ergebnis und geben es frei.",
		},
		{
			question: "Wie berechnet Heidi die Kosten?",
			answer:
				'Pro tatsächlich installiertem Zähler, dazu eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein konkretes <a href="/preise">Angebot</a> für Ihren Frankfurter Bestand.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Frankfurt. Heute.",
		sub: "Sie unterschreiben, Heidi übernimmt.",
	},
};

export default content;
