// Generated by scripts/extract-city.ts from the "Heidi Hamburg" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/hamburg/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/hamburg/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./hamburg-map";

const content: RegionContent = {
	slug: "hamburg",
	seo: {
		title: "Messdienstanbieter Hamburg: ohne Umwege | Heidi Systems",
		description:
			"Messdienst in Hamburg, vom Altbau in Harvestehude bis zur Siedlung in Wandsbek: Heidi übernimmt Ihre vorhandenen Zähler und erstellt die Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Hamburg. Ohne Umwege.",
	},
	links: { nearby: ["bremen", "hannover"] },
	name: "Hamburg",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Hamburger Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Hamburg",
		title: "Messdienst wechseln in Hamburg. Ohne Umwege.",
		lede: "Heidi nutzt Ihre vorhandenen Zähler ab dem ersten Tag und kümmert sich um Montage, Mieterkommunikation und Ablesung. Die Heizkostenabrechnung erstellen Sie mit einem Klick.",
		checks: [
			"Bestandszähler ab Tag eins",
			"Alles bei einem Partner",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Hamburger Altbau-Mehrfamilienhaus",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Isestraße 12",
		area: "Harvestehude · Altbau",
		units: 24,
		secondAddress: "Bramfelder Str. 31",
		appointment: {
			day: "Di, 14.10.",
			time: "8–10 Uhr",
		},
		avatars: ["AK", "MS", "JB"],
		tenant: "AK",
	},
	logoStrip: {
		text: "Hausverwaltungen in ganz Deutschland vertrauen bei der Abrechnung auf Heidi.",
		logos: [
			"vitec",
			"harte",
			"werne",
			"berlin",
			"raumgold",
			"neckar",
			"hsp",
			"progera",
			"dumax",
			"niesen",
			"wagner",
			"schleicher",
		],
	},
	noWait: {
		eyebrow: "Wechsel ohne Wartezeit",
		title: "Messdienstvertrag läuft noch? Wechseln Sie trotzdem jetzt.",
		text: "Auch während der Restlaufzeit liest Heidi Ihre vorhandenen Zähler aus und erstellt die Abrechnung. Erst wenn der alte Vertrag ausläuft, tauschen wir auf Heidi-Funkzähler.",
		notes: [
			"Übergang ohne Parallelbetrieb",
			"Kündigung erledigt Heidi per Vollmacht",
			"Ein Ansprechpartner von Anfang an",
		],
	},
	allInOne: {
		eyebrow: "Komplettservice",
		title: "Ein Partner für Montage, Mieter und Abrechnung.",
		text: "Nach Ihrer Unterschrift übernimmt Heidi die Organisation. Ihr Team muss weder Termine abstimmen noch Aushänge verteilen oder Ablesewerte einsammeln.",
		cards: [
			"Zertifizierte Monteure von Heidi: 92 % Erfolgsquote beim ersten Termin, 1–2 h Zeitfenster pro Wohnung.",
			"Heidi übernimmt Aushänge, Terminankündigungen und Rückfragen. Ihr Team wird damit nicht belastet.",
			"Fernablesung per Funk ohne Wohnungstermin, dazu die monatliche Verbrauchsinformation nach HKVO.",
			"Heizkostenabrechnung mit einem Klick, rechtssicher und automatisch an Ihr ERP- oder CRM-System übergeben.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Hamburg",
		title: "Von Blankenese bis Bergedorf. In allen sieben Bezirken.",
		sub: "Fahren Sie über einen Bezirk und sehen Sie, wie Heidi typische Hamburger Bestände übernimmt.",
		legend: "Beispielobjekt Isestraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Ein Klick genügt.",
		text: "Alle Verbrauchswerte kommen per Funk, die Kostenarten sind bereits zugeordnet. Mit einem Klick erstellt Heidi die Abrechnung für jede Einheit.",
		checks: [
			"Konform mit der Heizkostenverordnung",
			"Plausibilitätsprüfung pro Einheit",
			"Übergabe direkt an Ihre Software",
		],
	},
	service: {
		eyebrow: "Service für Hamburg",
		title: "Ihr fester Ansprechpartner für Hamburger Bestände.",
		text: "Eine feste Ansprechperson kennt Ihren Bestand und ist ab dem ersten Tag für Sie da. Montage, Ablesung und Abrechnung folgen in Hamburg demselben bewährten Ablauf.",
		kpis: [
			"Erfolgsquote beim ersten Montagetermin",
			"Tage Vorlauf für die Mieterinformation",
			"Zeitfenster für jede Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Verbrauchsinformation für Mieter. Monat für Monat automatisch.",
			text: "Jede Mietpartei erhält ihre Verbrauchswerte monatlich nach HKVO, im Vergleich zum Vorjahr. Ihr Team hat damit keinen Aufwand.",
		},
		portfolio: {
			title: "Ihr gesamter Bestand. Auf einer Plattform.",
			text: "Montagen, Ablesungen und Abrechnungen aller Liegenschaften auf einen Blick, mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Per Funk liegen alle Verbräuche vor. Mit einem Klick erstellt Heidi die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung übernimmt Heidi. Ihr Team muss nichts abstimmen.",
		"Jede Mietpartei bekommt einen eigenen Zugang zur monatlichen Verbrauchsinformation, wie von der HKVO gefordert.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Können unsere bisherigen Zähler weiter genutzt werden?",
			answer:
				"Ja. Heidi liest die vorhandenen Zähler aus, wertet die Verbräuche aus und rechnet ab. Neue Zähler kommen erst, wenn Ihr alter Messdienstvertrag endet.",
		},
		{
			question: "Ist ein Wechsel vor Vertragsende möglich?",
			answer:
				"Ja. Sie wechseln sofort, unabhängig von der Restlaufzeit. Die Kündigung übernehmen wir per Vollmacht.",
		},
		{
			question: "Wer kümmert sich um die Mieterkommunikation?",
			answer:
				"Heidi. Montagen kündigen wir 14 Tage vorher an, mit einem Zeitfenster von 1–2 Stunden, und wir beantworten die Rückfragen der Mieter.",
		},
		{
			question: "Wann ist die Heizkostenabrechnung fertig?",
			answer:
				"Sobald Sie klicken: Die Verbräuche liegen per Funk vor, Heidi erstellt die Abrechnung, Sie prüfen und geben frei.",
		},
		{
			question: "Wie wird Heidi abgerechnet?",
			answer:
				'Nach der Zahl der tatsächlich installierten Zähler plus einer Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Hamburger Bestand erhalten Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Hamburg. Heute.",
		sub: "Einmal unterschreiben. Heidi erledigt den Rest.",
	},
};

export default content;
