// Generated by scripts/extract-city.ts from the "Heidi Hannover" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/hannover/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/hannover/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./hannover-map";

const content: RegionContent = {
	slug: "hannover",
	seo: {
		title: "Messdienstanbieter Hannover ohne Mehraufwand | Heidi Systems",
		description:
			"Messdienst in Hannover, von der List bis zum Kronsberg: Heidi nutzt Ihre vorhandenen Zähler ab dem ersten Tag und kümmert sich um Montage und Abrechnung.",
		ogTitle: "Messdienst wechseln in Hannover. Ohne Mehraufwand.",
	},
	links: { nearby: ["bielefeld", "bremen"] },
	name: "Hannover",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Hannoveraner Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Hannover",
		title: "Messdienst wechseln in Hannover. Ohne Mehraufwand.",
		lede: "Ob Gründerzeit in der List oder Neubau am Kronsberg: Heidi nutzt Ihre vorhandenen Zähler ab dem ersten Tag und kümmert sich um Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Vorhandene Zähler weiter nutzen",
			"Ein Ansprechpartner für alles",
			"Abrechnung per Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Hannover",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Lister Meile 12",
		area: "List · Altbau",
		units: 20,
		secondAddress: "Limmerstraße 31",
		appointment: {
			day: "Mi, 04.11.",
			time: "9–11 Uhr",
		},
		avatars: ["JB", "DM", "FG"],
		tenant: "JB",
	},
	logoStrip: {
		text: "Hausverwaltungen in ganz Deutschland rechnen bereits mit Heidi ab.",
		logos: [
			"harte",
			"progera",
			"vitec",
			"schleicher",
			"wagner",
			"werne",
			"berlin",
			"hsp",
			"raumgold",
			"dumax",
			"niesen",
			"neckar",
		],
	},
	noWait: {
		eyebrow: "Heute wechseln",
		title: "Restlaufzeit? Heidi startet trotzdem sofort.",
		text: "Die Restlaufzeit beim bisherigen Messdienst spielt keine Rolle: Heidi liest Ihre vorhandenen Zähler aus und erstellt die Abrechnung. Getauscht wird, wenn der Vertrag endet.",
		notes: [
			"Ohne Parallelbetrieb, ohne Datenverlust",
			"Kündigung per Vollmacht durch Heidi",
			"Ein Ansprechpartner ab Start",
		],
	},
	allInOne: {
		eyebrow: "Voller Service",
		title: "Alles organisiert. Von der ersten Montage an.",
		text: "Von der ersten Montage bis zur fertigen Abrechnung organisiert Heidi alles. Ihr Team spart sich Terminabsprachen, Aushänge und das Einsammeln von Ablesewerten.",
		cards: [
			"Zertifizierte Monteure, 92 % Erfolg schon beim ersten Termin und ein Zeitfenster von 1–2 h für Ihre Mieter.",
			"Mieterkommunikation läuft über Heidi: Aushänge, Ankündigungen, Rückfragen.",
			"Ablesung per Funk, ohne dass jemand in die Wohnung muss. Die monatliche uVI nach HKVO kommt automatisch.",
			"Die rechtssichere Heizkostenabrechnung entsteht per Klick und landet direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Hannover",
		title: "Von Linden bis zum Kronsberg. In allen 13 Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Hannoveraner Bestände übernimmt.",
		legend: "Beispielobjekt Lister Meile 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Per Klick fertig.",
		text: "Funkwerte da, Kostenarten zugeordnet: Ein Klick, und Heidi erstellt jede Einzelabrechnung.",
		checks: [
			"Konform mit HKVO",
			"Plausibilitätscheck für jede Wohnung",
			"Übergabe an Ihr ERP",
		],
	},
	service: {
		eyebrow: "Service für Hannover",
		title: "Hannoveraner Bestand, persönlich betreut.",
		text: "Ob List, Linden oder Südstadt: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"Erfolg schon beim ersten Montagetermin",
			"Tage Vorlauf, bevor montiert wird",
			"Zeitfenster für Ihre Mieter",
		],
	},
	duo: {
		uvi: {
			title: "Die uVI für Ihre Mieter. Jeden Monat, ganz automatisch.",
			text: "Ihre Mieter sehen jeden Monat, was sie verbraucht haben, nach HKVO und im Vergleich zum Vorjahr. Für Ihr Team entsteht keine Arbeit.",
		},
		portfolio: {
			title: "Ein Portal für alle Liegenschaften.",
			text: "Pro Liegenschaft sehen Sie Montagen, Ablesungen und Abrechnungen an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Verbräuche per Funk, Abrechnung per Klick. Für jede Einheit, rechtssicher nach HKVO.",
		"Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung übernimmt Heidi. Ihr Team muss nichts abstimmen.",
		"Mit einem eigenen Zugang sieht jede Mietpartei jeden Monat ihre Verbrauchsinformation, genau wie es die HKVO verlangt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Was passiert mit unseren vorhandenen Zählern?",
			answer:
				"Ja. Wir übernehmen Auslesung, Auswertung und Abrechnung mit Ihren Bestandszählern. Ausgetauscht wird erst, wenn der bisherige Messdienstvertrag ausläuft.",
		},
		{
			question: "Was ist mit der Restlaufzeit unseres Vertrags?",
			answer:
				"Ja, sofort und unabhängig von der Restlaufzeit. Mit Ihrer Vollmacht kündigen wir beim bisherigen Messdienst.",
		},
		{
			question: "Wer kündigt die Montage bei den Mietern an?",
			answer:
				"Das machen wir. 14 Tage vor der Montage geht die Ankündigung raus, mit Zeitfenster von 1–2 Stunden. Rückfragen beantwortet Heidi selbst.",
		},
		{
			question: "Wann ist die Heizkostenabrechnung fertig?",
			answer:
				"Auf Knopfdruck: Die Verbräuche sind per Funk erfasst, Heidi erstellt die Abrechnung, Sie prüfen das Ergebnis und geben es frei.",
		},
		{
			question: "Wie sieht das Preismodell aus?",
			answer:
				'Grundlage sind die installierten Zähler und eine Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Hannoveraner Bestand gibt es nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Ihr Messdienst in Hannover. Ab heute mit Heidi.",
		sub: "Unterschreiben, zurücklehnen. Heidi erledigt den Rest.",
	},
};

export default content;
