/**
 * The city pages at /messdienstanbieter/<slug>, in the designs' footer order.
 * Tiny on purpose: the `city` param matcher bundles it into the client router.
 * The sitemap, the footer "Städte" group and the Germany map read it too.
 *
 * Adding a city = an entry here + `<slug>.ts` and `<slug>-map.ts` next to it
 * + its photos, all generated by `scripts/extract-city.ts` (plan, phase 7).
 * A city with `live: false` renders with `noindex` for review and is left
 * out of the sitemap, the footer and the Germany map. Set it `live: true`
 * once its go-live items are done (plan §6.4 / §7.6).
 *
 * Hamburg, Nürnberg and Münster wait for readable designs.
 */
export type CityEntry = {
	slug: string;
	name: string;
	/** Bundesland, for the Germany map. */
	state: string;
	live: boolean;
};

// prettier-ignore
export const CITIES = [
	{ slug: "berlin", name: "Berlin", state: "Berlin", live: true },
	{ slug: "muenchen", name: "München", state: "Bayern", live: false },
	{ slug: "koeln", name: "Köln", state: "Nordrhein-Westfalen", live: false },
	{ slug: "frankfurt", name: "Frankfurt", state: "Hessen", live: false },
	{ slug: "duesseldorf", name: "Düsseldorf", state: "Nordrhein-Westfalen", live: false },
	{ slug: "stuttgart", name: "Stuttgart", state: "Baden-Württemberg", live: false },
	{ slug: "leipzig", name: "Leipzig", state: "Sachsen", live: false },
	{ slug: "dortmund", name: "Dortmund", state: "Nordrhein-Westfalen", live: false },
	{ slug: "bremen", name: "Bremen", state: "Bremen", live: false },
	{ slug: "essen", name: "Essen", state: "Nordrhein-Westfalen", live: false },
	{ slug: "dresden", name: "Dresden", state: "Sachsen", live: false },
	{ slug: "hannover", name: "Hannover", state: "Niedersachsen", live: false },
	{ slug: "duisburg", name: "Duisburg", state: "Nordrhein-Westfalen", live: false },
	{ slug: "bochum", name: "Bochum", state: "Nordrhein-Westfalen", live: false },
	{ slug: "wuppertal", name: "Wuppertal", state: "Nordrhein-Westfalen", live: false },
	{ slug: "bielefeld", name: "Bielefeld", state: "Nordrhein-Westfalen", live: false },
	{ slug: "bonn", name: "Bonn", state: "Nordrhein-Westfalen", live: false },
	{ slug: "mannheim", name: "Mannheim", state: "Baden-Württemberg", live: false },
	{ slug: "karlsruhe", name: "Karlsruhe", state: "Baden-Württemberg", live: false },
	{ slug: "augsburg", name: "Augsburg", state: "Bayern", live: false },
	{ slug: "wiesbaden", name: "Wiesbaden", state: "Hessen", live: false },
	{ slug: "moenchengladbach", name: "Mönchengladbach", state: "Nordrhein-Westfalen", live: false },
] as const satisfies readonly CityEntry[];

export type CitySlug = (typeof CITIES)[number]["slug"];

export const isCitySlug = (s: string): s is CitySlug =>
	CITIES.some((c) => c.slug === s);

export const cityBySlug = (slug: string): CityEntry | undefined =>
	CITIES.find((c) => c.slug === slug);

export const LIVE_CITIES: readonly CityEntry[] = CITIES.filter((c) => c.live);

export const isLiveCity = (slug: string) => cityBySlug(slug)?.live ?? false;
