// Generated by scripts/extract-city.ts from the "Heidi Karlsruhe" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/karlsruhe/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/karlsruhe/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./karlsruhe-map";

const content: RegionContent = {
	slug: "karlsruhe",
	seo: {
		title: "Messdienstanbieter Karlsruhe, schnell | Heidi Systems",
		description:
			"Messdienst für Karlsruher Hausverwaltungen: ob Weststadt oder Waldstadt, Heidi übernimmt Ihre vorhandenen Zähler sofort und rechnet die Heizkosten ab.",
		ogTitle: "Messdienst wechseln in Karlsruhe. Schnell und einfach.",
	},
	links: { nearby: ["mannheim", "stuttgart"] },
	name: "Karlsruhe",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Karlsruher Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Karlsruhe",
		title: "Messdienst wechseln in Karlsruhe. Schnell und einfach.",
		lede: "Ob Gründerzeit in der Weststadt oder Wohnanlage in der Waldstadt: Heidi übernimmt Ihre vorhandenen Zähler sofort und kümmert sich um Montage, Mieterinfo, Ablesung und Abrechnung.",
		checks: [
			"Bestehende Zähler bleiben",
			"Komplettservice",
			"Heizkostenabrechnung auf Knopfdruck",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Karlsruhe",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Kaiserallee 12",
		area: "Weststadt · Altbau",
		units: 28,
		secondAddress: "Durlacher Allee 31",
		appointment: {
			day: "Mo, 26.10.",
			time: "9–11 Uhr",
		},
		avatars: ["FG", "NB", "CL"],
		tenant: "FG",
	},
	logoStrip: {
		text: "Verwaltungen aus ganz Deutschland vertrauen bei der Abrechnung auf Heidi.",
		logos: [
			"neckar",
			"harte",
			"raumgold",
			"wagner",
			"progera",
			"vitec",
			"hsp",
			"berlin",
			"dumax",
			"werne",
			"schleicher",
			"niesen",
		],
	},
	noWait: {
		eyebrow: "Wechsel ohne Wartezeit",
		title: "Restlaufzeit? Heidi startet trotzdem sofort.",
		text: "Heidi rechnet ab sofort mit Ihren vorhandenen Zählern ab, egal wie lange der alte Vertrag noch gilt. Erst zum Vertragsende tauschen wir auf Heidi-Funkzähler.",
		notes: [
			"Übergang ohne Datenverlust",
			"Kündigung per Vollmacht übernommen",
			"Feste Ansprechperson ab dem Start",
		],
	},
	allInOne: {
		eyebrow: "Alles erledigt",
		title: "Sie unterschreiben. Heidi macht den Rest.",
		text: "Nach einer Unterschrift organisiert Heidi den gesamten Ablauf. Termine, Aushänge und Ablesewerte muss Ihr Team nicht mehr nachhalten.",
		cards: [
			"Zertifizierte Monteure von Heidi: 92 % Erfolgsquote beim ersten Termin, 1–2 h Zeitfenster pro Wohnung.",
			"Terminankündigungen, Aushänge und Fragen der Mieter laufen komplett über Heidi.",
			"Abgelesen wird per Funk, ganz ohne Wohnungstermin. Die monatliche uVI nach HKVO geht automatisch raus.",
			"Heizkostenabrechnung mit einem Klick, rechtssicher und automatisch an Ihr ERP- oder CRM-System übergeben.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Karlsruhe",
		title: "Von Neureut bis Durlach. In allen 27 Stadtteilen.",
		sub: "Fahren Sie über einen Stadtteil und sehen Sie, wie Heidi typische Karlsruher Bestände übernimmt.",
		legend: "Beispielobjekt Kaiserallee 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Mit einem Klick erledigt.",
		text: "Die Verbräuche kommen per Funk, die Kostenarten sind hinterlegt. Ein Klick genügt, und Heidi rechnet jede Einheit ab.",
		checks: [
			"Nach HKVO rechtssicher",
			"Automatische Plausibilitätsprüfung",
			"Übergabe an Ihr ERP",
		],
	},
	service: {
		eyebrow: "Service für Karlsruhe",
		title: "Karlsruher Bestand, persönlich betreut.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Weststadt, Südstadt oder Durlach. Montage, Ablesung und Abrechnung folgen in Karlsruhe demselben bewährten Ablauf.",
		kpis: [
			"Erfolgsquote im ersten Anlauf",
			"Tage vorher angekündigt",
			"Zeitfenster je Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Jeden Monat die Verbrauchsinformation. Ohne Aufwand.",
			text: "Monat für Monat sieht jede Mietpartei ihren Verbrauch nach HKVO, mit Vorjahresvergleich. Ihr Team hat keine Arbeit damit.",
		},
		portfolio: {
			title: "Liegenschaften verwalten. Alles an einem Ort.",
			text: "Pro Liegenschaft sehen Sie Montagen, Ablesungen und Abrechnungen an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Per Funk liegen alle Verbräuche vor. Mit einem Klick erstellt Heidi die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung übernimmt Heidi. Ihr Team muss nichts abstimmen.",
		"Jede Mietpartei bekommt einen Zugang und findet dort Monat für Monat ihre Verbrauchsinformation nach HKVO.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Übernimmt Heidi unsere vorhandenen Zähler?",
			answer:
				"Ja. Ihre vorhandenen Zähler werden von Heidi ausgelesen und ausgewertet, die Abrechnung kommt von uns. Neue Geräte gibt es erst nach Ablauf Ihres alten Messdienstvertrags.",
		},
		{
			question: "Können wir wechseln, obwohl der Vertrag noch läuft?",
			answer:
				"Nein. Heidi übernimmt ab sofort, egal wie lange der alte Vertrag noch gilt. Um die Kündigung kümmern wir uns per Vollmacht.",
		},
		{
			question: "Wer kümmert sich um die Mieter?",
			answer:
				"Wir übernehmen das: Ankündigung 14 Tage im Voraus, ein Zeitfenster von 1–2 Stunden am Montagetag und direkte Antworten auf Rückfragen.",
		},
		{
			question: "Wann ist die Heizkostenabrechnung fertig?",
			answer:
				"Sehr schnell. Weil die Verbräuche per Funk vorliegen, erzeugt Heidi die Abrechnung mit einem Klick. Danach prüfen Sie und geben frei.",
		},
		{
			question: "Wie sieht das Preismodell aus?",
			answer:
				'Grundlage sind die installierten Zähler und eine Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Karlsruher Bestand gibt es nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Ihr Messdienst in Karlsruhe. Ab heute mit Heidi.",
		sub: "Sie unterschreiben einmal. Heidi kümmert sich um alles Weitere.",
	},
};

export default content;
