// Generated by scripts/extract-city.ts from the "Heidi Köln" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/koeln/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/koeln/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./koeln-map";

const content: RegionContent = {
	slug: "koeln",
	seo: {
		title: "Messdienstanbieter Köln ohne Aufwand | Heidi Systems",
		description:
			"Messdienst für Hausverwaltungen in Köln: ob Altbau im Veedel oder große Wohnanlage, Heidi übernimmt Ihre Zähler sofort und erstellt die Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Köln. Ohne Aufwand.",
	},
	links: { nearby: ["bonn", "duesseldorf", "wuppertal"] },
	name: "Köln",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Kölner Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Köln",
		title: "Messdienst wechseln in Köln. Ohne Aufwand.",
		lede: "Ob Altbau im Veedel oder große Wohnanlage: Heidi übernimmt Ihre vorhandenen Zähler sofort und erledigt Montage, Mieterinfo, Ablesung und die Heizkostenabrechnung auf Knopfdruck.",
		checks: [
			"Vorhandene Zähler weiter nutzen",
			"Rundum betreut",
			"Abrechnung in Sekunden",
		],
		photoAlt: "Kölner Altbau-Mehrfamilienhaus",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Brüsseler Straße 12",
		area: "Belgisches Viertel · Altbau",
		units: 24,
		secondAddress: "Neusser Str. 31",
		appointment: {
			day: "Di, 14.10.",
			time: "8–10 Uhr",
		},
		avatars: ["AK", "MS", "JB"],
		tenant: "AK",
	},
	logoStrip: {
		text: "Hausverwaltungen aus ganz Deutschland rechnen schon mit Heidi ab.",
		logos: [
			"raumgold",
			"progera",
			"niesen",
			"vitec",
			"werne",
			"dumax",
			"schleicher",
			"berlin",
			"neckar",
			"wagner",
			"hsp",
			"harte",
		],
	},
	noWait: {
		eyebrow: "Jetzt umsteigen",
		title: "Restlaufzeit beim alten Messdienst? Egal.",
		text: "Sie müssen nicht bis zum Vertragsende warten. Heidi liest Ihre vorhandenen Zähler ab sofort aus und rechnet ab. Die Funkzähler von Heidi kommen erst, wenn der alte Vertrag ausgelaufen ist.",
		notes: [
			"Kein Datenverlust beim Umstieg",
			"Kündigung übernimmt Heidi per Vollmacht",
			"Feste Ansprechperson ab dem Start",
		],
	},
	allInOne: {
		eyebrow: "Alles erledigt",
		title: "Sie unterschreiben. Heidi macht den Rest.",
		text: "Von der ersten Montage bis zur fertigen Abrechnung organisiert Heidi alles. Ihr Team spart sich Terminabsprachen, Aushänge und das Einsammeln von Ablesewerten.",
		cards: [
			"Zertifizierte Monteure, 92 % Erfolg schon beim ersten Termin und ein Zeitfenster von 1–2 h für Ihre Mieter.",
			"Terminankündigungen, Aushänge und Fragen der Mieter laufen komplett über Heidi.",
			"Abgelesen wird per Funk, ganz ohne Wohnungstermin. Die monatliche uVI nach HKVO geht automatisch raus.",
			"Rechtssicher abgerechnet auf Knopfdruck und direkt an Ihr ERP- oder CRM-System übergeben.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Köln",
		title: "Linksrheinisch wie rechtsrheinisch. In allen neun Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Kölner Bestände übernimmt.",
		legend: "Beispielobjekt Brüsseler Straße 12",
	},
	billing: {
		title: "Ein Klick. Alle Abrechnungen fertig.",
		text: "Die Verbrauchsdaten liegen per Funk vor, die Kosten sind verteilt. Ein Klick, und Heidi erstellt die Heizkostenabrechnung für jede Wohnung im Haus.",
		checks: [
			"Rechtssicher nach HKVO erstellt",
			"Jede Einheit auf Plausibilität geprüft",
			"Direkt in Ihrer Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Köln",
		title: "Ein fester Ansprechpartner für Ihre Kölner Objekte.",
		text: "Links wie rechts vom Rhein: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach demselben bewährten Ablauf.",
		kpis: [
			"Erfolg schon beim ersten Montagetermin",
			"Tage Vorankündigung für Ihre Mieter",
			"Zeitfenster für Mieter bei der Montage",
		],
	},
	duo: {
		uvi: {
			title: "Die uVI für Ihre Mieter. Jeden Monat, ganz automatisch.",
			text: "Ihre Mieter sehen monatlich ihren Verbrauch nach HKVO, mit Vergleich zum Vorjahresmonat. Ihr Team muss dafür nichts tun.",
		},
		portfolio: {
			title: "Jede Liegenschaft im Blick. Auf einer Plattform.",
			text: "Sie sehen Montagen, Ablesungen und Abrechnungen pro Liegenschaft an einem Ort, für Heidi-Funkzähler genauso wie für übernommene Bestandszähler.",
		},
	},
	trio: [
		"Alle Verbrauchswerte sind per Funk erfasst. Mit einem Klick entsteht die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Heidi kümmert sich um Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung. Ihr Team hat damit nichts zu tun.",
		"Jede Mietpartei hat ihren eigenen Zugang und findet dort jeden Monat ihre Verbrauchsinformation, wie es die HKVO verlangt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Nutzt Heidi unsere bisherigen Zähler weiter?",
			answer:
				"Ja. Heidi liest die vorhandenen Zähler aus, wertet die Verbräuche aus und erstellt die Abrechnung. Ausgetauscht wird erst, wenn Ihr Vertrag mit dem bisherigen Messdienst ausläuft.",
		},
		{
			question: "Müssen wir das Vertragsende abwarten?",
			answer:
				"Nein. Der Wechsel zu Heidi geht sofort, egal wie lange Ihr Vertrag noch läuft. Die Kündigung erledigen wir per Vollmacht.",
		},
		{
			question: "Wer kümmert sich um die Mieter?",
			answer:
				"Heidi. Wir kündigen jede Montage 14 Tage vorher an, geben ein Zeitfenster von 1–2 Stunden vor und beantworten die Fragen der Mieter.",
		},
		{
			question: "Wie aufwendig ist die Heizkostenabrechnung?",
			answer:
				"Gar nicht: Alle Verbräuche liegen per Funk vor, Heidi erstellt die Abrechnung auf Knopfdruck. Sie prüfen nur noch und geben frei.",
		},
		{
			question: "Was zahlen wir für Heidi?",
			answer:
				'Sie zahlen für die tatsächlich installierten Zähler plus eine Abrechnungspauschale. Nach dem Portfolio-Check bekommen Sie ein konkretes <a href="/preise">Angebot</a> für Ihren Kölner Bestand.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Köln. Heute.",
		sub: "Unterschreiben, zurücklehnen. Heidi erledigt den Rest.",
	},
};

export default content;
