// Generated by scripts/extract-city.ts from the "Heidi Leipzig" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/leipzig/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/leipzig/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./leipzig-map";

const content: RegionContent = {
	slug: "leipzig",
	seo: {
		title: "Messdienstanbieter Leipzig ohne Warten | Heidi Systems",
		description:
			"Messdienst für Hausverwaltungen in Leipzig: Gründerzeit in der Südvorstadt oder Plattenbau in Grünau, Heidi übernimmt Ihre Zähler sofort und rechnet ab.",
		ogTitle: "Messdienst wechseln in Leipzig. Ohne Warten.",
	},
	links: { nearby: ["dresden", "berlin"] },
	name: "Leipzig",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Leipziger Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Leipzig",
		title: "Messdienst wechseln in Leipzig. Ohne Warten.",
		lede: "Ob Gründerzeit in der Südvorstadt oder Plattenbau in Grünau: Heidi übernimmt Ihre bestehenden Zähler sofort und organisiert Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Vorhandene Zähler direkt übernehmen",
			"Ein Partner für den ganzen Ablauf",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Leipzig",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Karl-Heine-Straße 12",
		area: "Plagwitz · Altbau",
		units: 30,
		secondAddress: "Eisenbahnstraße 31",
		appointment: {
			day: "Mi, 28.10.",
			time: "8–10 Uhr",
		},
		avatars: ["TH", "NB", "CL"],
		tenant: "TH",
	},
	logoStrip: {
		text: "Bundesweit rechnen Hausverwaltungen schon mit Heidi ab.",
		logos: [
			"neckar",
			"dumax",
			"harte",
			"berlin",
			"raumgold",
			"vitec",
			"wagner",
			"progera",
			"hsp",
			"werne",
			"niesen",
			"schleicher",
		],
	},
	noWait: {
		eyebrow: "Jetzt umsteigen",
		title: "Noch an den alten Messdienst gebunden? Wechseln Sie trotzdem.",
		text: "Heidi startet mit Ihren vorhandenen Zählern: Auslesen und Abrechnen läuft ab sofort über uns, auch wenn der Vertrag mit dem bisherigen Messdienst noch Jahre gilt. Die Geräte tauschen wir erst zum Vertragsende.",
		notes: [
			"Kein Datenverlust beim Umstieg",
			"Heidi kündigt per Vollmacht",
			"Eine Ansprechperson für alles",
		],
	},
	allInOne: {
		eyebrow: "Komplett betreut",
		title: "Ein Partner für den ganzen Ablauf.",
		text: "Mit Ihrer Unterschrift übernimmt Heidi die Organisation. Termine, Aushänge und Ablesewerte sind nicht mehr Sache Ihres Teams.",
		cards: [
			"Montage durch zertifizierte Heidi-Monteure: 92 % Erfolg beim ersten Termin, 1–2 h Zeitfenster für die Mieter.",
			"Heidi informiert Ihre Mieter per Aushang und Ankündigung und beantwortet ihre Fragen direkt.",
			"Kein Ablesetermin in der Wohnung: Heidi liest per Funk ab und verschickt monatlich die uVI nach HKVO.",
			"Heizkostenabrechnung auf Knopfdruck, rechtssicher und mit direkter Übergabe an Ihr ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Leipzig",
		title: "Von Gohlis bis Connewitz. In allen zehn Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Leipziger Bestände übernimmt.",
		legend: "Beispielobjekt Karl-Heine-Straße 12",
	},
	billing: {
		title: "Heizkostenabrechnung in Sekunden.",
		text: "Die Verbräuche sind per Funk erfasst, die Kostenarten zugeordnet. Mit einem Klick entstehen die Abrechnungen für alle Einheiten.",
		checks: [
			"Konform mit der Heizkostenverordnung",
			"Plausibilitätsprüfung inklusive",
			"Übergabe an Ihr ERP",
		],
	},
	service: {
		eyebrow: "Service für Leipzig",
		title: "Leipziger Bestand, persönlich betreut.",
		text: "Ob Gohlis, Plagwitz oder Connewitz: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"Erfolg beim ersten Termin",
			"Tage Ankündigung vor der Montage",
			"Zeitfenster pro Mietpartei",
		],
	},
	duo: {
		uvi: {
			title: "Jeden Monat die Verbrauchsinformation. Ohne Aufwand.",
			text: "Ihre Mieter sehen jeden Monat, was sie verbraucht haben, nach HKVO und im Vergleich zum Vorjahr. Für Ihr Team entsteht keine Arbeit.",
		},
		portfolio: {
			title: "Ihr Portfolio. Übersichtlich an einem Ort.",
			text: "Montagen, Ablesungen und Abrechnungen aller Liegenschaften auf einen Blick, mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Heidi nutzt die per Funk erfassten Werte und erstellt per Klick die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Heidi kündigt per Vollmacht, montiert, informiert Ihre Mieter und rechnet ab. Sie müssen nichts koordinieren.",
		"Jede Mietpartei bekommt einen eigenen Zugang zur monatlichen Verbrauchsinformation, wie von der HKVO gefordert.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Was passiert mit unseren vorhandenen Zählern?",
			answer:
				"Ja. Die verbauten Zähler bleiben zunächst, Heidi liest sie aus und erstellt daraus die Abrechnung. Erst zum Ende des alten Vertrags tauschen wir.",
		},
		{
			question: "Was ist mit der Restlaufzeit unseres Vertrags?",
			answer:
				"Ja, sofort und unabhängig von der Restlaufzeit. Mit Ihrer Vollmacht kündigen wir beim bisherigen Messdienst.",
		},
		{
			question: "Wer übernimmt die Mieterinformation?",
			answer:
				"Heidi. Ihre Mieter erfahren 14 Tage vorher vom Montagetermin, bekommen ein Zeitfenster von 1–2 Stunden und wenden sich mit Fragen direkt an uns.",
		},
		{
			question: "Wie kommen wir zur Heizkostenabrechnung?",
			answer:
				"Die Verbrauchsdaten kommen per Funk, also entsteht die Abrechnung per Klick. Ihre Aufgabe: kurz prüfen und freigeben.",
		},
		{
			question: "Welche Kosten entstehen mit Heidi?",
			answer:
				'Grundlage sind die installierten Zähler und eine Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Leipziger Bestand gibt es nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Ihr Messdienst in Leipzig. Ab heute mit Heidi.",
		sub: "Unterschreiben, zurücklehnen. Heidi erledigt den Rest.",
	},
};

export default content;
