// Generated by scripts/extract-city.ts from the "Heidi Mannheim" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/mannheim/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/mannheim/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./mannheim-map";

const content: RegionContent = {
	slug: "mannheim",
	seo: {
		title: "Messdienstanbieter Mannheim ohne Umwege | Heidi Systems",
		description:
			"Messdienst in Mannheim, von der Neckarstadt bis zur Vogelstang: Heidi übernimmt Ihre vorhandenen Zähler sofort und organisiert Montage, Ablesung und Abrechnung.",
		ogTitle: "Messdienst wechseln in Mannheim. Ohne Doppelarbeit.",
	},
	links: { nearby: ["karlsruhe", "frankfurt", "stuttgart"] },
	name: "Mannheim",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Mannheimer Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Mannheim",
		title: "Messdienst wechseln in Mannheim. Ohne Doppelarbeit.",
		lede: "Ob Altbau in der Neckarstadt oder Wohnanlage auf der Vogelstang: Heidi übernimmt Ihre vorhandenen Zähler sofort und organisiert Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bestandszähler ab Tag eins",
			"Alles bei Heidi",
			"Ein Klick zur Abrechnung",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Mannheim",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Augartenstraße 12",
		area: "Schwetzingerstadt · Altbau",
		units: 32,
		secondAddress: "Mittelstraße 31",
		appointment: {
			day: "Di, 06.10.",
			time: "9–11 Uhr",
		},
		avatars: ["AK", "RS", "HV"],
		tenant: "AK",
	},
	logoStrip: {
		text: "Hausverwaltungen in ganz Deutschland rechnen bereits mit Heidi ab.",
		logos: [
			"raumgold",
			"werne",
			"harte",
			"berlin",
			"vitec",
			"schleicher",
			"neckar",
			"niesen",
			"progera",
			"wagner",
			"hsp",
			"dumax",
		],
	},
	noWait: {
		eyebrow: "Heute wechseln",
		title: "Messdienstvertrag läuft noch? Wechseln Sie trotzdem jetzt.",
		text: "Sie müssen nicht bis zum Vertragsende warten. Heidi liest Ihre vorhandenen Zähler ab sofort aus und rechnet ab. Die Funkzähler von Heidi kommen erst, wenn der alte Vertrag ausgelaufen ist.",
		notes: [
			"Ohne Doppelbetrieb, ohne Datenverlust",
			"Kündigung per Vollmacht übernommen",
			"Feste Ansprechperson von Beginn an",
		],
	},
	allInOne: {
		eyebrow: "Voller Service",
		title: "Ein Partner für Montage, Mieter und Abrechnung.",
		text: "Einmal unterschrieben, organisiert Heidi Montage, Mieterinfo, Ablesung und Abrechnung. Ihr Team muss keinen Terminen, Aushängen oder Ablesewerten mehr hinterherlaufen.",
		cards: [
			"Zertifizierte Monteure von Heidi schaffen 92 % der Montagen beim ersten Termin. Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Aushänge und Terminankündigungen verschickt Heidi, Rückfragen beantworten wir direkt.",
			"Abgelesen wird per Funk, ganz ohne Wohnungstermin. Die monatliche uVI nach HKVO geht automatisch raus.",
			"Ein Klick zur rechtssicheren Heizkostenabrechnung, die direkt in Ihr ERP- oder CRM-System geht.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Mannheim",
		title: "Von den Quadraten bis nach Sandhofen. In allen 17 Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Mannheimer Bestände übernimmt.",
		legend: "Beispielobjekt Augartenstraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung in Sekunden.",
		text: "Alles ist vorbereitet: Funkwerte erfasst, Kostenarten zugeordnet. Sie klicken, Heidi erstellt die Abrechnungen.",
		checks: [
			"Rechtssicher nach HKVO",
			"Automatische Plausibilitätsprüfung",
			"Direkt übergeben an Ihre Software",
		],
	},
	service: {
		eyebrow: "Service für Mannheim",
		title: "Ihre Mannheimer Objekte. Eine feste Ansprechperson.",
		text: "Ob Neckarstadt, Lindenhof oder Käfertal: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"der Montagen klappen beim ersten Termin",
			"Tage Vorankündigung je Termin",
			"Zeitfenster am Montagetag",
		],
	},
	duo: {
		uvi: {
			title: "Monatliche Verbrauchsinfo. Automatisch für jede Mietpartei.",
			text: "Heidi stellt jeder Mietpartei monatlich ihren Verbrauch bereit, nach HKVO und mit Vorjahresvergleich. Ihr Team ist nicht beteiligt.",
		},
		portfolio: {
			title: "Ein Portal für alle Liegenschaften.",
			text: "Eine Plattform für den ganzen Bestand: Montagen, Ablesungen und Abrechnungen jeder Liegenschaft, mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Die Funkwerte sind schon da. Mit einem Klick erstellt Heidi die Abrechnung jeder Einheit, rechtssicher nach HKVO.",
		"Heidi kündigt per Vollmacht, montiert, informiert Ihre Mieter und rechnet ab. Sie müssen nichts koordinieren.",
		"Jede Mietpartei erhält einen persönlichen Zugang und sieht ihre monatliche Verbrauchsinformation, so wie es die HKVO vorschreibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Übernehmen Sie unsere bisherigen Zähler?",
			answer:
				"Ja. Die verbauten Zähler bleiben zunächst, Heidi liest sie aus und erstellt daraus die Abrechnung. Erst zum Ende des alten Vertrags tauschen wir.",
		},
		{
			question: "Wann können wir frühestens wechseln?",
			answer:
				"Ja. Sie wechseln sofort, unabhängig von der Restlaufzeit. Die Kündigung übernehmen wir per Vollmacht.",
		},
		{
			question: "Wie läuft die Kommunikation mit den Mietern?",
			answer:
				"Über Heidi. Wir kündigen Montagen 14 Tage im Voraus an, nennen ein Zeitfenster von 1–2 Stunden und kümmern uns um Rückfragen.",
		},
		{
			question: "Wann ist die Heizkostenabrechnung fertig?",
			answer:
				"Sehr schnell. Weil die Verbräuche per Funk vorliegen, erzeugt Heidi die Abrechnung mit einem Klick. Danach prüfen Sie und geben frei.",
		},
		{
			question: "Wie berechnet Heidi die Kosten?",
			answer:
				'Sie zahlen nur für tatsächlich installierte Zähler plus eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein <a href="/preise">Angebot</a> für Ihren Mannheimer Bestand.',
		},
	],
	final: {
		title: "Jetzt in Mannheim den Messdienst wechseln.",
		sub: "Unterschrift genügt. Alles Weitere macht Heidi.",
	},
};

export default content;
