// Generated by scripts/extract-city.ts from the "Heidi Mönchengladbach" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/moenchengladbach/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/moenchengladbach/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./moenchengladbach-map";

const content: RegionContent = {
	slug: "moenchengladbach",
	seo: {
		title: "Messdienstanbieter Mönchengladbach | Heidi Systems",
		description:
			"Messdienst in Mönchengladbach: ob Altbau in Gladbach oder Wohnanlage in Rheydt, Heidi übernimmt Ihre bestehenden Zähler sofort und erstellt die Abrechnung.",
		ogTitle: "Messdienst wechseln in Mönchengladbach. Ohne Zusatzaufwand.",
	},
	links: { nearby: ["duesseldorf", "duisburg"] },
	name: "Mönchengladbach",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Mönchengladbacher Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Mönchengladbach",
		title: "Messdienst wechseln in Mönchengladbach. Ohne Zusatzaufwand.",
		lede: "Ob Altbau in Gladbach oder Wohnanlage in Rheydt: Heidi übernimmt Ihre bestehenden Zähler sofort und erledigt Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bestandszähler sofort nutzbar",
			"Ein Partner für den ganzen Ablauf",
			"Heizkostenabrechnung per Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Mönchengladbach",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Bismarckstraße 12",
		area: "Gladbach · Altbau",
		units: 16,
		secondAddress: "Odenkirchener Straße 31",
		appointment: {
			day: "Mo, 12.10.",
			time: "10–12 Uhr",
		},
		avatars: ["FG", "CL", "EK"],
		tenant: "FG",
	},
	logoStrip: {
		text: "Hausverwaltungen in ganz Deutschland rechnen bereits mit Heidi ab.",
		logos: [
			"dumax",
			"neckar",
			"schleicher",
			"wagner",
			"niesen",
			"werne",
			"hsp",
			"berlin",
			"progera",
			"raumgold",
			"harte",
			"vitec",
		],
	},
	noWait: {
		eyebrow: "Heute wechseln",
		title: "Noch an den alten Messdienst gebunden? Wechseln Sie trotzdem.",
		text: "Ihr bisheriger Messdienstvertrag läuft weiter, Heidi übernimmt trotzdem schon jetzt Auslesung und Abrechnung mit den vorhandenen Zählern. Der Gerätetausch folgt zum Vertragsende.",
		notes: [
			"Übergang ohne Datenverlust",
			"Heidi kündigt per Vollmacht",
			"Eine Ansprechperson für alles",
		],
	},
	allInOne: {
		eyebrow: "Ein Partner für alles",
		title: "Vier Aufgaben. Ein Ansprechpartner.",
		text: "Sie unterschreiben, Heidi organisiert. Kein Nachtelefonieren bei Terminen, Aushängen oder Ablesewerten für Ihr Team.",
		cards: [
			"Zertifizierte Monteure von Heidi schaffen 92 % der Montagen beim ersten Termin. Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Heidi übernimmt Aushänge, Terminankündigungen und Rückfragen. Ihr Team wird damit nicht belastet.",
			"Abgelesen wird per Funk, ganz ohne Wohnungstermin. Die monatliche uVI nach HKVO geht automatisch raus.",
			"Die Heizkostenabrechnung entsteht mit einem Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Mönchengladbach",
		title: "Von Neuwerk bis Wickrath. In der ganzen Stadt.",
		sub: "Fahren Sie über einen Stadtteil und sehen Sie, wie Heidi typische Mönchengladbacher Bestände übernimmt.",
		legend: "Beispielobjekt Bismarckstraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung in Sekunden.",
		text: "Alles ist vorbereitet: Funkwerte erfasst, Kostenarten zugeordnet. Sie klicken, Heidi erstellt die Abrechnungen.",
		checks: [
			"Nach Heizkostenverordnung",
			"Jede Einheit auf Plausibilität geprüft",
			"Anbindung an Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Mönchengladbach",
		title: "Mönchengladbacher Bestand, persönlich betreut.",
		text: "Ob Gladbach, Rheydt oder Odenkirchen: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"Erfolgsquote im ersten Anlauf",
			"Tage Vorankündigung für Ihre Mieter",
			"Zeitfenster für Mieter bei der Montage",
		],
	},
	duo: {
		uvi: {
			title: "Verbrauchsinformation für Mieter. Monat für Monat automatisch.",
			text: "Ihre Mieter sehen monatlich ihren Verbrauch nach HKVO, mit Vergleich zum Vorjahresmonat. Ihr Team muss dafür nichts tun.",
		},
		portfolio: {
			title: "Ihr gesamter Bestand. Auf einer Plattform.",
			text: "Montagen, Ablesungen, Abrechnungen. Für jede Liegenschaft auf einer Plattform, egal ob Heidi-Funkzähler oder übernommene Bestandszähler.",
		},
	},
	trio: [
		"Die Verbrauchswerte liegen per Funk bereit. Ein Klick, und die Abrechnung für jede Einheit steht, rechtssicher nach HKVO.",
		"Vom Kündigen per Vollmacht über die Montage bis zur Abrechnung kümmert sich Heidi. Ihr Team koordiniert nichts.",
		"Jede Mietpartei hat ihren eigenen Zugang und findet dort jeden Monat ihre Verbrauchsinformation, wie es die HKVO verlangt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Nutzt Heidi unsere bisherigen Zähler weiter?",
			answer:
				"Sie bleiben. Heidi liest sie aus, wertet die Verbräuche aus und erstellt die Abrechnung. Getauscht wird erst, wenn Ihr Vertrag mit dem bisherigen Messdienst endet.",
		},
		{
			question: "Ist ein Wechsel vor Vertragsende möglich?",
			answer:
				"Nein. Der Wechsel ist sofort möglich, auch bei langer Restlaufzeit. Die Kündigung beim bisherigen Messdienst übernehmen wir mit Ihrer Vollmacht.",
		},
		{
			question: "Wer kümmert sich um die Mieterkommunikation?",
			answer:
				"Über Heidi. Wir kündigen Montagen 14 Tage im Voraus an, nennen ein Zeitfenster von 1–2 Stunden und kümmern uns um Rückfragen.",
		},
		{
			question: "Wie kommen wir zur Heizkostenabrechnung?",
			answer:
				"Mit einem Klick. Die Funkwerte sind schon da, Heidi rechnet ab, und Sie geben das geprüfte Ergebnis frei.",
		},
		{
			question: "Wie rechnet Heidi ab?",
			answer:
				'Grundlage sind die installierten Zähler und eine Abrechnungspauschale. Ein konkretes <a href="/preise">Angebot</a> für Ihren Mönchengladbacher Bestand gibt es nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Ihr Messdienst in Mönchengladbach. Ab heute mit Heidi.",
		sub: "Unterschrift genügt. Alles Weitere macht Heidi.",
	},
};

export default content;
