// Generated by scripts/extract-city.ts from the "Heidi München" design.
import type { MapGeometry } from "$lib/landing/sections/region/types";

const map: MapGeometry = {
	ariaLabel: "Karte der Münchner Stadtbezirke",
	viewBox: "-6 -6 612 475",
	areaLabel: "Stadtbezirk",
	districts: [
		{
			name: "Altstadt-Lehel",
			shape: {
				kind: "path",
				d: "M381.9 227.5 L386.5 239.5 L388.5 242.0 L393.3 245.2 L390.3 251.0 L386.8 267.5 L384.8 270.8 L380.1 275.2 L381.0 275.5 L383.7 273.0 L382.2 277.1 L379.5 280.6 L377.4 281.4 L375.6 284.5 L376.6 284.9 L374.0 289.0 L369.1 285.9 L367.9 283.6 L362.6 283.4 L357.1 285.3 L354.6 285.1 L347.6 291.1 L343.5 289.6 L341.8 287.3 L342.2 286.7 L338.1 277.4 L339.5 269.3 L345.6 264.2 L352.9 260.0 L359.2 262.0 L360.5 257.8 L368.9 260.5 L371.7 250.4 L371.2 243.9 L373.3 243.4 L377.0 236.1 L379.3 233.7 L379.9 231.0 L378.8 227.3Z",
			},
			label: {
				x: 354.5,
				y: 270.8,
				lines: ["Altstadt-", "Lehel"],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Repräsentative Altbauten, Wohn- und Geschäftshäuser",
			hint: "Gemischt genutzte Häuser: Heidi übernimmt die vorhandenen Zähler sofort, egal wie lange der Altvertrag läuft.",
		},
		{
			name: "Ludwigsvorstadt-Isarvorstadt",
			shape: {
				kind: "path",
				d: "M310.9 259.7 L331.3 265.6 L339.5 269.3 L338.1 277.4 L342.2 286.7 L341.8 287.3 L343.6 289.7 L347.6 291.1 L354.6 285.1 L357.1 285.3 L362.7 283.4 L367.9 283.6 L369.1 285.9 L375.5 289.4 L375.3 290.1 L369.6 297.1 L364.7 297.9 L360.4 300.4 L338.4 318.3 L334.2 323.4 L303.9 302.4 L306.1 294.8 L307.9 292.1 L307.2 289.2 L308.7 286.1 L309.4 281.0 L313.1 275.6 L313.2 271.3 L308.5 270.3 L310.4 267.4Z",
			},
			label: {
				x: 325.7,
				y: 293.4,
				lines: ["Ludwigsv.-", "Isarvorst."],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Gründerzeit-Altbau im Glockenbach- und Schlachthofviertel",
			hint: "Viele Heizkörper pro Wohnung: Funk-Heizkostenverteiler werden ohne Wohnungstermin abgelesen.",
		},
		{
			name: "Maxvorstadt",
			shape: {
				kind: "path",
				d: "M336.7 226.4 L346.8 227.2 L355.8 230.9 L367.7 233.3 L366.1 237.6 L366.6 238.4 L371.9 239.4 L373.1 237.4 L376.3 235.7 L376.6 237.2 L373.4 243.3 L371.2 243.9 L371.7 250.4 L368.9 260.5 L360.5 257.8 L359.2 262.0 L352.9 260.0 L345.6 264.2 L339.5 269.3 L331.3 265.6 L311.0 259.4 L310.9 263.3 L295.2 261.5 L308.1 244.1 L310.1 244.7 L312.6 238.9 L330.2 224.7Z",
			},
			label: {
				x: 336.5,
				y: 244.3,
				lines: ["Max-", "vorstadt"],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Altbau und Nachkriegsbauten rund um die Universitäten",
			hint: "Viele Mieterwechsel: Ablesewerte liegen per Funk vor, ohne Termin vor Ort.",
		},
		{
			name: "Schwabing-West",
			shape: {
				kind: "path",
				d: "M352.3 174.0 L371.9 175.0 L372.1 177.6 L365.9 178.4 L368.4 195.6 L367.6 201.1 L361.8 201.1 L363.1 211.7 L362.7 216.0 L363.9 216.1 L362.0 232.0 L355.8 230.9 L346.8 227.2 L336.3 226.4 L330.2 224.7 L323.4 230.1 L312.9 217.1 L315.8 215.1 L318.4 215.1 L318.8 203.5 L321.0 199.6 L324.9 197.7 L332.7 197.9 L330.7 183.7 L327.5 178.8 L339.0 178.8Z",
			},
			label: {
				x: 345.5,
				y: 198.6,
				lines: ["Schwabing-", "West"],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Jugendstil- und Gründerzeit-Altbau",
			hint: "Wie in der Clemensstraße: bestehende Zähler sofort übernehmen, getauscht wird bei Vertragsende.",
		},
		{
			name: "Au-Haidhausen",
			shape: {
				kind: "path",
				d: "M387.7 264.2 L389.0 264.6 L389.5 267.7 L391.8 265.7 L401.4 268.2 L400.8 273.1 L403.1 274.0 L404.2 274.2 L404.4 272.9 L407.1 271.6 L407.2 270.5 L417.9 272.8 L428.4 273.2 L429.3 276.0 L426.2 276.6 L427.9 283.7 L422.9 284.3 L418.2 286.9 L411.2 296.9 L401.9 306.2 L398.8 306.5 L393.1 311.7 L392.8 311.1 L388.1 313.3 L359.1 321.6 L346.0 314.0 L345.8 312.3 L360.4 300.4 L364.7 297.9 L368.0 297.9 L370.1 296.6 L375.3 290.1 L375.5 289.4 L374.1 288.6 L376.6 284.9 L375.6 284.5 L377.4 281.4 L380.7 279.3 L383.8 273.1 L381.0 275.5 L380.1 275.2 L385.2 270.3Z",
			},
			label: {
				x: 394.4,
				y: 287.2,
				lines: ["Au-", "Haidhausen"],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Gründerzeit im Franzosenviertel, Herbergshäuser in der Au",
			hint: "Kein Parallelbetrieb, kein Datenverlust: Heidi übernimmt nahtlos vom bisherigen Messdienst.",
		},
		{
			name: "Sendling",
			shape: {
				kind: "path",
				d: "M289.4 293.6 L299.0 298.5 L334.2 323.4 L331.5 328.4 L332.9 342.7 L332.3 346.0 L329.9 350.0 L322.8 356.7 L317.4 353.0 L317.6 351.7 L316.3 351.0 L315.0 356.5 L310.3 353.6 L309.6 355.3 L303.8 354.3 L299.2 360.0 L299.1 363.1 L297.9 357.9 L290.4 358.8 L290.1 326.4 L293.3 303.7 L292.3 298.4Z",
			},
			label: {
				x: 310.4,
				y: 334.3,
				lines: ["Sendling"],
				small: true,
			},
			stock: "Altbau und Wohnanlagen der 1950er-Jahre",
			hint: "Montagefenster von 1–2 Stunden pro Wohnung, Ihre Mieter werden rechtzeitig informiert.",
		},
		{
			name: "Sendling-Westpark",
			shape: {
				kind: "path",
				d: "M273.9 277.3 L289.8 294.2 L293.0 300.9 L293.1 306.5 L290.1 326.4 L290.4 358.8 L289.7 359.0 L289.2 354.9 L286.4 355.2 L286.2 357.2 L282.1 357.7 L281.5 358.7 L279.5 358.0 L262.0 360.1 L259.7 356.5 L250.8 363.6 L247.4 363.6 L247.5 364.7 L245.3 365.2 L245.0 370.1 L241.2 370.1 L234.5 363.5 L233.2 360.5 L234.3 353.2 L235.1 303.7 L245.0 305.1 L246.9 301.9 L258.7 293.8 L264.4 286.6Z",
			},
			label: {
				x: 262.4,
				y: 326.4,
				lines: ["Sendling-", "Westpark"],
				lineHeight: 12.1,
			},
			stock: "Wohnanlagen der Nachkriegszeit und der 1970er-Jahre",
			hint: "Viele Einheiten pro Objekt: Rollout im Cluster statt Haus für Haus.",
		},
		{
			name: "Schwanthalerhöhe",
			shape: {
				kind: "path",
				d: "M287.7 261.5 L310.9 263.3 L310.4 267.5 L308.5 270.3 L313.2 271.3 L312.7 277.0 L309.5 280.7 L308.7 286.1 L307.2 289.2 L307.9 292.1 L306.1 294.8 L303.9 302.3 L298.5 298.1 L289.4 293.6 L273.7 277.0 L274.6 276.2 L274.4 270.3 L275.8 267.2 L282.1 264.4 L287.3 265.0Z",
			},
			label: {
				x: 295,
				y: 275.6,
				lines: ["Schwan-", "thalerh."],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Dichte Altbau-Blöcke im Westend",
			hint: "Monatliche Verbrauchsinformation an alle Mieter, automatisch ab Go-live.",
		},
		{
			name: "Neuhausen-Nymphenburg",
			shape: {
				kind: "path",
				d: "M310.4 192.5 L313.9 198.2 L318.6 197.9 L321.0 199.6 L318.8 203.5 L318.4 215.1 L315.8 215.1 L312.9 217.1 L323.4 230.1 L312.6 238.9 L310.1 244.7 L308.1 244.1 L295.2 261.5 L290.0 261.4 L289.6 262.1 L263.2 259.5 L250.7 260.2 L225.1 255.4 L218.2 253.3 L211.4 249.0 L204.6 240.5 L202.0 235.1 L199.6 223.0 L200.3 218.2 L203.2 212.1 L207.2 213.1 L212.2 212.0 L213.7 208.9 L218.2 204.3 L220.4 203.9 L223.8 205.4 L226.0 205.1 L224.7 204.6 L225.3 201.8 L227.9 202.3 L228.6 199.8 L232.7 200.5 L246.8 200.0 L248.5 194.2 L258.0 199.6 L282.0 195.5 L283.5 200.1 L288.4 198.8 L289.0 200.6 L304.3 193.9 L306.2 194.2Z",
			},
			label: {
				x: 271.4,
				y: 226.6,
				lines: ["Neuhausen-", "Nymphenburg"],
				lineHeight: 12.1,
			},
			stock: "Gründerzeit in Neuhausen, Villen in Nymphenburg",
			hint: "Vom Mehrfamilienhaus bis zur Villa: Heidi rechnet schon ab 2 Wohneinheiten ab.",
		},
		{
			name: "Moosach",
			shape: {
				kind: "path",
				d: "M174.6 106.5 L203.3 119.9 L211.3 122.2 L221.4 122.4 L241.4 129.0 L250.2 135.1 L269.4 141.5 L276.2 144.7 L289.3 148.3 L299.5 146.9 L296.8 167.5 L297.8 178.5 L294.9 189.0 L293.8 198.4 L289.0 200.6 L288.4 198.8 L284.4 200.4 L283.5 200.1 L282.0 195.5 L258.0 199.6 L248.5 194.2 L246.8 200.0 L232.7 200.5 L228.6 199.8 L227.9 202.3 L225.3 201.8 L224.7 204.6 L226.0 205.1 L223.8 205.4 L220.3 203.9 L217.0 205.0 L216.7 199.8 L215.3 199.6 L216.3 197.8 L215.4 196.7 L214.3 187.5 L215.0 187.4 L214.9 183.6 L213.0 183.4 L213.2 181.3 L212.0 181.4 L213.8 170.0 L213.9 149.8 L214.9 145.4 L213.5 132.4 L193.8 123.8 L189.7 120.4 L185.3 114.3 L173.8 107.8Z",
			},
			label: {
				x: 243.8,
				y: 168.3,
				lines: ["Moosach"],
			},
			stock: "Siedlungen und Wohnanlagen der Nachkriegszeit",
			hint: "Kein Warten aufs Vertragsende: Heidi startet mit Ihren vorhandenen Zählern.",
		},
		{
			name: "Milbertshofen-Am Hart",
			shape: {
				kind: "path",
				d: "M375.0 59.7 L376.0 86.0 L372.0 117.1 L380.8 115.9 L379.4 127.5 L378.3 127.3 L377.8 135.9 L369.9 136.8 L371.9 175.0 L352.3 174.0 L339.0 178.8 L327.5 178.8 L330.7 183.7 L332.7 197.9 L324.9 197.7 L321.0 199.6 L318.6 197.9 L313.9 198.2 L310.4 192.5 L306.2 194.2 L304.3 193.9 L293.8 198.4 L294.9 189.0 L297.8 178.5 L296.8 167.5 L299.5 146.9 L312.5 143.8 L339.4 142.9 L333.4 78.0 L335.3 70.5 L333.9 69.8 L337.5 65.3 L336.7 63.0 L337.7 62.6 L335.5 57.8 L338.3 51.8 L367.0 48.5Z",
			},
			label: {
				x: 362.7,
				y: 77.1,
				lines: ["Milbertshofen-", "Am Hart"],
				lineHeight: 12.1,
			},
			stock: "Genossenschafts- und Werkswohnungen, viel Neubau",
			hint: "Neubau mit Wohnungswasserzählern: Funkablesung und uVI automatisch.",
		},
		{
			name: "Schwabing-Freimann",
			shape: {
				kind: "path",
				d: "M437.1 46.9 L461.8 55.7 L459.7 58.3 L461.2 65.5 L467.6 68.2 L466.7 69.2 L467.3 70.1 L480.0 77.2 L480.3 84.1 L478.8 90.3 L475.3 96.1 L464.8 104.4 L461.2 110.1 L458.8 125.3 L450.0 148.3 L444.8 158.4 L448.6 161.5 L445.7 165.1 L443.4 170.5 L440.0 167.5 L393.5 245.1 L388.5 242.0 L386.5 239.5 L381.9 227.5 L378.8 227.3 L379.8 232.5 L376.8 236.5 L376.0 235.5 L372.7 237.8 L371.9 239.4 L366.5 238.4 L367.7 233.3 L362.0 232.0 L363.9 216.1 L362.7 216.0 L363.1 211.7 L361.7 202.2 L361.8 201.1 L367.6 201.1 L368.4 195.6 L365.9 178.4 L372.1 177.6 L369.9 136.8 L377.8 135.9 L378.3 127.3 L379.4 127.5 L380.3 122.6 L379.6 122.5 L380.8 115.9 L372.0 117.1 L376.0 86.0 L399.4 86.3 L399.4 77.6 L404.6 76.1 L404.3 73.9 L406.7 73.8 L406.6 71.8 L415.5 72.0 L405.8 53.0 L408.8 51.6 L408.1 49.6 L411.1 48.9 L411.4 50.9 L408.8 51.7 L409.8 55.8 L417.8 56.0 L419.8 50.1 L433.6 51.1 L433.4 48.1 L436.3 48.2Z",
			},
			label: {
				x: 419.4,
				y: 117.2,
				lines: ["Schwabing-", "Freimann"],
				lineHeight: 12.1,
			},
			stock: "Altbau in Alt-Schwabing, Großsiedlungen in Freimann",
			hint: "Unterschiedliche Bestände, ein Ablauf: Analyse, Pilotobjekt, dann der Bestand.",
		},
		{
			name: "Bogenhausen",
			shape: {
				kind: "path",
				d: "M519.5 164.4 L540.2 168.2 L543.8 164.6 L543.8 162.2 L548.8 162.9 L554.7 169.2 L546.6 173.7 L551.3 177.8 L555.6 183.3 L550.9 192.6 L538.5 189.6 L540.1 194.7 L538.4 200.1 L519.3 227.0 L513.6 222.5 L507.4 220.8 L507.4 236.6 L503.8 253.9 L504.3 258.0 L501.9 267.0 L504.8 267.6 L498.9 272.6 L485.3 283.0 L484.4 279.9 L462.7 277.1 L455.8 277.8 L451.0 280.2 L445.0 278.7 L437.4 279.2 L435.7 278.5 L427.3 280.8 L426.2 276.6 L429.3 276.0 L428.4 273.2 L417.9 272.8 L407.2 270.5 L407.1 271.6 L404.4 272.9 L404.2 274.2 L400.8 273.1 L401.4 268.2 L391.8 265.7 L390.4 267.6 L389.1 267.4 L389.3 265.2 L387.7 264.2 L391.1 249.1 L440.0 167.5 L443.4 170.5 L442.3 175.8 L446.8 176.3 L448.5 174.5 L458.0 178.0 L455.9 181.8 L464.3 185.5 L464.8 184.2 L472.3 184.8 L472.1 184.1 L476.3 183.7 L476.3 182.7 L480.8 182.7 L480.7 181.6 L504.9 178.6 L504.9 176.5 L497.5 169.8 L497.4 165.0 L499.4 162.0Z",
			},
			label: {
				x: 456.2,
				y: 235.1,
				lines: ["Bogenhausen"],
			},
			stock: "Altbau, Villen und große Wohnanlagen",
			hint: "Gemischte Portfolios: alte und neue Zählertechnik in einer Abrechnung.",
		},
		{
			name: "Berg am Laim",
			shape: {
				kind: "path",
				d: "M461.5 277.1 L484.4 279.9 L487.7 293.0 L490.0 297.0 L482.2 315.3 L480.4 319.0 L479.2 318.4 L478.3 320.1 L473.3 331.9 L469.7 329.9 L468.7 330.3 L465.0 327.1 L459.4 324.4 L439.2 318.5 L413.5 315.6 L406.4 316.0 L398.1 307.2 L400.2 305.9 L401.9 306.2 L411.0 297.2 L418.2 286.9 L422.9 284.3 L427.9 283.7 L427.3 280.8 L435.7 278.5 L437.4 279.2 L445.0 278.7 L451.0 280.2 L455.8 277.8Z",
			},
			label: {
				x: 462,
				y: 298.8,
				lines: ["Berg am", "Laim"],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Wohnanlagen der 1950er- bis 1970er-Jahre und Neubau",
			hint: "Abrechnung auf Knopfdruck, direkt übergeben an Ihre Verwaltungssoftware.",
		},
		{
			name: "Trudering-Riem",
			shape: {
				kind: "path",
				d: "M507.4 220.8 L513.9 222.6 L519.3 227.0 L518.8 227.6 L528.6 235.5 L525.9 257.8 L578.1 248.3 L584.1 255.0 L580.2 257.0 L583.2 260.6 L578.5 264.0 L584.3 270.6 L586.8 272.2 L591.6 274.1 L595.9 270.8 L600.0 275.6 L594.7 279.6 L595.9 282.5 L587.3 286.3 L586.0 283.3 L582.4 284.9 L585.9 289.9 L581.4 293.1 L584.2 295.5 L586.1 294.2 L588.8 297.8 L585.1 307.5 L581.9 310.7 L579.8 308.1 L576.7 311.6 L576.3 310.7 L574.3 312.2 L572.2 312.2 L569.1 314.5 L558.3 304.8 L552.4 310.4 L558.0 315.2 L555.5 318.5 L554.0 317.3 L552.2 319.7 L559.5 323.1 L579.7 329.1 L576.8 332.4 L586.2 340.9 L583.1 355.7 L577.5 361.4 L562.4 369.8 L556.5 374.1 L552.5 374.9 L543.6 380.4 L543.9 382.6 L540.7 383.8 L535.1 375.8 L530.9 375.5 L512.9 368.0 L504.2 365.4 L503.9 362.3 L507.2 356.6 L497.7 346.7 L491.7 344.3 L487.6 340.9 L478.5 340.1 L468.7 330.3 L469.7 329.9 L473.3 331.9 L478.3 320.1 L479.2 318.4 L480.4 319.0 L482.2 315.3 L490.0 297.0 L487.7 293.0 L485.3 283.0 L504.8 267.6 L501.9 267.0 L504.3 258.0 L503.8 253.9 L507.4 236.6Z",
			},
			label: {
				x: 517.8,
				y: 316.5,
				lines: ["Trudering-", "Riem"],
				lineHeight: 12.1,
			},
			stock:
				"Einfamilienhäuser in Trudering, Neubauquartiere in der Messestadt Riem",
			hint: "Neubau mit Funkzählern: Ablesung und uVI laufen vom ersten Monat an.",
		},
		{
			name: "Ramersdorf-Perlach",
			shape: {
				kind: "path",
				d: "M397.9 307.2 L406.4 316.0 L413.5 315.6 L436.4 318.0 L462.7 325.8 L467.4 329.1 L478.5 340.1 L487.6 340.9 L491.7 344.3 L497.7 346.7 L507.2 356.6 L503.9 362.3 L504.2 365.4 L512.9 368.0 L530.9 375.5 L535.1 375.8 L543.4 387.1 L538.3 386.4 L533.9 387.4 L530.5 407.2 L531.1 410.1 L534.7 413.7 L535.7 419.5 L538.3 423.7 L518.5 420.4 L518.1 421.9 L515.2 422.3 L505.0 421.9 L501.5 419.9 L458.3 408.4 L459.7 408.3 L451.1 406.8 L451.1 402.6 L435.6 399.2 L435.7 397.3 L423.4 396.5 L420.9 381.7 L410.0 381.1 L404.7 378.1 L396.2 360.0 L392.8 348.7 L389.0 334.3 L388.7 327.3 L391.2 314.3Z",
			},
			label: {
				x: 453,
				y: 363.3,
				lines: ["Ramersdorf-", "Perlach"],
				lineHeight: 12.1,
			},
			stock: "Großsiedlung Neuperlach und Wohnanlagen",
			hint: "Hunderte Einheiten pro Quartier: Heidi koordiniert Montage und Mieterinfo komplett.",
		},
		{
			name: "Obergiesing-Fasangarten",
			shape: {
				kind: "path",
				d: "M392.8 311.1 L390.4 316.4 L388.5 330.1 L389.8 337.9 L396.2 360.0 L403.4 375.9 L406.2 379.5 L410.0 381.1 L420.9 381.7 L423.4 396.5 L421.4 396.5 L421.5 397.5 L415.6 397.3 L416.0 399.8 L407.2 400.5 L402.2 404.9 L399.3 399.2 L393.6 401.1 L392.6 402.8 L388.1 403.9 L387.6 403.0 L387.3 404.4 L385.8 405.1 L384.1 404.8 L382.8 398.8 L377.4 384.1 L374.7 383.0 L372.2 383.8 L377.0 381.1 L371.8 368.5 L366.5 371.9 L366.0 371.0 L366.8 359.7 L365.8 357.0 L366.9 356.5 L360.6 342.6 L358.4 339.8 L352.8 337.4 L356.1 330.2 L357.8 328.3 L358.4 321.6 L388.1 313.3Z",
			},
			label: {
				x: 373.2,
				y: 331.6,
				lines: ["Obergiesing-", "Fasangarten"],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Altbau in Giesing, Wohnanlagen der Nachkriegszeit",
			hint: "Die Kündigung beim bisherigen Messdienst übernimmt Heidi per Vollmacht.",
		},
		{
			name: "Untergiesing-Harlaching",
			shape: {
				kind: "path",
				d: "M345.5 312.6 L346.0 314.0 L358.2 321.2 L357.8 328.3 L355.9 330.6 L352.9 338.0 L357.3 339.2 L359.9 341.5 L366.9 356.5 L365.8 357.0 L366.8 359.7 L366.1 371.2 L366.5 371.9 L371.8 368.5 L377.0 381.1 L354.0 394.2 L353.9 395.5 L352.0 395.3 L334.9 404.6 L334.2 408.5 L320.0 405.1 L312.1 430.2 L313.4 430.7 L311.9 430.8 L305.9 446.9 L303.7 446.4 L303.5 437.4 L302.1 434.7 L302.9 433.5 L301.4 431.0 L299.9 430.8 L299.6 428.9 L300.9 422.7 L299.1 422.7 L303.8 408.2 L314.2 389.2 L313.6 368.4 L314.4 364.4 L316.0 361.8 L319.1 359.8 L322.0 356.1 L322.8 356.7 L331.0 348.6 L332.8 343.3 L331.6 334.8 L331.9 327.2 L338.1 318.6Z",
			},
			label: {
				x: 341.5,
				y: 371.1,
				lines: ["Untergiesing-", "Harlaching"],
				lineHeight: 10.1,
				small: true,
			},
			stock: "Altbau an der Isar, Villen in Harlaching",
			hint: "Zertifizierte Monteure: 92 % der Montagen klappen beim ersten Termin.",
		},
		{
			name: "Thalkirchen-Obersendling-Forstenried-Fürstenried-Solln",
			shape: {
				kind: "path",
				d: "M316.8 351.0 L317.4 353.0 L322.0 356.1 L319.1 359.8 L315.6 362.2 L314.3 364.9 L313.6 368.8 L314.2 389.1 L303.8 408.2 L299.1 422.7 L291.7 422.4 L285.3 423.7 L282.9 427.0 L278.8 437.4 L277.5 444.8 L274.2 444.8 L274.2 446.4 L270.2 446.3 L268.9 448.1 L268.7 451.0 L267.3 450.9 L267.3 448.8 L261.8 448.9 L262.2 449.6 L260.8 449.9 L259.8 451.5 L258.9 451.3 L256.5 458.7 L249.7 456.2 L245.2 463.0 L237.6 461.1 L236.8 453.5 L235.7 452.9 L234.9 449.8 L235.7 449.7 L235.2 447.0 L236.6 444.0 L209.5 426.7 L208.5 428.9 L210.8 429.9 L209.3 432.9 L207.1 431.8 L209.2 426.5 L186.5 412.1 L185.8 414.4 L184.2 412.9 L184.9 411.8 L185.8 412.5 L186.4 412.0 L182.5 409.5 L187.0 400.9 L188.8 400.1 L191.5 395.6 L188.8 395.4 L184.4 392.3 L186.7 385.9 L187.5 378.3 L191.4 376.4 L197.7 373.8 L198.6 376.5 L201.1 379.2 L208.2 377.9 L221.7 369.6 L230.1 362.4 L233.3 361.1 L234.5 363.5 L241.2 370.1 L244.8 370.3 L245.3 365.2 L247.5 364.7 L247.4 363.6 L250.8 363.6 L259.7 356.5 L262.0 360.1 L279.5 358.0 L281.5 358.7 L282.1 357.7 L286.2 357.2 L286.4 355.2 L289.2 354.9 L289.7 359.0 L297.9 357.9 L299.1 363.1 L299.2 360.0 L303.8 354.3 L309.6 355.3 L310.3 353.6 L315.0 356.5Z",
			},
			label: {
				x: 250.3,
				y: 387.3,
				lines: [
					"Thalkirchen-",
					"Obersendling-",
					"Forstenried-",
					"Fürstenried-",
					"Solln",
				],
				lineHeight: 12.1,
			},
			stock: "Villen in Solln, Siedlungen in Fürstenried und Forstenried",
			hint: "Große Wohnanlagen: Heidi plant den Rollout Objekt für Objekt, ohne Mehraufwand für Ihr Team.",
		},
		{
			name: "Hadern",
			shape: {
				kind: "path",
				d: "M194.0 291.2 L195.3 295.0 L203.5 292.9 L215.8 293.7 L223.4 298.7 L227.3 304.7 L235.1 303.7 L234.3 353.2 L233.3 361.1 L230.1 362.4 L221.7 369.6 L209.2 377.5 L201.1 379.2 L198.6 376.5 L197.7 373.8 L187.5 378.3 L182.4 369.3 L189.0 356.3 L180.5 353.3 L180.4 354.8 L169.3 354.7 L170.4 346.3 L170.0 331.8 L172.8 331.3 L173.8 323.2 L172.3 310.4 L172.6 297.7 L186.0 294.7 L187.4 293.1Z",
			},
			label: {
				x: 203.9,
				y: 333.1,
				lines: ["Hadern"],
			},
			stock: "Wohnanlagen der 1960er- und 1970er-Jahre",
			hint: "Ein Ansprechpartner ab dem ersten Tag, für alle Objekte im Bestand.",
		},
		{
			name: "Pasing-Obermenzing",
			shape: {
				kind: "path",
				d: "M165.6 177.8 L165.3 182.8 L169.7 182.0 L171.2 183.0 L173.5 182.6 L174.0 181.2 L184.2 177.6 L188.7 179.7 L200.6 191.8 L204.4 188.3 L214.5 187.7 L215.4 196.7 L216.3 197.8 L215.3 199.6 L216.7 199.8 L217.4 205.7 L213.7 208.9 L212.2 212.0 L207.2 213.1 L203.2 212.1 L200.9 216.4 L199.7 221.6 L200.4 229.8 L202.0 235.1 L206.0 242.5 L212.8 250.1 L211.6 256.8 L213.2 257.0 L213.5 257.9 L210.9 267.3 L208.0 271.8 L203.4 283.6 L202.1 289.2 L202.5 293.0 L195.3 295.0 L194.0 291.2 L187.4 293.1 L186.0 294.7 L172.6 297.7 L170.5 293.5 L167.7 293.3 L167.9 292.5 L163.5 291.0 L164.6 288.2 L150.1 285.1 L149.7 287.1 L147.5 286.0 L144.7 290.4 L142.9 285.6 L143.6 284.4 L128.2 281.8 L128.9 279.9 L125.3 276.7 L137.6 247.0 L143.8 241.8 L153.3 239.4 L153.7 237.0 L143.8 233.4 L131.8 221.3 L119.5 211.3 L121.2 209.4 L121.0 208.2 L123.2 204.5 L131.9 195.3 L128.2 190.8 L130.4 188.2 L127.9 185.0 L127.2 182.2 L138.6 179.9 L142.7 181.7 L145.4 184.6Z",
			},
			label: {
				x: 178.6,
				y: 256.6,
				lines: ["Pasing-", "Obermenzing"],
				lineHeight: 12.1,
			},
			stock: "Altbau in Pasing, Villenkolonien und Neubau",
			hint: "Mieter werden 14 Tage vorher informiert, Rückfragen laufen über Heidi.",
		},
		{
			name: "Aubing-Lochhausen-Langwied",
			shape: {
				kind: "path",
				d: "M117.9 108.3 L135.3 109.9 L129.2 114.4 L126.0 120.8 L125.6 125.1 L127.2 137.1 L127.1 144.6 L115.3 147.4 L117.2 154.1 L127.2 160.2 L125.5 163.3 L125.6 170.5 L127.3 173.6 L134.4 180.6 L131.0 182.0 L127.2 182.2 L127.9 185.0 L130.4 188.2 L128.2 190.8 L131.9 195.3 L123.2 204.5 L121.0 208.2 L121.2 209.4 L119.5 211.3 L131.8 221.3 L143.8 233.4 L153.7 237.0 L153.3 239.4 L143.8 241.8 L137.6 247.0 L124.7 278.1 L122.4 276.2 L114.7 274.5 L108.5 277.1 L105.9 280.0 L103.7 285.8 L102.0 287.6 L89.1 297.7 L79.8 302.7 L68.7 305.3 L55.8 304.4 L53.4 296.9 L47.8 298.6 L46.3 293.9 L47.4 289.1 L45.4 281.9 L48.7 279.8 L48.4 278.4 L52.0 276.7 L47.6 265.4 L50.5 263.7 L47.4 254.2 L48.9 253.6 L47.0 248.8 L43.8 250.2 L41.0 244.5 L38.5 246.1 L38.5 244.2 L37.1 244.4 L36.6 236.0 L31.0 234.8 L31.1 234.1 L28.6 234.1 L28.6 235.6 L21.8 234.8 L21.2 233.2 L22.6 233.5 L21.7 229.9 L23.8 230.0 L23.4 228.8 L15.0 226.7 L15.7 223.8 L17.3 222.7 L9.7 222.1 L0.0 223.6 L3.3 211.2 L7.7 208.0 L12.5 195.4 L14.7 183.2 L13.7 178.1 L17.2 173.3 L21.4 172.9 L23.7 171.4 L27.6 171.8 L33.6 170.8 L37.0 174.0 L40.6 175.2 L44.2 171.9 L45.7 168.8 L50.0 165.5 L53.8 158.1 L50.5 155.4 L51.8 152.3 L52.2 145.4 L49.3 143.6 L49.6 142.9 L46.0 142.2 L49.8 118.3 L67.5 117.1 L69.0 116.0 L69.7 116.7 L72.7 116.1 L92.9 111.7 L96.2 112.6 L97.6 110.7 L118.2 106.6Z",
			},
			label: {
				x: 73.4,
				y: 199.5,
				lines: ["Aubing-", "Lochhausen-", "Langwied"],
				lineHeight: 12.1,
			},
			stock: "Einfamilienhäuser, Siedlungen und Neubau in Freiham",
			hint: "Vom Reihenhaus bis zum Neubauquartier: ein Ablauf für den ganzen Bestand.",
		},
		{
			name: "Allach-Untermenzing",
			shape: {
				kind: "path",
				d: "M192.7 70.9 L205.0 87.5 L205.3 93.3 L201.3 94.9 L202.3 112.3 L200.2 115.6 L200.2 118.7 L174.6 106.5 L173.8 107.8 L185.3 114.3 L189.7 120.4 L193.8 123.8 L213.5 132.4 L214.9 145.4 L213.9 149.8 L213.8 170.0 L212.0 181.4 L213.2 181.3 L213.0 183.4 L214.9 183.6 L215.0 187.4 L204.4 188.3 L200.6 191.8 L188.7 179.7 L184.2 177.6 L171.2 183.0 L169.7 182.0 L165.3 182.8 L165.6 177.8 L145.4 184.6 L140.3 180.4 L136.6 179.8 L134.4 180.6 L127.3 173.6 L125.6 170.5 L125.5 163.3 L127.2 160.2 L117.2 154.1 L115.3 147.4 L127.1 144.6 L127.2 137.1 L125.6 125.1 L126.0 120.8 L129.2 114.4 L135.3 109.9 L117.8 108.8 L118.6 105.2 L128.6 105.0 L128.7 104.1 L137.1 103.7 L138.0 102.2 L160.4 97.6 L162.8 90.7 L165.2 89.6 L165.1 86.7 L168.1 82.8 L180.5 74.1 L186.0 71.4Z",
			},
			label: {
				x: 162.6,
				y: 140.1,
				lines: ["Allach-", "Untermenzing"],
				lineHeight: 12.1,
			},
			stock: "Siedlungen und Einfamilienhäuser",
			hint: "Funkablesung ohne Termin vor Ort, auch in kleinen Objekten.",
		},
		{
			name: "Feldmoching-Hasenbergl",
			shape: {
				kind: "path",
				d: "M272.7 16.9 L280.1 38.9 L282.2 41.7 L287.0 41.5 L286.9 43.8 L299.9 47.0 L299.7 47.9 L302.4 48.1 L302.9 46.4 L303.1 47.1 L304.0 46.8 L303.9 48.2 L305.3 50.2 L309.3 52.4 L338.3 51.8 L335.5 57.8 L337.7 62.6 L336.7 63.0 L337.5 65.3 L333.9 69.8 L335.3 70.5 L333.4 78.0 L339.4 142.9 L312.5 143.8 L293.6 148.1 L287.4 148.0 L250.2 135.1 L243.7 130.2 L237.3 127.6 L221.4 122.4 L211.3 122.2 L200.2 118.7 L200.2 115.6 L202.3 112.3 L201.3 94.9 L205.3 93.3 L205.0 87.5 L192.7 70.9 L193.3 69.8 L215.9 62.1 L212.3 61.2 L210.9 54.3 L211.7 46.6 L210.4 39.8 L214.2 33.0 L213.3 25.2 L216.6 24.6 L217.3 20.8 L215.5 17.8 L216.7 15.7 L215.1 11.6 L215.7 5.8 L230.5 1.7 L230.4 0.0 L233.0 0.1 L252.6 5.9Z",
			},
			label: {
				x: 279,
				y: 90.4,
				lines: ["Feldmoching-", "Hasenbergl"],
				lineHeight: 12.1,
			},
			stock: "Großsiedlung am Hasenbergl, Siedlungen in Feldmoching",
			hint: "Viele Mietparteien: Aushänge, Termine und Rückfragen laufen über Heidi.",
		},
		{
			name: "Laim",
			shape: {
				kind: "path",
				d: "M218.2 253.3 L249.6 260.1 L263.2 259.5 L279.5 261.5 L287.7 261.5 L287.3 265.0 L282.1 264.4 L275.8 267.2 L274.4 270.3 L274.6 276.2 L273.9 277.3 L264.4 286.6 L258.7 293.8 L246.9 301.9 L245.0 305.1 L235.1 303.7 L227.3 304.7 L225.0 300.4 L218.3 294.8 L211.2 293.1 L202.5 293.0 L202.1 290.4 L205.2 278.4 L212.1 263.4 L213.5 257.9 L213.2 257.0 L211.6 256.8 L212.8 250.1Z",
			},
			label: {
				x: 237.2,
				y: 283.6,
				lines: ["Laim"],
				small: true,
			},
			stock: "Wohnanlagen der 1920er- bis 1950er-Jahre",
			hint: "Plausibilitätsprüfung für jede Einheit, bevor die Abrechnung rausgeht.",
		},
	],
	defaultDistrict: "Schwabing-West",
	marker: {
		x: 354.1,
		y: 215.8,
	},
	style: {
		strokeWidth: 1.6,
		labelSize: 10.5,
		legacyFrame: "narrow",
	},
};

export default map;
