// Generated by scripts/extract-city.ts from the "Heidi München" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/muenchen/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/muenchen/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./muenchen-map";

const content: RegionContent = {
	slug: "muenchen",
	seo: {
		title: "Messdienstanbieter München ohne Hürden | Heidi Systems",
		description:
			"Messdienst für Hausverwaltungen in München: Heidi übernimmt Ihre Zähler von Schwabing bis Trudering sofort, mit Montage, Mieterinfo, uVI und Abrechnung.",
		ogTitle: "Messdienst wechseln in München. Ohne Hürden.",
	},
	links: { nearby: ["augsburg", "stuttgart"] },
	name: "München",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Münchner Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in München",
		title: "Messdienst wechseln in München. Ohne Hürden.",
		lede: "Wechseln Sie zu Heidi, ohne auf das Vertragsende zu warten. Wir übernehmen Ihre vorhandenen Zähler und erledigen den Rest: Montage, Mieterinfo, Ablesung und die Heizkostenabrechnung per Klick.",
		checks: [
			"Vorhandene Zähler direkt übernehmen",
			"Ein Ansprechpartner für alles",
			"Heizkostenabrechnung per Klick",
		],
		photoAlt: "Münchner Altbau-Mehrfamilienhaus",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Clemensstraße 12",
		area: "Schwabing-West · Altbau",
		units: 24,
		secondAddress: "Elsässer Str. 31",
		appointment: {
			day: "Di, 14.10.",
			time: "8–10 Uhr",
		},
		avatars: ["AK", "MS", "JB"],
		tenant: "AK",
	},
	logoStrip: {
		text: "Hausverwaltungen in ganz Deutschland rechnen bereits mit Heidi ab.",
		logos: [
			"dumax",
			"werne",
			"lhm",
			"hsp",
			"niesen",
			"raumgold",
			"vitec",
			"neckar",
			"schleicher",
			"progera",
			"harte",
			"wagner",
		],
	},
	noWait: {
		eyebrow: "Sofort wechseln",
		title: "Altvertrag noch nicht abgelaufen? Kein Problem.",
		text: "Heidi übernimmt Auswertung und Abrechnung mit Ihren bestehenden Zählern, ganz gleich, wie lange Ihr bisheriger Messdienstvertrag noch gilt. Neue Funkzähler kommen erst zum Vertragsende.",
		notes: [
			"Nahtloser Übergang ohne Datenverlust",
			"Kündigung per Vollmacht durch Heidi",
			"Fester Ansprechpartner ab Tag eins",
		],
	},
	allInOne: {
		eyebrow: "Rundum-Service",
		title: "Montage, Mieter, Abrechnung. Alles bei Heidi.",
		text: "Eine Unterschrift genügt. Termine, Aushänge und Ablesewerte koordiniert Heidi, Ihr Team wird spürbar entlastet.",
		cards: [
			"Zertifizierte Heidi-Monteure: 92 % der Montagen klappen beim ersten Termin, Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Ankündigungen, Aushänge und Mieterfragen übernimmt Heidi. Ihr Postfach bleibt frei.",
			"Per Funk abgelesen, ohne Termin in der Wohnung. Dazu jeden Monat die uVI nach HKVO, vollautomatisch.",
			"Heizkostenabrechnung per Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz München",
		title: "Von Pasing bis Trudering. In allen 25 Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Münchner Bestände übernimmt.",
		legend: "Beispielobjekt Clemensstraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Mit einem Klick erledigt.",
		text: "Die Verbräuche kommen per Funk, die Kostenarten sind hinterlegt. Ein Klick genügt, und Heidi rechnet jede Einheit ab.",
		checks: [
			"Rechtssicher nach HKVO",
			"Plausibilitätscheck für jede Wohnung",
			"Direkt in Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für München",
		title: "Ein fester Ansprechpartner für Ihren Münchner Bestand.",
		text: "Ihre Verwaltung bekommt eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen in München nach demselben bewährten Ablauf.",
		kpis: [
			"der Montagen klappen beim ersten Termin",
			"Tage vorher werden Ihre Mieter informiert",
			"Zeitfenster pro Wohnung am Montagetag",
		],
	},
	duo: {
		uvi: {
			title: "Monatliche Verbrauchsinfo für Ihre Mieter. Vollautomatisch.",
			text: "Ihre Mieter sehen jeden Monat, was sie verbraucht haben, nach HKVO und im Vergleich zum Vorjahr. Für Ihr Team entsteht keine Arbeit.",
		},
		portfolio: {
			title: "Alle Liegenschaften. Eine Plattform.",
			text: "Ob Montage, Ablesung oder Abrechnung: Sie sehen jede Liegenschaft an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Die Verbrauchswerte liegen per Funk bereit. Ein Klick, und die Abrechnung für jede Einheit steht, rechtssicher nach HKVO.",
		"Heidi kündigt per Vollmacht, montiert, informiert Ihre Mieter und rechnet ab. Sie müssen nichts koordinieren.",
		"Jede Mietpartei erhält einen persönlichen Zugang und sieht ihre monatliche Verbrauchsinformation, so wie es die HKVO vorschreibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Übernimmt Heidi unsere vorhandenen Zähler?",
			answer:
				"Ja. Wir lesen Ihre bestehenden Zähler aus, werten die Verbräuche aus und rechnen ab. Getauscht wird erst zum Ende Ihres bisherigen Messdienstvertrags.",
		},
		{
			question: "Können wir vor Vertragsende wechseln?",
			answer:
				"Ja, sofort und unabhängig von der Restlaufzeit. Mit Ihrer Vollmacht kündigen wir beim bisherigen Messdienst.",
		},
		{
			question: "Wie erfahren die Mieter von der Montage?",
			answer:
				"Über Heidi. Wir kündigen Montagen 14 Tage im Voraus an, nennen ein Zeitfenster von 1–2 Stunden und kümmern uns um Rückfragen.",
		},
		{
			question: "Wie lange dauert die Heizkostenabrechnung?",
			answer:
				"Einen Klick: Die Verbräuche liegen per Funk vor, Heidi erstellt die Abrechnung. Sie prüfen sie und geben sie frei.",
		},
		{
			question: "Wie setzen sich die Kosten zusammen?",
			answer:
				'Sie zahlen pro tatsächlich installiertem Zähler, dazu kommt eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein konkretes <a href="/preise">Angebot</a> für Ihren Münchner Bestand.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in München. Heute.",
		sub: "Eine Unterschrift genügt. Den Rest erledigt Heidi.",
	},
};

export default content;
