// Generated by scripts/extract-city.ts from the "Heidi Münster" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/muenster/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/muenster/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./muenster-map";

const content: RegionContent = {
	slug: "muenster",
	seo: {
		title: "Messdienstanbieter Münster: reibungslos | Heidi Systems",
		description:
			"Messdienst in Münster, vom Kreuzviertel bis Hiltrup: Heidi übernimmt Ihre vorhandenen Zähler sofort und erledigt Montage, Ablesung und Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Münster. Reibungslos und sofort.",
	},
	links: { nearby: ["bielefeld", "dortmund", "bochum"] },
	name: "Münster",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Münsteraner Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Münster",
		title: "Messdienst wechseln in Münster. Reibungslos und sofort.",
		lede: "Ob Altbau im Kreuzviertel oder Wohnanlage in Kinderhaus: Heidi übernimmt Ihre vorhandenen Zähler sofort und erledigt Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Vorhandene Zähler bleiben",
			"Komplettservice",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Münster",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Hammer Straße 12",
		area: "Südviertel · Altbau",
		units: 12,
		secondAddress: "Wolbecker Straße 31",
		appointment: {
			day: "Mo, 12.10.",
			time: "8–10 Uhr",
		},
		avatars: ["FG", "OP", "DM"],
		tenant: "FG",
	},
	logoStrip: {
		text: "Hausverwaltungen von Nord bis Süd setzen auf Heidi.",
		logos: [
			"raumgold",
			"neckar",
			"schleicher",
			"werne",
			"berlin",
			"hsp",
			"progera",
			"wagner",
			"vitec",
			"harte",
			"niesen",
			"dumax",
		],
	},
	noWait: {
		eyebrow: "Wechsel ohne Wartezeit",
		title: "Restlaufzeit beim alten Messdienst? Egal.",
		text: "Die Restlaufzeit beim bisherigen Messdienst spielt keine Rolle: Heidi liest Ihre vorhandenen Zähler aus und erstellt die Abrechnung. Getauscht wird, wenn der Vertrag endet.",
		notes: [
			"Nahtloser Wechsel, keine Datenlücke",
			"Kündigung erledigt Heidi per Vollmacht",
			"Feste Ansprechperson von Beginn an",
		],
	},
	allInOne: {
		eyebrow: "Ohne Koordinationsaufwand",
		title: "Montage, Mieterinfo, Abrechnung. Ein Ansprechpartner.",
		text: "Von der ersten Montage bis zur fertigen Abrechnung organisiert Heidi alles. Ihr Team spart sich Terminabsprachen, Aushänge und das Einsammeln von Ablesewerten.",
		cards: [
			"Zertifizierte Heidi-Monteure: 92 % der Montagen klappen beim ersten Termin, Ihre Mieter bekommen ein Zeitfenster von 1–2 h.",
			"Heidi übernimmt Aushänge, Terminankündigungen und Rückfragen. Ihr Team wird damit nicht belastet.",
			"Ablesung per Funk, ohne dass jemand in die Wohnung muss. Die monatliche uVI nach HKVO kommt automatisch.",
			"Die Heizkostenabrechnung entsteht mit einem Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Münster",
		title: "Vom Kreuzviertel bis nach Hiltrup. In allen sechs Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Münsteraner Bestände übernimmt.",
		legend: "Beispielobjekt Hammer Straße 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Ein Klick genügt.",
		text: "Die Verbräuche kommen per Funk, die Kostenarten sind hinterlegt. Ein Klick genügt, und Heidi rechnet jede Einheit ab.",
		checks: [
			"Rechtssicher gemäß HKVO",
			"Jede Wohnung auf Plausibilität geprüft",
			"Schnittstelle zu Ihrer Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Münster",
		title: "Ein fester Ansprechpartner für Ihren Münsteraner Bestand.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Kreuzviertel, Hansaviertel oder Hiltrup. Montage, Ablesung und Abrechnung folgen in Münster demselben bewährten Ablauf.",
		kpis: [
			"Erfolgsquote im ersten Anlauf",
			"Tage Ankündigung vor der Montage",
			"Zeitfenster je Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Die uVI für Ihre Mieter. Jeden Monat, ganz automatisch.",
			text: "Heidi stellt jeder Mietpartei monatlich ihren Verbrauch bereit, nach HKVO und mit Vorjahresvergleich. Ihr Team ist nicht beteiligt.",
		},
		portfolio: {
			title: "Alle Objekte im Blick. Auf einer Plattform.",
			text: "Eine Plattform für den ganzen Bestand: Montagen, Ablesungen und Abrechnungen jeder Liegenschaft, mit Heidi-Funkzählern oder übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Per Funk liegen alle Verbräuche vor. Mit einem Klick erstellt Heidi die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Heidi erledigt Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung. Für Ihr Team bleibt nichts zu koordinieren.",
		"Jede Mietpartei erhält einen persönlichen Zugang und sieht ihre monatliche Verbrauchsinformation, so wie es die HKVO vorschreibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Nutzt Heidi unsere bisherigen Zähler weiter?",
			answer:
				"Ja. Die verbauten Zähler bleiben zunächst, Heidi liest sie aus und erstellt daraus die Abrechnung. Erst zum Ende des alten Vertrags tauschen wir.",
		},
		{
			question: "Ist ein Wechsel vor Vertragsende möglich?",
			answer:
				"Nein. Heidi übernimmt ab sofort, egal wie lange der alte Vertrag noch gilt. Um die Kündigung kümmern wir uns per Vollmacht.",
		},
		{
			question: "Wer übernimmt die Mieterinformation?",
			answer:
				"Heidi. Wir kündigen die Montage 14 Tage vorher an, nennen den Mietern ein Zeitfenster von 1–2 Stunden und sind ihr Ansprechpartner bei Fragen.",
		},
		{
			question: "Wie viel Arbeit macht die Heizkostenabrechnung?",
			answer:
				"Sehr schnell. Weil die Verbräuche per Funk vorliegen, erzeugt Heidi die Abrechnung mit einem Klick. Danach prüfen Sie und geben frei.",
		},
		{
			question: "Wie setzen sich die Kosten zusammen?",
			answer:
				'Abgerechnet wird pro tatsächlich installiertem Zähler, dazu eine Abrechnungspauschale. Ihr konkretes <a href="/preise">Angebot</a> für den Münsteraner Bestand bekommen Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Münster. Heute.",
		sub: "Sie unterschreiben einmal. Heidi kümmert sich um alles Weitere.",
	},
};

export default content;
