// Generated by scripts/extract-city.ts from the "Heidi Nürnberg" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/nuernberg/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/nuernberg/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./nuernberg-map";

const content: RegionContent = {
	slug: "nuernberg",
	seo: {
		title: "Messdienstanbieter Nürnberg: sofort wechseln | Heidi Systems",
		description:
			"Messdienst in Nürnberg, vom Altbau in Gostenhof bis Langwasser: Heidi übernimmt Ihre vorhandenen Zähler, Montage, Mieterinfo und die Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Nürnberg. Mit einer Unterschrift.",
	},
	links: { nearby: ["augsburg", "muenchen"] },
	name: "Nürnberg",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Nürnberger Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Nürnberg",
		title: "Messdienst wechseln in Nürnberg. Mit einer Unterschrift.",
		lede: "Vom Altbau in Gostenhof bis zur Großsiedlung Langwasser: Heidi übernimmt Ihre vorhandenen Zähler sofort und organisiert Montage, Mieterinfo, Ablesung und Abrechnung.",
		checks: [
			"Bisherige Zähler direkt weiter nutzen",
			"Rundum betreut",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Nürnberg",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Johannisstraße 12",
		area: "St. Johannis · Altbau",
		units: 28,
		secondAddress: "Fürther Straße 31",
		appointment: {
			day: "Mo, 09.11.",
			time: "8–10 Uhr",
		},
		avatars: ["DM", "TH", "JB"],
		tenant: "DM",
	},
	logoStrip: {
		text: "Hausverwaltungen von Nord bis Süd setzen auf Heidi.",
		logos: [
			"vitec",
			"raumgold",
			"werne",
			"harte",
			"niesen",
			"wagner",
			"progera",
			"dumax",
			"neckar",
			"berlin",
			"hsp",
			"schleicher",
		],
	},
	noWait: {
		eyebrow: "Sofort wechseln",
		title: "Langer Restvertrag? Kein Grund zu warten.",
		text: "Ihr bisheriger Messdienstvertrag läuft weiter, Heidi übernimmt trotzdem schon jetzt Auslesung und Abrechnung mit den vorhandenen Zählern. Der Gerätetausch folgt zum Vertragsende.",
		notes: [
			"Kein Datenverlust beim Umstieg",
			"Kündigung per Vollmacht inklusive",
			"Eine Ansprechperson für alles",
		],
	},
	allInOne: {
		eyebrow: "Komplettservice",
		title: "Ein Partner für den ganzen Ablauf.",
		text: "Mit Ihrer Unterschrift übernimmt Heidi die Organisation. Termine, Aushänge und Ablesewerte sind nicht mehr Sache Ihres Teams.",
		cards: [
			"92 % der Montagen gelingen beim ersten Termin. Zertifizierte Monteure, Zeitfenster von 1–2 h für Ihre Mieter.",
			"Aushänge und Terminankündigungen verschickt Heidi, Rückfragen beantworten wir direkt.",
			"Kein Ablesetermin in der Wohnung: Heidi liest per Funk ab und verschickt monatlich die uVI nach HKVO.",
			"Heizkostenabrechnung auf Knopfdruck, rechtssicher und mit direkter Übergabe an Ihr ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Nürnberg",
		title: "Von St. Johannis bis Langwasser. In der ganzen Stadt.",
		sub: "Fahren Sie über einen Stadtteil und sehen Sie, wie Heidi typische Nürnberger Bestände übernimmt.",
		legend: "Beispielobjekt Johannisstraße 12",
	},
	billing: {
		title: "Ein Klick. Und die Abrechnung steht.",
		text: "Verbräuche per Funk, Kostenarten zugeordnet, Verteilerschlüssel hinterlegt. Sie klicken, Heidi rechnet jede Einheit ab.",
		checks: [
			"Nach Heizkostenverordnung",
			"Plausibilität für jede Einheit geprüft",
			"Direkt in Ihrer Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Nürnberg",
		title: "Ihre Nürnberger Objekte. Eine feste Ansprechperson.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Gostenhof, St. Johannis oder Langwasser. Montage, Ablesung und Abrechnung folgen in Nürnberg demselben bewährten Ablauf.",
		kpis: [
			"Erfolgsquote beim ersten Montagetermin",
			"Tage Ankündigung vor der Montage",
			"Zeitfenster je Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Monat für Monat: die Verbrauchsinfo für Ihre Mieter.",
			text: "Ihre Mieter sehen monatlich ihren Verbrauch nach HKVO, mit Vergleich zum Vorjahresmonat. Ihr Team muss dafür nichts tun.",
		},
		portfolio: {
			title: "Ihr Portfolio. Übersichtlich an einem Ort.",
			text: "Ob Montage, Ablesung oder Abrechnung: Sie sehen jede Liegenschaft an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Die Funkwerte sind schon da. Mit einem Klick erstellt Heidi die Abrechnung jeder Einheit, rechtssicher nach HKVO.",
		"Kündigung per Vollmacht, Montage, Mieterinfo und Abrechnung übernimmt Heidi. Ihr Team muss nichts abstimmen.",
		"Mit einem eigenen Zugang sieht jede Mietpartei jeden Monat ihre Verbrauchsinformation, genau wie es die HKVO verlangt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Nutzt Heidi unsere bisherigen Zähler weiter?",
			answer:
				"Ja. Wir übernehmen Auslesung, Auswertung und Abrechnung mit Ihren Bestandszählern. Ausgetauscht wird erst, wenn der bisherige Messdienstvertrag ausläuft.",
		},
		{
			question: "Müssen wir das Vertragsende abwarten?",
			answer:
				"Nein. Heidi startet direkt, die Restlaufzeit spielt keine Rolle. Gekündigt wird per Vollmacht durch uns.",
		},
		{
			question: "Wie erfahren die Mieter von der Montage?",
			answer:
				"Das machen wir. 14 Tage vor der Montage geht die Ankündigung raus, mit Zeitfenster von 1–2 Stunden. Rückfragen beantwortet Heidi selbst.",
		},
		{
			question: "Wann ist die Heizkostenabrechnung fertig?",
			answer:
				"Einen Klick: Die Verbräuche liegen per Funk vor, Heidi erstellt die Abrechnung. Sie prüfen sie und geben sie frei.",
		},
		{
			question: "Welche Kosten entstehen mit Heidi?",
			answer:
				'Sie zahlen nur für tatsächlich installierte Zähler plus eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein <a href="/preise">Angebot</a> für Ihren Nürnberger Bestand.',
		},
	],
	final: {
		title: "Jetzt in Nürnberg den Messdienst wechseln.",
		sub: "Unterschrift genügt. Alles Weitere macht Heidi.",
	},
};

export default content;
