// Generated by scripts/extract-city.ts from the "Heidi Stuttgart" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/stuttgart/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/stuttgart/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./stuttgart-map";

const content: RegionContent = {
	slug: "stuttgart",
	seo: {
		title: "Messdienstanbieter Stuttgart ohne Umstände | Heidi Systems",
		description:
			"Messdienst in Stuttgart, vom Altbau im Westen bis zur Wohnanlage in Freiberg: Heidi nutzt Ihre vorhandenen Zähler ab sofort und erledigt Montage und Abrechnung.",
		ogTitle: "Messdienst wechseln in Stuttgart. Ohne Umstände.",
	},
	links: { nearby: ["karlsruhe", "mannheim", "augsburg"] },
	name: "Stuttgart",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Stuttgarter Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Stuttgart",
		title: "Messdienst wechseln in Stuttgart. Ohne Umstände.",
		lede: "Vom Altbau im Stuttgarter Westen bis zur Wohnanlage in Freiberg: Heidi nutzt Ihre vorhandenen Zähler ab sofort und erledigt Montage, Mieterkommunikation, Ablesung und Abrechnung.",
		checks: [
			"Vorhandene Zähler sofort übernehmen",
			"Ein Partner für den ganzen Ablauf",
			"Abrechnung per Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Stuttgart",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Gutenbergstraße 12",
		area: "Stuttgart-West · Altbau",
		units: 18,
		secondAddress: "Wagenburgstraße 31",
		appointment: {
			day: "Fr, 09.10.",
			time: "10–12 Uhr",
		},
		avatars: ["MS", "HV", "SY"],
		tenant: "MS",
	},
	logoStrip: {
		text: "Verwaltungen aus ganz Deutschland vertrauen bei der Abrechnung auf Heidi.",
		logos: [
			"harte",
			"wagner",
			"hsp",
			"vitec",
			"neckar",
			"progera",
			"dumax",
			"niesen",
			"raumgold",
			"berlin",
			"werne",
			"schleicher",
		],
	},
	noWait: {
		eyebrow: "Heute wechseln",
		title: "Nicht aufs Vertragsende warten. Heute wechseln.",
		text: "Auch während der Restlaufzeit liest Heidi Ihre vorhandenen Zähler aus und erstellt die Abrechnung. Erst wenn der alte Vertrag ausläuft, tauschen wir auf Heidi-Funkzähler.",
		notes: [
			"Übergang ohne Parallelbetrieb",
			"Kündigung durch Heidi per Vollmacht",
			"Eine Ansprechperson für alles",
		],
	},
	allInOne: {
		eyebrow: "Ein Partner für alles",
		title: "Alles organisiert. Von der ersten Montage an.",
		text: "Eine Unterschrift genügt. Termine, Aushänge und Ablesewerte koordiniert Heidi, Ihr Team wird spürbar entlastet.",
		cards: [
			"Zertifizierte Monteure von Heidi: 92 % Erfolgsquote beim ersten Termin, 1–2 h Zeitfenster pro Wohnung.",
			"Mieterkommunikation läuft über Heidi: Aushänge, Ankündigungen, Rückfragen.",
			"Fernablesung per Funk ohne Wohnungstermin, dazu die monatliche Verbrauchsinformation nach HKVO.",
			"Heizkostenabrechnung per Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Stuttgart",
		title: "Vom Kessel bis auf die Fildern. In allen 23 Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Stuttgarter Bestände übernimmt.",
		legend: "Beispielobjekt Gutenbergstraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung. Per Klick fertig.",
		text: "Die Verbrauchsdaten liegen per Funk vor, die Kosten sind verteilt. Ein Klick, und Heidi erstellt die Heizkostenabrechnung für jede Wohnung im Haus.",
		checks: [
			"Heizkostenverordnung eingehalten",
			"Plausibilitätsprüfung pro Einheit",
			"Anbindung an Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Stuttgart",
		title: "Ihre Stuttgarter Objekte. Eine feste Ansprechperson.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Westen, Bad Cannstatt oder Vaihingen. Montage, Ablesung und Abrechnung folgen in Stuttgart demselben bewährten Ablauf.",
		kpis: [
			"Erfolgsquote im ersten Anlauf",
			"Tage Vorankündigung je Termin",
			"Zeitfenster für die Mieter",
		],
	},
	duo: {
		uvi: {
			title: "Verbrauchsinformation für Mieter. Monat für Monat automatisch.",
			text: "Ihre Mieter erhalten monatlich ihren Verbrauch nach Heizkostenverordnung und den Vergleich zum Vorjahr. Für Ihre Verwaltung entsteht kein Aufwand.",
		},
		portfolio: {
			title: "Ihr Portfolio. Übersichtlich an einem Ort.",
			text: "Alle Liegenschaften an einem Ort: Montagen, Ablesungen und Abrechnungen, für Heidi-Funkzähler wie für übernommene Bestandszähler.",
		},
	},
	trio: [
		"Die Funkwerte sind schon da. Mit einem Klick erstellt Heidi die Abrechnung jeder Einheit, rechtssicher nach HKVO.",
		"Von der Kündigung per Vollmacht bis zur fertigen Abrechnung organisiert Heidi alles, auch Montage und Mieterinfo.",
		"Jede Mietpartei hat einen persönlichen Zugang und sieht dort monatlich ihre Verbrauchsinformation, wie es die HKVO vorgibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Nutzt Heidi unsere bisherigen Zähler weiter?",
			answer:
				"Ja. Heidi liest die vorhandenen Zähler aus, wertet die Verbräuche aus und erstellt die Abrechnung. Ausgetauscht wird erst, wenn Ihr Vertrag mit dem bisherigen Messdienst ausläuft.",
		},
		{
			question: "Was ist mit der Restlaufzeit unseres Vertrags?",
			answer:
				"Nein. Der Wechsel ist sofort möglich, auch bei langer Restlaufzeit. Die Kündigung beim bisherigen Messdienst übernehmen wir mit Ihrer Vollmacht.",
		},
		{
			question: "Wer kündigt die Montage bei den Mietern an?",
			answer:
				"Heidi. Montagen kündigen wir 14 Tage vorher an, mit einem Zeitfenster von 1–2 Stunden, und wir beantworten die Rückfragen der Mieter.",
		},
		{
			question: "Wie kommen wir zur Heizkostenabrechnung?",
			answer:
				"Einen Klick: Die Verbräuche liegen per Funk vor, Heidi erstellt die Abrechnung. Sie prüfen sie und geben sie frei.",
		},
		{
			question: "Wie wird Heidi abgerechnet?",
			answer:
				'Sie zahlen nur für tatsächlich installierte Zähler plus eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein <a href="/preise">Angebot</a> für Ihren Stuttgarter Bestand.',
		},
	],
	final: {
		title: "Jetzt in Stuttgart den Messdienst wechseln.",
		sub: "Einmal unterschreiben, den Rest übernimmt Heidi.",
	},
};

export default content;
