// Generated by scripts/extract-city.ts from the "Heidi Wiesbaden" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/wiesbaden/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/wiesbaden/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./wiesbaden-map";

const content: RegionContent = {
	slug: "wiesbaden",
	seo: {
		title: "Messdienstanbieter Wiesbaden ohne Aufschub | Heidi Systems",
		description:
			"Messdienst für Wiesbadener Hausverwaltungen: vom Rheingauviertel bis Klarenthal übernimmt Heidi Ihre vorhandenen Zähler sofort und die Heizkostenabrechnung.",
		ogTitle: "Messdienst wechseln in Wiesbaden. Ohne Aufschub.",
	},
	links: { nearby: ["frankfurt", "mannheim"] },
	name: "Wiesbaden",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Wiesbadener Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Wiesbaden",
		title: "Messdienst wechseln in Wiesbaden. Ohne Aufschub.",
		lede: "Ob Gründerzeit im Rheingauviertel oder Wohnanlage in Klarenthal: Heidi übernimmt Ihre vorhandenen Zähler sofort und kümmert sich um Montage, Mieterinfo, Ablesung und Abrechnung.",
		checks: [
			"Vorhandene Zähler bleiben",
			"Ein Partner, alle Aufgaben",
			"Heizkostenabrechnung auf Knopfdruck",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Wiesbaden",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Adolfsallee 12",
		area: "Rheingauviertel · Altbau",
		units: 22,
		secondAddress: "Biebricher Allee 31",
		appointment: {
			day: "Do, 15.10.",
			time: "10–12 Uhr",
		},
		avatars: ["RS", "LW", "EK"],
		tenant: "RS",
	},
	logoStrip: {
		text: "Hausverwaltungen von Nord bis Süd setzen auf Heidi.",
		logos: [
			"berlin",
			"progera",
			"hsp",
			"raumgold",
			"harte",
			"schleicher",
			"vitec",
			"werne",
			"niesen",
			"wagner",
			"dumax",
			"neckar",
		],
	},
	noWait: {
		eyebrow: "Heute wechseln",
		title: "Altvertrag noch nicht abgelaufen? Kein Problem.",
		text: "Die Restlaufzeit beim bisherigen Messdienst spielt keine Rolle: Heidi liest Ihre vorhandenen Zähler aus und erstellt die Abrechnung. Getauscht wird, wenn der Vertrag endet.",
		notes: [
			"Ohne Parallelbetrieb, ohne Datenverlust",
			"Kündigung durch Heidi per Vollmacht",
			"Persönlicher Ansprechpartner ab Tag eins",
		],
	},
	allInOne: {
		eyebrow: "Alles erledigt",
		title: "Ein Partner für Montage, Mieter und Abrechnung.",
		text: "Von der ersten Montage bis zur fertigen Abrechnung organisiert Heidi alles. Ihr Team spart sich Terminabsprachen, Aushänge und das Einsammeln von Ablesewerten.",
		cards: [
			"92 % Erfolg beim ersten Termin, 1–2 h Zeitfenster für Ihre Mieter, ausgeführt von zertifizierten Heidi-Monteuren.",
			"Mieterkommunikation läuft über Heidi: Aushänge, Ankündigungen, Rückfragen.",
			"Per Funk abgelesen, ohne Termin in der Wohnung. Dazu jeden Monat die uVI nach HKVO, vollautomatisch.",
			"Rechtssichere Heizkostenabrechnung per Klick, übergeben an Ihr ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Wiesbaden",
		title: "Von Biebrich bis Naurod. In allen Ortsbezirken.",
		sub: "Fahren Sie über einen Ortsbezirk und sehen Sie, wie Heidi typische Wiesbadener Bestände übernimmt.",
		legend: "Beispielobjekt Adolfsallee 12",
	},
	billing: {
		title: "Heizkostenabrechnung in Sekunden.",
		text: "Die Verbräuche kommen per Funk, die Kostenarten sind hinterlegt. Ein Klick genügt, und Heidi rechnet jede Einheit ab.",
		checks: [
			"Rechtssicher nach HKVO erstellt",
			"Jede Einheit auf Plausibilität geprüft",
			"Direkt in Ihrer Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Wiesbaden",
		title: "Ihre Wiesbadener Objekte. Eine feste Ansprechperson.",
		text: "Eine feste Ansprechperson kennt Ihre Objekte, ob Westend, Biebrich oder Bierstadt. Montage, Ablesung und Abrechnung folgen in Wiesbaden demselben bewährten Ablauf.",
		kpis: [
			"Erfolg beim ersten Termin",
			"Tage vorher angekündigt",
			"Zeitfenster je Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Monat für Monat: die Verbrauchsinfo für Ihre Mieter.",
			text: "Verbrauch nach HKVO, jeden Monat, mit Vergleich zum Vorjahr. So informiert Heidi Ihre Mieter, ohne Aufwand für Ihr Team.",
		},
		portfolio: {
			title: "Alle Liegenschaften. Eine Plattform.",
			text: "Montagen, Ablesungen, Abrechnungen. Für jede Liegenschaft auf einer Plattform, egal ob Heidi-Funkzähler oder übernommene Bestandszähler.",
		},
	},
	trio: [
		"Heidi nutzt die per Funk erfassten Werte und erstellt per Klick die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Kündigung per Vollmacht, Montage, Mieterkommunikation und Abrechnung liegen bei Heidi. Ihr Team koordiniert nichts davon.",
		"Jede Mietpartei bekommt einen Zugang und findet dort Monat für Monat ihre Verbrauchsinformation nach HKVO.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Können vorhandene Zähler bleiben?",
			answer:
				"Ja. Ihre vorhandenen Zähler werden von Heidi ausgelesen und ausgewertet, die Abrechnung kommt von uns. Neue Geräte gibt es erst nach Ablauf Ihres alten Messdienstvertrags.",
		},
		{
			question: "Müssen wir das Vertragsende abwarten?",
			answer:
				"Nein, Sie können sofort wechseln. Mit Ihrer Vollmacht kündigen wir den alten Vertrag für Sie, unabhängig davon, wie lange er noch läuft.",
		},
		{
			question: "Wer spricht mit unseren Mietern?",
			answer:
				"Heidi. Wir kündigen jede Montage 14 Tage vorher an, geben ein Zeitfenster von 1–2 Stunden vor und beantworten die Fragen der Mieter.",
		},
		{
			question: "Wann ist die Heizkostenabrechnung fertig?",
			answer:
				"Die Verbrauchsdaten kommen per Funk, also entsteht die Abrechnung per Klick. Ihre Aufgabe: kurz prüfen und freigeben.",
		},
		{
			question: "Was zahlen wir für Heidi?",
			answer:
				'Sie zahlen nur für tatsächlich installierte Zähler plus eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein <a href="/preise">Angebot</a> für Ihren Wiesbadener Bestand.',
		},
	],
	final: {
		title: "Jetzt in Wiesbaden den Messdienst wechseln.",
		sub: "Einmal unterschreiben, den Rest übernimmt Heidi.",
	},
};

export default content;
