// Generated by scripts/extract-city.ts from the "Heidi Wuppertal" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/cities/wuppertal/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/cities/wuppertal/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./wuppertal-map";

const content: RegionContent = {
	slug: "wuppertal",
	seo: {
		title: "Messdienstanbieter Wuppertal, entspannt | Heidi Systems",
		description:
			"Messdienst in Wuppertal vom Luisenviertel bis Ronsdorf: Heidi nutzt Ihre vorhandenen Zähler sofort weiter und erledigt Montage, Ablesung und Abrechnung.",
		ogTitle: "Messdienst wechseln in Wuppertal. Ganz entspannt.",
	},
	links: { nearby: ["duesseldorf", "bochum", "koeln"] },
	name: "Wuppertal",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Wuppertaler Bestand.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in Wuppertal",
		title: "Messdienst wechseln in Wuppertal. Ganz entspannt.",
		lede: "Vom Gründerzeit-Altbau im Luisenviertel bis zur Wohnanlage in Ronsdorf: Heidi nutzt Ihre vorhandenen Zähler sofort weiter und erledigt Montage, Mieterinfo, Ablesung und Abrechnung.",
		checks: [
			"Bestandszähler ab Tag eins",
			"Rundum betreut",
			"Heizkostenabrechnung per Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Wuppertal",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Luisenstraße 12",
		area: "Luisenviertel · Altbau",
		units: 16,
		secondAddress: "Heckinghauser Straße 31",
		appointment: {
			day: "Do, 29.10.",
			time: "10–12 Uhr",
		},
		avatars: ["NB", "FG", "JB"],
		tenant: "NB",
	},
	logoStrip: {
		text: "Hausverwaltungen in ganz Deutschland rechnen bereits mit Heidi ab.",
		logos: [
			"berlin",
			"hsp",
			"vitec",
			"wagner",
			"neckar",
			"schleicher",
			"raumgold",
			"harte",
			"dumax",
			"progera",
			"werne",
			"niesen",
		],
	},
	noWait: {
		eyebrow: "Jetzt umsteigen",
		title: "Altvertrag noch nicht abgelaufen? Kein Problem.",
		text: "Heidi rechnet ab sofort mit Ihren vorhandenen Zählern ab, egal wie lange der alte Vertrag noch gilt. Erst zum Vertragsende tauschen wir auf Heidi-Funkzähler.",
		notes: [
			"Kein Parallelbetrieb nötig",
			"Kündigung durch Heidi per Vollmacht",
			"Eine Ansprechperson für alles",
		],
	},
	allInOne: {
		eyebrow: "Komplett betreut",
		title: "Montage, Mieter, Abrechnung. Alles bei Heidi.",
		text: "Eine Unterschrift genügt. Termine, Aushänge und Ablesewerte koordiniert Heidi, Ihr Team wird spürbar entlastet.",
		cards: [
			"Zertifizierte Monteure von Heidi: 92 % Erfolgsquote beim ersten Termin, 1–2 h Zeitfenster pro Wohnung.",
			"Heidi kündigt Termine an, hängt aus und beantwortet die Fragen der Mieter. Ihr Postfach bleibt ruhig.",
			"Funkablesung ohne Wohnungstermin und die monatliche uVI nach HKVO, automatisch versendet.",
			"Ein Klick zur rechtssicheren Heizkostenabrechnung, die direkt in Ihr ERP- oder CRM-System geht.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Wuppertal",
		title: "Von Vohwinkel bis Beyenburg. In allen zehn Stadtbezirken.",
		sub: "Fahren Sie über einen Stadtbezirk und sehen Sie, wie Heidi typische Wuppertaler Bestände übernimmt.",
		legend: "Beispielobjekt Luisenstraße 12",
	},
	billing: {
		title: "Heizkostenabrechnung in Sekunden.",
		text: "Die Verbrauchsdaten liegen per Funk vor, die Kosten sind verteilt. Ein Klick, und Heidi erstellt die Heizkostenabrechnung für jede Wohnung im Haus.",
		checks: [
			"Rechtssicher nach HKVO",
			"Jede Wohnung auf Plausibilität geprüft",
			"Direkt in Ihre Verwaltungssoftware",
		],
	},
	service: {
		eyebrow: "Service für Wuppertal",
		title: "Ein fester Ansprechpartner für Ihren Wuppertaler Bestand.",
		text: "Ob Elberfeld, Barmen oder Vohwinkel: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"Erfolgsquote beim ersten Montagetermin",
			"Tage Vorankündigung für Ihre Mieter",
			"Zeitfenster je Wohnung",
		],
	},
	duo: {
		uvi: {
			title: "Monatliche Verbrauchsinfo. Automatisch für jede Mietpartei.",
			text: "Verbrauch nach HKVO, jeden Monat, mit Vergleich zum Vorjahr. So informiert Heidi Ihre Mieter, ohne Aufwand für Ihr Team.",
		},
		portfolio: {
			title: "Ein Portal für alle Liegenschaften.",
			text: "Alle Liegenschaften an einem Ort: Montagen, Ablesungen und Abrechnungen, für Heidi-Funkzähler wie für übernommene Bestandszähler.",
		},
	},
	trio: [
		"Alle Verbrauchswerte sind per Funk erfasst. Mit einem Klick entsteht die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Von der Kündigung per Vollmacht bis zur fertigen Abrechnung organisiert Heidi alles, auch Montage und Mieterinfo.",
		"Jede Mietpartei erhält einen persönlichen Zugang und sieht ihre monatliche Verbrauchsinformation, so wie es die HKVO vorschreibt.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Funktioniert Heidi mit unseren bestehenden Zählern?",
			answer:
				"Ja. Wir lesen Ihre bestehenden Zähler aus, werten die Verbräuche aus und rechnen ab. Getauscht wird erst zum Ende Ihres bisherigen Messdienstvertrags.",
		},
		{
			question: "Wechsel trotz laufendem Vertrag möglich?",
			answer:
				"Ja, sofort und unabhängig von der Restlaufzeit. Mit Ihrer Vollmacht kündigen wir beim bisherigen Messdienst.",
		},
		{
			question: "Wer kümmert sich um die Mieter?",
			answer:
				"Heidi. Wir kündigen jede Montage 14 Tage vorher an, geben ein Zeitfenster von 1–2 Stunden vor und beantworten die Fragen der Mieter.",
		},
		{
			question: "Wann ist die Heizkostenabrechnung fertig?",
			answer:
				"Mit einem Klick. Die Funkwerte sind schon da, Heidi rechnet ab, und Sie geben das geprüfte Ergebnis frei.",
		},
		{
			question: "Welche Kosten entstehen mit Heidi?",
			answer:
				'Abgerechnet wird pro tatsächlich installiertem Zähler, dazu eine Abrechnungspauschale. Ihr konkretes <a href="/preise">Angebot</a> für den Wuppertaler Bestand bekommen Sie nach dem Portfolio-Check.',
		},
	],
	final: {
		title: "Wechseln Sie Ihren Messdienst in Wuppertal. Heute.",
		sub: "Unterschreiben, zurücklehnen. Heidi erledigt den Rest.",
	},
};

export default content;
