// Code generated by Slice Machine. DO NOT EDIT.

import AuthorImage from "./AuthorImage/index.svelte";
import AuthorName from "./AuthorName/index.svelte";
import BlogAuthor from "./BlogAuthor/index.svelte";
import BlogImage from "./BlogImage/index.svelte";
import BussinessText from "./BussinessText/index.svelte";
import MainTitle from "./MainTitle/index.svelte";
import Quote from "./Quote/index.svelte";
import RichTextBlock from "./RichTextBlock/index.svelte";
import Subtitle from "./Subtitle/index.svelte";

export const components = {
	author_image: AuthorImage,
	first_name: AuthorName,
	blog_author: BlogAuthor,
	blog_image: BlogImage,
	bussiness_text: BussinessText,
	main_title: MainTitle,
	quote: Quote,
	rich_text_block: RichTextBlock,
	subtitle: Subtitle,
};
