import type { HeatingBillPdfModel } from "./types";

/**
 * Empty model with zero/empty defaults.
 * Used as the initial template for computeHeatingBill — all values are
 * computed from real data.  If real data is missing, fields remain at 0 / "".
 */
export const emptyHeatingBillModel: HeatingBillPdfModel = {
    cover: {
        propertyNumber: "",
        heidiCustomerNumber: "",
        userNumber: "",
        contractorsNames: "",
        contractors: [],
        street: "",
        zip: "",
        ownerFirstName: "",
        ownerLastName: "",
        createdAt: "",
        billingPeriodStart: "",
        billingPeriodEnd: "",
        usagePeriodStart: "",
        usagePeriodEnd: "",
        totalAmount: 0,
        totalAmountFormatted: "0,00 €",
        portalLink: "",
        userId: "",
        securityCode: "",
        qrCodeUrl: "",
    },

    buildingCalc: {
        energyCarrier: "Nah-/Fernwärme",
        energyInvoices: [],
        energyRelief: null,
        energyTotalKwh: 0,
        energyTotalKwhFormatted: "0",
        energyTotalAmount: 0,
        energyTotalAmountFormatted: "0,00 €",

        heatingCostItems: [],
        heatingCostCarryOver: 0,
        heatingCostCarryOverFormatted: "0,00 €",
        heatingCostTotal: 0,
        heatingCostTotalFormatted: "0,00 €",

        distributionCostItems: [],
        distributionCostTotal: 0,
        distributionCostTotalFormatted: "0,00 €",
        grandTotal: 0,
        grandTotalFormatted: "0,00 €",

        warmWater: {
            constantFactor: 2.5,
            volumeM3: 0,
            volumeM3Formatted: "0,00",
            tempDiffHigh: 60,
            tempDiffLow: 10,
            conversionFactor: 1.15,
            conversionOperation: "divide" as const,
            energyKwh: 0,
            energyKwhFormatted: "0,00",
            energySharePercent: 0,
            energySharePercentFormatted: "0,00",
            costFromEnergy: 0,
            costFromEnergyFormatted: "0,00 €",
            deviceRental: 0,
            deviceRentalFormatted: "0,00 €",
            totalCost: 0,
            totalCostFormatted: "0,00 €",
            baseCostPercent: 30,
            baseCostAmount: 0,
            baseCostAmountFormatted: "0,00 €",
            baseCostArea: 0,
            baseCostAreaFormatted: "0,00",
            baseCostRatePerM2: 0,
            baseCostRatePerM2Formatted: "0,000000",
            consumptionCostPercent: 70,
            consumptionCostAmount: 0,
            consumptionCostAmountFormatted: "0,00 €",
            consumptionCostVolume: 0,
            consumptionCostVolumeFormatted: "0,00",
            consumptionCostRatePerM3: 0,
            consumptionCostRatePerM3Formatted: "0,000000",
        },

        heating: {
            energyTotal: 0,
            energyTotalFormatted: "0,00 €",
            minusWarmWater: 0,
            minusWarmWaterFormatted: "0,00 €",
            deviceRental: 0,
            deviceRentalFormatted: "0,00 €",
            totalCost: 0,
            totalCostFormatted: "0,00 €",
            baseCostPercent: 30,
            baseCostAmount: 0,
            baseCostAmountFormatted: "0,00 €",
            baseCostArea: 0,
            baseCostAreaFormatted: "0,00",
            baseCostRatePerM2: 0,
            baseCostRatePerM2Formatted: "0,000000",
            consumptionCostPercent: 70,
            consumptionCostAmount: 0,
            consumptionCostAmountFormatted: "0,00 €",
            consumptionMwh: 0,
            consumptionMwhFormatted: "0,00",
            consumptionCostRatePerMwh: 0,
            consumptionCostRatePerMwhFormatted: "0,000000",
        },
    },

    coldWater: {
        totalCost: 0,
        totalCostFormatted: "0,00 €",
        rateItems: [],
        unitTotalCost: 0,
        unitTotalCostFormatted: "0,00 €",
    },

    unitBreakdown: {
        contractorsNames: "",
        street: "",
        zip: "",
        billingPeriodStart: "",
        billingPeriodEnd: "",
        createdAt: "",

        livingSpaceM2: 0,
        livingSpaceM2Formatted: "0,00",

        heatingBaseCost: 0,
        heatingBaseCostFormatted: "0,00 €",
        heatingBaseCostCalc: "",
        heatingConsumptionMwh: 0,
        heatingConsumptionMwhFormatted: "0,00",
        heatingConsumptionCost: 0,
        heatingConsumptionCostFormatted: "0,00 €",
        heatingConsumptionCalc: "",

        warmWaterBaseCost: 0,
        warmWaterBaseCostFormatted: "0,00 €",
        warmWaterBaseCostCalc: "",
        warmWaterConsumptionM3: 0,
        warmWaterConsumptionM3Formatted: "0,00",
        warmWaterConsumptionCost: 0,
        warmWaterConsumptionCostFormatted: "0,00 €",
        warmWaterConsumptionCalc: "",
        heatingAndWarmWaterTotal: 0,
        heatingAndWarmWaterTotalFormatted: "0,00 €",

        coldWaterItems: [],
        coldWaterTotal: 0,
        coldWaterTotalFormatted: "0,00 €",

        grandTotal: 0,
        grandTotalFormatted: "0,00 €",

        stateRelief: null,

        heatingDevices: [],
        warmWaterDevices: [],
        coldWaterDevices: [],
        heatingDevicesTotal: 0,
        heatingDevicesTotalFormatted: "0,00",
        warmWaterDevicesTotal: 0,
        warmWaterDevicesTotalFormatted: "0,00",
        coldWaterDevicesTotal: 0,
        coldWaterDevicesTotalFormatted: "0,00",
    },

    co2: {
        energyCarrier: "",
        energyRows: [],
        totalKwh: 0,
        totalKwhFormatted: "0",
        totalCo2Kg: 0,
        totalCo2KgFormatted: "0,00",
        totalCost: 0,
        totalCostFormatted: "0,00 €",

        totalLivingSpaceM2: 0,
        totalLivingSpaceM2Formatted: "0,00",
        emissionFactorKgPerKwh: 0,
        emissionFactorFormatted: "0,00000",
        emissionPerM2: 0,
        emissionPerM2Formatted: "0,00",

        classificationTable: [
            { rangeLabel: "< 12 kg/m²/a", tenantPercent: 100, landlordPercent: 0, isHighlighted: false },
            { rangeLabel: "12 bis < 17", tenantPercent: 90, landlordPercent: 10, isHighlighted: false },
            { rangeLabel: "17 bis < 22", tenantPercent: 80, landlordPercent: 20, isHighlighted: false },
            { rangeLabel: "22 bis < 27", tenantPercent: 70, landlordPercent: 30, isHighlighted: false },
            { rangeLabel: "27 bis < 32", tenantPercent: 60, landlordPercent: 40, isHighlighted: false },
            { rangeLabel: "32 bis < 37", tenantPercent: 50, landlordPercent: 50, isHighlighted: false },
            { rangeLabel: "37 bis < 42", tenantPercent: 40, landlordPercent: 60, isHighlighted: false },
            { rangeLabel: "42 bis < 47", tenantPercent: 30, landlordPercent: 70, isHighlighted: false },
            { rangeLabel: "47 bis < 52", tenantPercent: 20, landlordPercent: 80, isHighlighted: false },
            { rangeLabel: "≥ 52", tenantPercent: 5, landlordPercent: 95, isHighlighted: false },
        ],
        selectedTierTenantPercent: 0,
        selectedTierLandlordPercent: 0,

        buildingTenantCost: 0,
        buildingTenantCostFormatted: "0,00 €",
        buildingLandlordCost: 0,
        buildingLandlordCostFormatted: "0,00 €",
        buildingTotalCost: 0,
        buildingTotalCostFormatted: "0,00 €",
        unitTenantCost: 0,
        unitTenantCostFormatted: "0,00 €",
        unitLandlordCost: 0,
        unitLandlordCostFormatted: "0,00 €",
        unitTotalCost: 0,
        unitTotalCostFormatted: "0,00 €",

        qrCodeUrl: "",
        infoLink: "",
    },

    energySummary: {
        energyCarrier: "",
        totalKwh: 0,
        totalKwhFormatted: "0,0",
        co2EmissionFactor: 0,
        co2EmissionFactorFormatted: "0,00000",
        primaryEnergyFactors: [],
        totalCo2Kg: 0,
        totalCo2KgFormatted: "0,00",

        heatingKwh: 0,
        heatingKwhFormatted: "0,0",
        warmWaterKwh: 0,
        warmWaterKwhFormatted: "0,00",
        totalUnitKwh: 0,
        totalUnitKwhFormatted: "0,00",
        livingSpaceM2: 0,
        livingSpaceM2Formatted: "0,00",
        kwhPerM2: 0,
        kwhPerM2Formatted: "0,00",

        nationalAverageKwhPerM2: 0,
        nationalAverageFormatted: "0,0",
        propertyAverageKwhPerM2: 0,
        propertyAverageFormatted: "0,00",

        comparisonHeatingPropertyKwh: 0,
        comparisonHeatingPropertyKwhFormatted: "0",
        comparisonHeatingNationalKwh: 0,
        comparisonHeatingNationalKwhFormatted: "0",
        comparisonWarmWaterPropertyKwh: 0,
        comparisonWarmWaterPropertyKwhFormatted: "0",
        comparisonWarmWaterNationalKwh: 0,
        comparisonWarmWaterNationalKwhFormatted: "0",

        qrCodeUrl: "",
        infoLink: "",
        energyAgencyLink: "",
    },
};
