// Generated by scripts/extract-city.ts from the "Heidi Deutschland" design.
// Edit the design and re-run the script; only `seo` and `links` are hand-written.
import heroPhoto from "$lib/assets/landing/germany/hero.jpg?enhanced";
import referencesPhoto from "$lib/assets/landing/germany/references.jpg?enhanced";
import type { RegionContent } from "$lib/landing/sections/region/types";
import map from "./map";

const content: RegionContent = {
	seo: {
		title: "Messdienstanbieter in ganz Deutschland | Heidi Systems",
		description:
			"Messdienst für Hausverwaltungen in ganz Deutschland: Heidi übernimmt Ihre Zähler sofort und kümmert sich um Montage, Mieterinfo, Ablesung und Abrechnung.",
		ogTitle: "Messdienst wechseln. In ganz Deutschland.",
	},
	links: { nearby: [] },
	name: "Deutschland",
	bannerText:
		"Ab 1.1.2027 müssen Zähler und Heizkostenverteiler fernablesbar sein. Wir prüfen Ihren Bestand, bundesweit.",
	hero: {
		tag: "Messdienst für Hausverwaltungen in ganz Deutschland",
		title: "Messdienst wechseln. In ganz Deutschland.",
		lede: "Von der Gründerzeit in Leipzig bis zur Großsiedlung im Ruhrgebiet: Heidi übernimmt Ihre vorhandenen Zähler sofort und kümmert sich bundesweit um Montage, Mieterinfo, Ablesung und Heizkostenabrechnung.",
		checks: [
			"Bisherige Zähler direkt weiter nutzen",
			"Ein Partner, alle Aufgaben",
			"Abrechnung mit einem Klick",
		],
		photoAlt: "Altbau-Mehrfamilienhaus in Deutschland",
		units: 24,
		photo: heroPhoto,
	},
	example: {
		address: "Bahnhofstraße 12",
		area: "Altbau · bundesweites Portfolio",
		units: 32,
		secondAddress: "Lindenallee 31",
		appointment: {
			day: "Fr, 16.10.",
			time: "8–10 Uhr",
		},
		avatars: ["JB", "DM", "OP"],
		tenant: "JB",
	},
	logoStrip: {
		text: "Bundesweit rechnen Hausverwaltungen schon mit Heidi ab.",
		logos: [
			"neckar",
			"schleicher",
			"niesen",
			"progera",
			"harte",
			"vitec",
			"raumgold",
			"dumax",
			"berlin",
			"wagner",
			"werne",
			"hsp",
		],
	},
	noWait: {
		eyebrow: "Heute wechseln",
		title: "Altvertrag noch nicht abgelaufen? Kein Problem.",
		text: "Die Restlaufzeit beim bisherigen Messdienst spielt keine Rolle: Heidi liest Ihre vorhandenen Zähler aus und erstellt die Abrechnung. Getauscht wird, wenn der Vertrag endet.",
		notes: [
			"Nahtloser Wechsel, keine Datenlücke",
			"Vollmacht genügt für die Kündigung",
			"Eine Ansprechperson für alles",
		],
	},
	allInOne: {
		eyebrow: "Komplett betreut",
		title: "Montage, Mieter, Abrechnung. Alles bei Heidi.",
		text: "Eine Unterschrift genügt. Termine, Aushänge und Ablesewerte koordiniert Heidi, Ihr Team wird spürbar entlastet.",
		cards: [
			"92 % Erfolg beim ersten Termin, 1–2 h Zeitfenster für Ihre Mieter, ausgeführt von zertifizierten Heidi-Monteuren.",
			"Ihre Mieter wenden sich an Heidi, nicht an Ihre Verwaltung. Aushänge und Terminankündigungen inklusive.",
			"Ablesung per Funk, ohne dass jemand in die Wohnung muss. Die monatliche uVI nach HKVO kommt automatisch.",
			"Heizkostenabrechnung per Klick, rechtssicher und direkt in Ihrem ERP- oder CRM-System.",
		],
	},
	map: {
		...map,
		eyebrow: "In ganz Deutschland",
		title: "Von Flensburg bis Garmisch. In allen 16 Bundesländern.",
		sub: "Fahren Sie über ein Bundesland oder klicken Sie auf einen Punkt, um direkt die passende Städteseite zu öffnen.",
		legend: "Städte mit eigener Heidi-Seite (anklicken)",
	},
	billing: {
		title: "Abrechnen mit einem Klick.",
		text: "Verbräuche per Funk, Kostenarten zugeordnet, Verteilerschlüssel hinterlegt. Sie klicken, Heidi rechnet jede Einheit ab.",
		checks: [
			"Rechtssicher nach HKVO erstellt",
			"Plausibilitätsprüfung inklusive",
			"Direkt übergeben an Ihre Software",
		],
	},
	service: {
		eyebrow: "Service bundesweit",
		title: "Ihre bundesweiten Objekte. Eine feste Ansprechperson.",
		text: "Ob in einer Stadt oder über ganz Deutschland verteilt: Ihre Verwaltung hat eine feste Ansprechperson, die Ihren Bestand kennt. Montage, Ablesung und Abrechnung laufen nach einem klaren Ablauf.",
		kpis: [
			"Erfolgsquote im ersten Anlauf",
			"Tage Vorlauf für die Mieterinformation",
			"Zeitfenster für die Mieter",
		],
	},
	duo: {
		uvi: {
			title: "Verbrauchsinfo für jede Mietpartei. Jeden Monat.",
			text: "Ihre Mieter sehen monatlich ihren Verbrauch nach HKVO, mit Vergleich zum Vorjahresmonat. Ihr Team muss dafür nichts tun.",
		},
		portfolio: {
			title: "Liegenschaften verwalten. Alles an einem Ort.",
			text: "Ob Montage, Ablesung oder Abrechnung: Sie sehen jede Liegenschaft an einem Ort, mit Heidi-Funkzählern und übernommenen Bestandszählern.",
		},
	},
	trio: [
		"Alle Verbrauchswerte sind per Funk erfasst. Mit einem Klick entsteht die Abrechnung für jede Einheit, rechtssicher nach HKVO.",
		"Kündigung per Vollmacht, Montage, Mieterkommunikation, Abrechnung: Das alles übernimmt Heidi. Ihr Team muss nichts abstimmen.",
		"Jede Mietpartei bekommt einen Zugang und findet dort Monat für Monat ihre Verbrauchsinformation nach HKVO.",
	],
	referencesPhoto: referencesPhoto,
	faq: [
		{
			question: "Können unsere bisherigen Zähler weiter genutzt werden?",
			answer:
				"Ja. Die verbauten Zähler bleiben zunächst, Heidi liest sie aus und erstellt daraus die Abrechnung. Erst zum Ende des alten Vertrags tauschen wir.",
		},
		{
			question: "Können wir vor Vertragsende wechseln?",
			answer:
				"Nein, Sie können sofort wechseln. Mit Ihrer Vollmacht kündigen wir den alten Vertrag für Sie, unabhängig davon, wie lange er noch läuft.",
		},
		{
			question: "Wer kündigt die Montage bei den Mietern an?",
			answer:
				"Heidi informiert sie 14 Tage vor der Montage, nennt ein Zeitfenster von 1–2 Stunden und ist für Rückfragen direkt erreichbar.",
		},
		{
			question: "Wie entsteht die Heizkostenabrechnung?",
			answer:
				"Mit einem Klick. Die Funkwerte sind schon da, Heidi rechnet ab, und Sie geben das geprüfte Ergebnis frei.",
		},
		{
			question: "Wie sieht das Preismodell aus?",
			answer:
				'Sie zahlen nur für tatsächlich installierte Zähler plus eine Abrechnungspauschale. Nach dem Portfolio-Check erhalten Sie ein <a href="/preise">Angebot</a> für Ihren bundesweiten Bestand.',
		},
	],
	final: {
		title: "Jetzt bundesweit den Messdienst wechseln.",
		sub: "Sie unterschreiben einmal. Heidi kümmert sich um alles Weitere.",
	},
};

export default content;
